### ISSUE TITLE
合并 CSL-Chinese-IR-CSSCI-Journals 的样式

### ISSUE THREAD

**Issue by zepinglee** [zotero-chinese/styles#14]
目前已经整理了 https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl 的样式，现在 <https://zotero-cn.github.io/styles/article/> 看起来整齐多了。

下一步打算将 https://github.com/EdwardSaidZhou/CSL-Chinese-IR-CSSCI-Journals 的样式整理进来。

问一下 @EdwardSaidZhou 有没有将这些样式官方的示例条目录入 Zotero 供测试？（比如我们之前将 GB/T 7714 和《法学引注册手册》的全部官方示例录入到 <https://www.zotero.org/groups/4677213/chinese_csl_development/library>，就可以方便大家进行测试和校对）

**Comment by EdwardSaidZhou** [comment]
@zepinglee 在制作CSL样式的时候，是使用《中国社会科学》的示例文献，导入我自己Zotero库进行测试，这会儿我来将中国社会科学的示例条目导入您提供的library以供大家测试校对

**Comment by EdwardSaidZhou** [comment]
@zepinglee 请问如何将《中国社会科学》的示例条目导入 https://www.zotero.org/groups/4677213/chinese_csl_development/library？

**Comment by zepinglee** [comment]
> @zepinglee 在制作CSL样式的时候，是使用《中国社会科学》的示例文献，导入我自己Zotero库进行测试，这会儿我来将中国社会科学的示例条目导入您提供的library以供大家测试校对

那就太好不过了！

顺便问一下，《中国社会科学》的样式在人文社科领域是最有影响力的吗？

> @zepinglee 请问如何将《中国社会科学》的示例条目导入 [https://www.zotero.org/groups/4677213/chinese_csl_development/library？](https://www.zotero.org/groups/4677213/chinese_csl_development/library%EF%BC%9F)

在这里加入群组，然后在 Zotero 界面就可以修改群组中的内容。

不过目前仅限管理员编辑，需要将你的 Zotero id 发给我，然后由我修改提升权限。

**Comment by EdwardSaidZhou** [comment]
> > @zepinglee 在制作CSL样式的时候，是使用《中国社会科学》的示例文献，导入我自己Zotero库进行测试，这会儿我来将中国社会科学的示例条目导入您提供的library以供大家测试校对
> 
> 那就太好不过了！
> 
> 顺便问一下，《中国社会科学》的样式在人文社科领域是最有影响力的吗？
> 
> > @zepinglee 请问如何将《中国社会科学》的示例条目导入 [https://www.zotero.org/groups/4677213/chinese_csl_development/library？](https://www.zotero.org/groups/4677213/chinese_csl_development/library%EF%BC%9F)
> 
> 在这里加入群组，然后在 Zotero 界面就可以修改群组中的内容。
> 
> 不过目前仅限管理员编辑，需要将你的 Zotero id 发给我，然后由我修改提升权限。

@zepinglee 非常感谢，我Zotero的ID为edwardsaidzhou。《中国社会科学》在人文社科领域的影响力还是很大的。

**Comment by zepinglee** [comment]
<img width="857" alt="Screen Shot 2022-08-23 at 09 57 55" src="https://user-images.githubusercontent.com/12290822/186051805-9d46bee1-6e21-420c-bed2-aeed11fe19c2.png">

已经改为管理员了，可以在 Zotero 的界面中编辑。

<img width="217" alt="Screen Shot 2022-08-23 at 10 00 38" src="https://user-images.githubusercontent.com/12290822/186052171-92ceaab4-36fd-416f-8346-69f7b2d9397a.png">

每个期刊的目录仅保存官方提供的示例，其下属的子目录保存需要展示的示例或者额外的测试条目。

**Comment by EdwardSaidZhou** [comment]
> <img alt="Screen Shot 2022-08-23 at 09 57 55" width="857" src="https://user-images.githubusercontent.com/12290822/186051805-9d46bee1-6e21-420c-bed2-aeed11fe19c2.png">
> 
> 已经改为管理员了，可以在 Zotero 的界面中编辑。
> 
> <img alt="Screen Shot 2022-08-23 at 10 00 38" width="217" src="https://user-images.githubusercontent.com/12290822/186052171-92ceaab4-36fd-416f-8346-69f7b2d9397a.png">
> 
> 每个期刊的目录仅保存官方提供的示例，其下属的子目录保存需要展示的示例或者额外的测试条目。

好的，感谢大佬。已经将官方示例放置于 Group Library 的 期刊 分类下。

**Comment by zepinglee** [comment]
简单看了一下，这些文献似乎都是官网  <http://sscp.cssn.cn/tgxt/zgshkxtg/>（附件：关于引文注释的规定）的示例条目？可以放在`期刊/中国社会科学`目录下。`期刊/中国社会科学/中国社会科学-测试`更适合放非官方提供的条目，比如某用户在写自己的文章时引用某文献发现格式不对，可以传到`-测试`的目录中，供 CSL 开发者进行调试。

**Comment by zepinglee** [comment]
另外发现其中某些字段的信息不太合理，比如“卷2”应填在 volume 字段，影印本更适合填在 edition 字段。

我晚些时候再统一进行整理。

**Comment by EdwardSaidZhou** [comment]
> 另外发现其中某些字段的信息不太合理，比如“卷2”应填在 volume 字段，影印本更适合填在 edition 字段。
> 
> 我晚些时候再统一进行整理。

好的，感谢

**Comment by zepinglee** [comment]
目前已经将 https://github.com/EdwardSaidZhou/CSL-Chinese-IR-CSSCI-Journals 的全部样式放入了 [src/](https://github.com/zotero-cn/styles/tree/main/src) 中。其中花了很久寻找每个期刊的英文名。

我在考虑，`src/` 中的目录名和 .csl 样式文件直接使用中文原名是不是更直观一些？而且这样用户下载到的 .csl 文件就是以中文原名的形式。

不过这也可能有缺点：

1. 在 Windows 系统中文路径可能有 GB 18030 / UTF-8 的编码问题；
2. 对于开发者而言，在命令行中打开编辑不太方便。（比如 `code src/manual-of-legal-citation-multi-lingual/manual-of-legal-citation-multi-lingual.csl`）.

@northword 有什么建议？

**Comment by northword** [comment]
> 我在考虑，`src/` 中的目录名和 .csl 样式文件直接使用中文原名是不是更直观一些？而且这样用户下载到的 .csl 文件就是以中文原名的形式。
> 
> 不过这也可能有缺点：
> 
> 1. 在 Windows 系统中文路径可能有 GB 18030 / UTF-8 的编码问题；
> 2. 对于开发者而言，在命令行中打开编辑不太方便。（比如 `code src/manual-of-legal-citation-multi-lingual/manual-of-legal-citation-multi-lingual.csl`）.
> 
> @northword 有什么建议？

都可以吧，不过我更倾向用英文文件名，这会避免一些未知的问题，且更符合 [中文技术文档](https://github.com/ruanyf/document-style-guide/blob/master/docs/structure.md) 对文件名的要求（虽然我们这个也不算技术文档）。

对于用户下载的文件的文件名这个，按照目前的设计，用户安装时候直接在网页点链接就安装好了，不需要下载，且用户不需要访问仓库，所以也没有特别提高对用户的直观性，对咱们阅读起来可能会有一些提高。

不过如果用中文的话，你列的两个问题应该影响不大，

- 中文路径的编码问题，因为读写内容涉及 gbk 字符，读写都会配置 utf-8，所以路径中的中文应该是没问题的，可以测试一下。

- 命令行打开不方便这个，我个人更习惯 code 里打开 styles 整个文件夹，然后在图形界面里打开某个文件，所以对我基本上没有影响。

另一个用中文可能导致问题是，目前网页的路径是和目录名一致的，中文的话，在 url 里会被转码，例如  `https://www.baidu.com/s?wd=测试` 会被转码为 `https://www.baidu.com/s?wd=%E6%B5%8B%E8%AF%95`，且有时候QQ/微信等不能正常识别 url 里的中文，会不正确地截断 url，如果有用户分享网页链接，且分享的是没有转码的，别人打开可能需要复制到浏览器，不能直接点击打开；如果是转码的，则路径是一堆不直观的字符。

不过这个可以在 markdown 文件里写 slug 来修改网页的路径解决，只需要提供英文名或者调其他模块把中文转成拼音（应该是有这种模块的）就好。

也就是，能想到的缺点基本都可以解决，我对文件名用中文还是英文没什么强迫症，看你们的想法嘛。

**Comment by zepinglee** [comment]
感谢这么完整的回复。我现在感觉还是保持现有的英文文件名吧。
