### ISSUE TITLE
请求社会学研究的样式

### ISSUE THREAD

**Issue by balalery** [zotero-chinese/styles#19]
您好，我请求您能在项目中增加《社会学研究》的参考文献样式

**Comment by zepinglee** [comment]
https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/209sociological-studies.csl

**Comment by balalery** [comment]
您好！邮件已收到，祝您生活愉快！

**Comment by balalery** [comment]
> 

>

**Comment by balalery** [comment]
![image](https://user-images.githubusercontent.com/92866440/229513750-a77ee630-b744-4329-8eb1-159c88d3579e.png)
这就是我的问题，麻烦您了！

**Comment by zepinglee** [comment]
> 谢谢您，但是我自己在引用中发现了一些问题。由于我不会编辑csl文件，因此希望您可以改进一下，谢谢您。具体的情况，您可以参考我发的图片。我的意思是，参考文献里的中文文献并不像您展示的那样是一个带有汉字标点的参考文献格式，相反，它用的是英文标点。如果您比较忙的话，也可以大概告诉我一下，如何修改文件，我来更改。谢谢您！ 祝您生活愉快！

参考 https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/issues/new?assignees=&labels=&template=bug_report.md&title= 的示例，将文献导出 CSL-JSON 格式然后贴上来。

**Comment by balalery** [comment]
**修改《社会学研究的样式》**

CSL 样式：sociological-studies.csl


1. 该样式的文中引用——作者-出版年，外面的括号以及里面的逗号（注意要加空格）应该是英文，而非中文。应该把（author，year）改为(author, date)。
2. 该样式的中文样式——没有成功实现，因为我从豆瓣和知网抓取的图书论文，是中文，但是它用了英文格式处理我的中文图书。
3. 该样式中的英文格式——英文作者的姓与名之间，应该加上英文逗号并空格。
**屏幕截图**

如果必要，请添加屏幕截图以帮助解释。截图在下一条消息，麻烦您了！


**条目信息**


1. 中文文献条目出错
```json
[
	{
		"id": "chentaoWuXuDeXingDeLunLiShengHuoHeiGeErLunXianDaiSheHuiDeLiNian2022",
		"type": "article-journal",
		"abstract": "比较黑格尔的伦理概念与古代伦理概念的区别有助于澄清现代社会的理念。在亚里士多德那里，“伦理”是一个借助习惯、法律和政制搭建起来的、旨在塑造人的欲求和欲望的生活方式。对于处在自然德性和思虑德性之间的伦理空间而言，习惯、法律和制度并不是自足的，它们着眼并取决于德性。相比之下，在黑格尔那里，现代人无须具备多么高的德性，仅仅通过服从健全的法律和制度就能够驯化自己的欲望，从而赢得他人的承认和自由。不过，我们需要反思，在法律和制度的健全和完备之外是否还有其他可能性？或许，这仍然取决于我们能否在自身的文明传统中再度唤醒某种伦理特质，去驾驭这些理性化的法律和制度，营造出一种值得欲求的共同生活。",
		"container-title": "社会",
		"DOI": "10.15992/j.cnki.31-1123/c.2022.05.007",
		"ISSN": "1004-8804",
		"issue": "5",
		"language": "中文;",
		"note": "<北大核心, CSSCI, AMI>",
		"page": "95-123",
		"source": "CNKI",
		"title": "无须德性的伦理生活  黑格尔论现代社会的理念",
		"URL": "https://kns.cnki.net/KCMS/detail/detail.aspx?dbcode=CJFD&dbname=CJFDLAST2022&filename=SHEH202205004&v=",
		"volume": "42",
		"author": [
			{
				"literal": "陈涛"
			}
		],
		"issued": {
			"date-parts": [
				[
					"2022"
				]
			]
		}
	}
]
```

2. 中文图书条目出错
```json
[
	{
		"id": "yangkaidaoZhongGuoXiangYueZhiDu2015",
		"type": "book",
		"collection-title": "中华现代学术名著丛书",
		"ISBN": "978-7-100-11714-2",
		"number-of-pages": "253",
		"publisher": "商务印书馆",
		"source": "Douban",
		"title": "中国乡约制度",
		"URL": "https://book.douban.com/subject/26730206/",
		"author": [
			{
				"family": "杨开道",
				"given": ""
			}
		],
		"accessed": {
			"date-parts": [
				[
					"2023",
					4,
					2
				]
			]
		},
		"issued": {
			"date-parts": [
				[
					"2015",
					12
				]
			]
		}
	}
]
```
3. 英文文献条目出错
```json
[
	{
		"id": "colemanSocialCapitalCreation1988",
		"type": "article-journal",
		"abstract": "In this paper, the concept of social capital is introduced and illustrated, its forms are described, the social structural conditions under which it arises are examined, and it is used in an analysis of dropouts from high school. Use of the concept of social capital is part of a general theoretical strategy discussed in the paper: taking rational action as a starting point but rejecting the extreme individualistic premises that often accompany it. The conception of social capital as a resource for action is one way of introducing social structure into the rational action paradigm. Three forms of social capital are examined: obligations and expectations, information channels, and social norms. The role of closure in the social structure in facilitating the first and third of these forms of social capital is described. An analysis of the effect of the lack of social capital available to high school sophomores on dropping out of school before graduation is carried out. The effect of social capital within the family and in the community outside the family is examined.",
		"container-title": "American Journal of Sociology",
		"DOI": "10.1086/228943",
		"ISSN": "0002-9602",
		"note": "publisher: University of Chicago Press",
		"page": "S95-S120",
		"source": "JSTOR",
		"title": "Social Capital in the Creation of Human Capital",
		"URL": "https://www.jstor.org/stable/2780243",
		"volume": "94",
		"author": [
			{
				"family": "Coleman",
				"given": "James S."
			}
		],
		"accessed": {
			"date-parts": [
				[
					"2023",
					3,
					28
				]
			]
		},
		"issued": {
			"date-parts": [
				[
					"1988"
				]
			]
		}
	}
]
```

**其他相关信息**

在此处添加有关该问题的其他信息。感谢您的帮助！

**Comment by balalery** [comment]
![image](https://user-images.githubusercontent.com/92866440/229988682-17473e26-1d29-43b3-a6a3-7d570624bdce.png)

**Comment by zepinglee** [comment]
@balalery 你有这个期刊的参考文献格式要求吗？CSL 样式中记录的网址 <http://shxyj.ajcass.org/Home/channel?ChannelUrl=tgyq> 找不到官方的参考文献示例了。

1. 引注中的符号一般跟这句话的语境搭配。比如用中文写作时，“（杨开道，2015）”应该跟中文保持一致使用全角符号。你是要用英文写作吗？
2. 中文文献需要在 language 字段填写 `zh` 或者 `zh-CN`，不是 `中文;`。
3. 已经修改，见 <https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/232c42f83856d608b3478ef2e09f9c67f315c6a3/209sociological-studies.csl>。

**Comment by balalery** [comment]
收到，一直没有能回复您。此期刊的网站如下：http://shxyj.ajcass.org/Home/channel?ChannelUrl=tgyq。可惜并无参考文献格式要求。但是，我们可以通过文献来推理它的参考格式，最新的一篇文献，我放在了附件里。
引注确实需要和话语的语境搭配。但是此期刊好像默认都是英文括号，您可以看看我发的文献，是半角符号。劳烦您据此更新一下参考文献格式。
中文文献我试着更改一下language字段，谢谢您。
[为中国式现代化服务：社会学学科建设40年.pdf](https://github.com/zotero-cn/styles/files/11406781/40.pdf)

**Comment by balalery** [comment]
关于language字段的问题，我确实填写的是zh，但是不知道为何还是无法实现中文格式的参考文献，该样式用了英文格式处理我的中文图书。请您参考一下附件中的图片。辛苦您了
![image](https://user-images.githubusercontent.com/92866440/236477702-0169e64b-c76d-4f3e-8728-1292fb8dbd72.png)
![image](https://user-images.githubusercontent.com/92866440/236477855-719feffd-dbaf-4032-b429-3f7a539cbd72.png)

**Comment by balalery** [comment]
我刚刚测试了一下，发现当language字段修改为zh-cmn-Hans时，中文图书可以用中文格式的参考文献了，但是这样还是不方面，如果可以的话，请您修改一下样式，但language字段为zh时，也能用中文格式的参考文献。辛苦您了

**Comment by zepinglee** [comment]
> 收到，一直没有能回复您。此期刊的网站如下：<http://shxyj.ajcass.org/Home/channel?ChannelUrl=tgyq>。可惜并无参考文献格式要求。但是，我们可以通过文献来推理它的参考格式，最新的一篇文献，我放在了附件里。(http://shxyj.ajcass.org/Home/channel?ChannelUrl=tgyq>可惜并无参考文献格式要求。但是，我们可以通过文献来推理它的参考格式，最新的一篇文献，我放在了附件里。) 引注确实需要和话语的语境搭配。但是此期刊好像默认都是英文括号，您可以看看我发的文献，是半角符号。劳烦您据此更新一下参考文献格式。 中文文献我试着更改一下language字段，谢谢您。 [为中国式现代化服务：社会学学科建设40年.pdf](https://github.com/zotero-cn/styles/files/11406781/40.pdf)

这种符号排版风格是开明式（句末标点全宽，句内标点半宽）。中文文献都是用的中文符号，没理由用西文符号。

**Comment by balalery** [comment]
您好！邮件已收到，祝您生活愉快！

**Comment by zepinglee** [comment]
> 关于language字段的问题，我确实填写的是zh，但是不知道为何还是无法实现中文格式的参考文献，该样式用了英文格式处理我的中文图书。请您参考一下附件中的图片。辛苦您了 

将文献导出为 CSL-JSON 贴上来，参考 [Chinese-STD-GB-T-7714-related-csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl) 的 issue 模板 <https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/issues/new?assignees=&labels=&template=bug_report.md&title=>。

**Comment by balalery** [comment]
修改《社会学研究》的样式

CSL 样式：sociological-studies.csl

关于language字段的问题，我确实填写的是zh，但是不知道为何还是无法实现中文格式的参考文献，该样式用了英文格式处理我的中文图书。请您参考一下附件中的图片。辛苦您

**条目信息**


1. 中文文献条目出错
（1）当论文language为zh时
```json
[
    {
        "id": "xiachuanlingYinguochanraodeerjieshehuiyinguoluzhibian2021a",
        "type": "article-newspaper",
        "container-title": "中国社会科学报",
        "language": "zh",
        "note": "DOI: 10.28131/n.cnki.ncshk.2021.004115\npublisher: 中国社会科学报",
        "page": "010",
        "source": "CNKI",
        "title": "因果缠绕的二阶社会因果律之辨",
        "URL": "https://kns.cnki.net/KCMS/detail/detail.aspx?dbcode=CCND&dbname=CCNDLAST2022&filename=CSHK202111100100&v=",
        "author": [
            {
                "literal": "夏传玲"
            }
        ],
        "accessed": {
            "date-parts": [
                [
                    "2023",
                    5,
                    6
                ]
            ]
        },
        "issued": {
            "date-parts": [
                [
                    "2021",
                    11,
                    10
                ]
            ]
        }
    }
]
```
![image](https://user-images.githubusercontent.com/92866440/236628615-a9df98d8-cf26-46d3-bbd3-0be642a37bca.png)
（2）当论文language为zh-cmn时
```json
[
    {
        "id": "xiachuanlingYinguochanraodeerjieshehuiyinguoluzhibian2021a",
        "type": "article-newspaper",
        "container-title": "中国社会科学报",
        "language": "zh-cmn",
        "note": "DOI: 10.28131/n.cnki.ncshk.2021.004115\npublisher: 中国社会科学报",
        "page": "010",
        "source": "CNKI",
        "title": "因果缠绕的二阶社会因果律之辨",
        "URL": "https://kns.cnki.net/KCMS/detail/detail.aspx?dbcode=CCND&dbname=CCNDLAST2022&filename=CSHK202111100100&v=",
        "author": [
            {
                "literal": "夏传玲"
            }
        ],
        "accessed": {
            "date-parts": [
                [
                    "2023",
                    5,
                    6
                ]
            ]
        },
        "issued": {
            "date-parts": [
                [
                    "2021",
                    11,
                    10
                ]
            ]
        }
    }
]
```
![image](https://user-images.githubusercontent.com/92866440/236628780-935592bc-ac21-4b54-a05c-e1057e4b4b9b.png)
图书不再测试，与论文遇到的问题一样。都是当language字段修改为zh-cmn-Hans或zh-cmn时，中文论文和图书可以用中文格式的参考文献，而为zh时则不行。但是这样还是不方便，如果可以的话，请您修改一下样式，但language字段为zh时，也能用中文格式的参考文献。辛苦您了
另外，附《社会学研究》参考文献格式，您可以据此做出修改，辛苦您了
[社会学研究 参考文献格式.pdf](https://github.com/zotero-cn/styles/files/11412519/default.pdf)

**Comment by zepinglee** [comment]
我无法复现你的问题。

见 CSL-data <https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/d843338da19058718fb5d1088202c5533d9fb992/tests/styles/209sociological-studies/test-data.json#L1-L69> 以及输出 <https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/d843338da19058718fb5d1088202c5533d9fb992/tests/styles/209sociological-studies/test.md?plain=1#L57-L58>。

`language` 无论填写 `zh` 或者 `zh-cmn` 都是中文符号。

**Comment by zepinglee** [comment]
> 另外，附《社会学研究》参考文献格式，您可以据此做出修改，辛苦您了 [社会学研究 参考文献格式.pdf](https://github.com/zotero-cn/styles/files/11412519/default.pdf)

这份文档第 16 页 21 条：

> 21.注意文内标点符号除文末参考文献里的英文文献部分用英文标点，其他部分一律用中文标点。

所以中文文献的逗号也应该使用中文标点。

**Comment by balalery** [comment]
好的，以上收到，辛苦您了。可能这是我个人的问题，唉，那我以后把中文文献手动修改为zh-cmn吧，辛苦您了。此外，您的格式没有什么问题，谢谢您，是我理解出现了问题。

**Comment by zepinglee** [comment]
> 好的，以上收到，辛苦您了。可能这是我个人的问题，唉，那我以后把中文文献手动修改为zh-cmn吧，辛苦您了。此外，您的格式没有什么问题，谢谢您，是我理解出现了问题。

可能是 zotero 的 word 插件配置有误，建议检查一下设置。另外可以尝试刷新，或者重新配置参考文献。

不建议改成 `zh-cmn`，按照 [Zotero 的要求](https://www.zotero.org/support/kb/item_types_and_fields#general_fields) language 字段应该填写 `zh-CN`（“two letter [ISO language codes](http://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) followed by two letter [ISO country codes](http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)”）。

**Comment by balalery** [comment]
收到，非常感谢









      发自我的企业微信         

 
 
 ----------回复的邮件信息----------
 Zeping ***@***.***&gt; 于2023年5月6日(周六) 晚上11:37写道:

  

  
好的，以上收到，辛苦您了。可能这是我个人的问题，唉，那我以后把中文文献手动修改为zh-cmn吧，辛苦您了。此外，您的格式没有什么问题，谢谢您，是我理解出现了问题。
  
可能是 zotero 的 word 插件配置有误，建议检查一下设置。另外可以尝试刷新，或者重新配置参考文献。
 
不建议改成 zh-cmn，按照 Zotero 的要求 language 字段应该填写 zh-CN（“two letter ISO language codes followed by two letter ISO country codes”）。
