### ISSUE TITLE
为什么我的参考文献超过三个作者部分不显示“等”或者“et al”

### ISSUE THREAD

**Issue by AmyGreennn** [zotero-chinese/styles#21]
为什么我的参考文献超过三个作者部分不显示“等”或者“et al”

**Comment by northword** [comment]
更换style

**Comment by AmyGreennn** [comment]
我也找了好几个了，包括这个，我看网上挺多人说可以，结果我还是不行。你有推荐的style吗



---Original---
From: ***@***.***&gt;
Sent at: 2023年11月24日(Fri) AM7:54
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [zotero-chinese/styles] 为什么我的参考文献超过三个作者部分不显示“等”或者“et al” (Issue #21)




 
更换style

**Comment by northword** [comment]
你用的哪个？样式名截个图呢

**Comment by northword** [comment]
https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl?tab=readme-ov-file#%E9%83%A8%E5%88%86csl%E6%98%BE%E7%A4%BA%E6%95%88%E6%9E%9C

这里面的你看看合适的

**Comment by zepinglee** [comment]
1. 用了具体哪个样式？
2. 将出错的文献导出的 CSL-JSON 格式贴上来。
