### ISSUE TITLE
您好我想请问一下中国工业经济格式的一个问题

### ISSUE THREAD

**Issue by yangtaifeng** [zotero-chinese/styles#22]
我想将中国工业经济格式英文调为英文在前，需要怎么设置呢。期待您的回复，我的邮箱是ytf123ytf123@163.com

**Comment by zepinglee** [comment]
1. 确保 `language` 字段填写了 `en-US` 或者 `zh-CN`。
2. 在 `bibliography > sort` 中添加 `<key variable="language">`。

```xml
  <bibliography entry-spacing="0" second-field-align="flush">
    <sort>
      <key variable="language"/>
      <key macro="author-zh"/>
      <key macro="issued-year"/>
    </sort>
    ...
  </bibliography>
```

建议使用 <https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/208chinas-industrial-economics.csl>，其中可能有更新。
