### ISSUE TITLE
您好！我下载了法学引注手册的Zotero的CSL，安装之后，插入引文出现了格式问题，我想请您看看如何解决。

### ISSUE THREAD

**Issue by minikinminilin** [zotero-chinese/styles#23]
<img width="830" alt="截屏2024-02-02 20 56 01" src="https://github.com/zotero-chinese/styles/assets/153914620/5cc1711c-9502-42d1-a9c5-ac2eb48f5efd">
<img width="830" alt="截屏2024-02-02 20 56 14" src="https://github.com/zotero-chinese/styles/assets/153914620/471af86a-32e5-4b3d-b64e-89221a6751bb">
<img width="326" alt="截屏2024-02-02 20 56 38" src="https://github.com/zotero-chinese/styles/assets/153914620/1b2b04b9-91d8-4990-88ad-11ecc58001a9">
问题就如图片上所显示的，调整文献的语言也无法更正脚注的格式，请问这种情况我要如何解决？

**Comment by northword** [comment]
你好，请从 https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl 仓库安装最新版本的样式文件，然后看看有没有问题出现，如果仍有问题，向上面的仓库反馈，当前仓库暂时没有在积极维护 CSL 文件本身。

**Comment by zepinglee** [comment]
第二张图是怎么产生的？

[301manual-of-legal-citation-multi-lingual.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/301manual-of-legal-citation-multi-lingual.csl) 样式设置了默认语言为英文，应该不能选择“中文”。所以你的样式是从哪里下载的？能不能传一份上来（需要打包成 zip 格式）？

**Comment by zepinglee** [comment]
> 你好，请从 https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl 仓库安装最新版本的样式文件，然后看看有没有问题出现，如果仍有问题，向上面的仓库反馈，当前仓库暂时没有在积极维护 CSL 文件本身。

我才发现原来是这个仓库。

**Comment by northword** [comment]
> 我才发现原来是这个仓库。

哈哈，因为你把所有的仓库都 watch 了；我觉得多个仓库不太好维护的话，这个仓库后面可以把 csl 移出，然后把 csl 仓库以子模块之类的形式放到这个仓库，这个仓库只生成预览网页，网页里可以提供多个镜像地址  这样的形式。

然后这个仓库定时更新，或 csl 仓库加个 onpush action ，触发这个仓库的更新（只是一个设想）。

**Comment by minikinminilin** [comment]
问题解决啦，谢谢你们！！！🌹🌹🌹🌹🌹

**Comment by zepinglee** [comment]
> > 我才发现原来是这个仓库。
> 
> 哈哈，因为你把所有的仓库都 watch 了；我觉得多个仓库不太好维护的话，这个仓库后面可以把 csl 移出，然后把 csl 仓库以子模块之类的形式放到这个仓库，这个仓库只生成预览网页，网页里可以提供多个镜像地址 这样的形式。
> 
> 然后这个仓库定时更新，或 csl 仓库加个 onpush action ，触发这个仓库的更新（只是一个设想）。

最好是把原来的仓库 transfer 过来。

**Comment by zepinglee** [comment]
另外图 2 中的“笔记”翻译错了，应该是“注释”。

@minikinminilin 另外插入 citation 时建议使用 Zotero 的 Word 插件，不要使用“Create bibliography from item”的方法。后者缺少像 Ibid. 这样的特性。

**Comment by minikinminilin** [comment]
好的，谢谢帮忙！怪不得我感觉这个笔记放在这里有点突兀。

发件人: Zeping Lee ***@***.***>
日期: 星期六, 2024年2月3日 17:44
收件人: zotero-chinese/styles ***@***.***>
抄送: minikinminilin ***@***.***>, Mention ***@***.***>
主题: Re: [zotero-chinese/styles] 您好！我下载了法学引注手册的Zotero的CSL，安装之后，插入引文出现了格式问题，我想请您看看如何解决。 (Issue #23)

另外图 2 中的“笔记”翻译错了，应该是“注释”。

@minikinminilin<https://github.com/minikinminilin> 另外插入 citation 时建议使用 Zotero 的 Word 插件，不要使用“Create bibliography from item”的方法。后者缺少像 Ibid. 这样的特性。

―
