### ISSUE TITLE
gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi英文的et.al问题

### ISSUE THREAD

**Issue by shahwaiz-git** [zotero-chinese/styles#26]
gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi引用英文文献时，部分本该出现‘’et.al.‘’的地方会变为‘’等‘’
如图
![1710920938982](https://github.com/zotero-chinese/styles/assets/75054015/535a7465-c6bb-4fe3-bcbc-06eca2e9cb09)

**Comment by northword** [comment]
https://zotero-chinese.com/user-guide/faqs/word-addon.html#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9%E5%8F%8A%E4%B8%8E%E6%A0%B7%E5%BC%8F%E7%9B%B8%E5%85%B3%E7%9A%84%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98
