### ISSUE TITLE
申请添加华南农业大学（研究生）版

### ISSUE THREAD

**Issue by YUKITOfoxx** [zotero-chinese/styles#260]
**样式信息**

- 期刊/学校名称：华南农业大学研究生学位论文

- 英文名称： South China Agriculture University

- 参考文献格式：与465华南农业大学本科生学位论文的区别在
<img width="785" alt="截屏2024-02-14 20 28 47" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/115545817/690d67f3-4060-4255-821a-caa8bc9a1b88">
即正文中无论是外国作者还是中国作者统一使用中文括号、分号和逗号

Zotero ID:

**其他样式信息**

**Comment by YUKITOfoxx** [comment]
您好，徐宇佳已经收到啦，我将尽快给您答复。

**Comment by zepinglee** [comment]
@YUKITOfoxx 有没有格式要求的官方链接？

> 您好，徐宇佳已经收到啦，我将尽快给您答复。

非假期不要开自动回复。

**Comment by YUKITOfoxx** [comment]
好的，老师，不好意思，确认是中文的。

**Comment by YUKITOfoxx** [comment]
https://yjsy.scau.edu.cn/286/list.htm

不知道老师们是否能进入这个网址 位于【学位科】第二行
[学位办公室] | 华南农业大学研究生学位论文写作指南（2019年12月） | 2023-03-01
[[学位办公室](https://yjsy.scau.edu.cn/286/list.htm)]	[华南农业大学研究生学位论文写作指南（2019年12月）](https://yjsy.scau.edu.cn/_upload/article/files/8f/60/ad6c68bc4c8181e8fa46982ced10/1d8619e0-908f-4a3b-bbef-5b772ca1c6ba.docx)	2023-03-01

然后上面的要求是在该文档第六页

**Comment by zepinglee** [comment]
在 71c74d5 中添加。

> https://yjsy.scau.edu.cn/286/list.htm
> 
> 不知道老师们是否能进入这个网址 

可以。我们需要记录这些信息，以后如果格式要求有变化可以方便我们参考。

**Comment by YUKITOfoxx** [comment]
谢谢老师，更新之后发现出现了一个小问题，就是三人以上的文献在正文引用中“人名”和“等”中间出现了空格，如图
<img width="154" alt="截屏2024-02-15 12 04 19" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/115545817/0ebcf0c0-b35f-400f-9655-53b5e9e3e300">
<img width="186" alt="截屏2024-02-15 12 07 06" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/115545817/e3a35238-3e9a-4e58-aba6-c1d3f03625f3">
再次感谢老师们。

**Comment by zepinglee** [comment]
> 更新之后发现出现了一个小问题，就是三人以上的文献在正文引用中“人名”和“等”中间出现了空格

GB/T 7714—2005 文后参考文献著录规则

<img width="871" alt="Screenshot 2024-02-15 at 12 21 01" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/af98895a-719b-49df-8401-8dc8d84e12e5">

**Comment by YUKITOfoxx** [comment]
好的，不好意思老师，谢谢老师们。
