### ISSUE TITLE
申请《教育史研究》样式

### ISSUE THREAD

**Issue by Ben-Tirion** [zotero-chinese/styles#304]
**样式信息**

- 期刊/学校名称：[教育史研究]

- 英文名称：[Educational History Studies]

- 参考文献格式：[例如 <https://kns.cnki.net/kcms2/article/abstract?v=_6cC4UgRj8SZnR0wjCgZrkd1CSjRUMDPAve5VrT6l1yN_ahexZEFufMb4ag-lh_hT_nTXOMeYH1Txq19UR9tJHTukdewBpd5Wtb8ImtIb6DleoEh15YWxqkzCy1ss6c3&uniplatform=NZKPT>]

- 参考文献格式的更新日期：[例如 2020-07-30]

- （学校）文件号：

- （期刊）ISSN 号：[2096-6660]

- （期刊）相关领域：[history, social science]

**测试条目**

Zotero ID:BenTirion

**其他样式信息**

**Comment by redleafnew** [comment]
这是官方的投稿网址，感觉像是第三方的。
另外看看与仓库中哪个更接近。

**Comment by Ben-Tirion** [comment]
> 这是官方的投稿网址，感觉像是第三方的。 另外看看与仓库中哪个更接近。

是的，已修改成知网上官方的征稿启事pdf

**Comment by redleafnew** [comment]
这个样式与仓库中有没有接近的，方便修改。另外将里面提到的参考文献JSON格式上传上来。

**Comment by zepinglee** [comment]
我无法获取知网的 PDF，最好传一份到 github 上。

**Comment by Ben-Tirion** [comment]
[《教育史研究》征稿启事.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/15195891/default.pdf)


> 我无法获取知网的 PDF，最好传一份到 github 上。

**Comment by zepinglee** [comment]
在 1ac3216 中添加。测试效果见 <https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/tests/styles/325educational-history-studies/test.md>。

**Comment by Ben-Tirion** [comment]
> 在 [1ac3216](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/commit/1ac3216a39110f2a53c03b801358e399882bffcc) 中添加。测试效果见 https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/tests/styles/325educational-history-studies/test.md。

感谢贡献，发现一点小问题。他要求在译著前加国别，如“［美］布鲁纳著，邵瑞珍、张渭城等译”

**Comment by zepinglee** [comment]
> 感谢贡献，发现一点小问题。他要求在译著前加国别，如“［美］布鲁纳著，邵瑞珍、张渭城等译”

国籍只能手动添加到作者的姓名前。

https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/8647a10d595e2bf016e1e493a05254d1306bb8ec/tests/manual-of-legal-citation-data.json#L69-L73

https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/8647a10d595e2bf016e1e493a05254d1306bb8ec/tests/styles/325educational-history-studies/test.md?plain=1#L260
