### ISSUE TITLE
申请添加黑龙江大学本科毕业论文引文样式

### ISSUE THREAD

**Issue by chute8427** [zotero-chinese/styles#305]
**样式信息**

- 期刊/学校名称：[黑龙江大学]

- 英文名称：[Heilongjiang University]

- 参考文献格式：https://jsjrj.hlju.edu.cn/info/1975/1236.htm

[黑龙江大学本科生毕业论文（设计）撰写规范.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/15268925/default.pdf)

**测试条目**

Zotero ID:

**其他样式信息**

**Comment by zepinglee** [comment]
> 参考文献书写格式应符合GB7714－87《文后参考文献著录规则》。

其实后面的示例是按照 GB/T 7714—2005 的格式。

**Comment by zepinglee** [comment]
在 02a24be 中添加。测试效果见 <https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/tests/styles/487heilongjiang-university-undergraduate/README.md>。

**Comment by chute8427** [comment]
好的 谢谢 有问题会再来反馈 现在有两个地方很迷惑 查看往届论文 三个作者以上  张三, 李四, 王五, 等. 张三, 李四, 王五等. 都有写的。还有英文 etal.  et al. 同样也不统一。

**Comment by zepinglee** [comment]
> 好的 谢谢 有问题会再来反馈 现在有两个地方很迷惑 查看往届论文 三个作者以上 张三, 李四, 王五, 等. 张三, 李四, 王五等. 都有写的。还有英文 etal. et al. 同样也不统一。

你们的《撰写规范》要求：

> 主要责任者为多人时，一般只列出 3 名作者

“et al.”是两个拉丁文单词，没有“etal.”的用法。
