### ISSUE TITLE
申请添加武汉理工大学毕业论文格式

### ISSUE THREAD

**Issue by Jhyyy88** [zotero-chinese/styles#310]
- 期刊/学校名称：[武汉理工大学毕业论文]

- 英文名称：[Wuhan University of Technology]

- 参考文献格式：[例如 <http://jwc.whut.edu.cn/Web/Details?id=41&type=010205>]
附件：
[20160525115234_7523.pdf](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/15336047/20160525115234_7523.pdf)

**Comment by zepinglee** [comment]
在 002 基础上简单修改一下即可。我明天处理。

**Comment by Jhyyy88** [comment]
十分感谢大佬！

**Comment by zepinglee** [comment]
在 e3c7b5d 中添加。
