### ISSUE TITLE
申请添加西安电子科技大学本科毕业论文参考文献格式

### ISSUE THREAD

**Issue by Good-Dish** [zotero-chinese/styles#311]
- 期刊/学校名称：[西安电子科技大学毕业论文]
- 
- 参考文献格式：https://see.xidian.edu.cn/html/news/2703.html
- 
- （1）专著类的文献：
[序号]  作者 . 专著名称.  版本. 出版地：出版者，出版年. 参考的页码。
（2）期刊类的文献：
[序号]  作者 . 文献名. 期刊名称.  年 , 月,  卷（期）. 页码。
其中作者采用姓在前、名在后的形式。当作者超过三个时，只著录前三个人，其后
加“等”字即可。

**Comment by zepinglee** [comment]
在 6d6ec64 中添加。

为了避免歧义，期刊文章不显示月份。
