### ISSUE TITLE
华中科技大学理工科模板中，数字之间的连字符不一致

### ISSUE THREAD

**Issue by narutozxp** [zotero-chinese/styles#316]
**描述错误**

CSL 样式：[huazhong-university-of-science-and-technology.csl](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/main/418huazhong-university-of-science-and-technology.csl)

该模板的显示效果如下:
>[1]	S. Yamaki, M. Abet, M. Kawamata, M. Yoshizawa. Performance Evaluation of Phase-Only Correlation Functions from the Viewpoint of Correlation Filters, in: 2018 Asia-Pacific Signal and Information Processing Association Annual Summit and Conference (APSIPA ASC), Honolulu, HI, USA, 12–15 Nov. 2018, IEEE, 2018: 1361-1364

会议日期中,两个数字之间的连接符使用的是en-dash（12–15）（unicode U+2013），而页数之间的连接符使用的是hyphen（1361-1364）(unicode U+002d)。这两个应该使用同样的符号（en-dash）。

**Comment by zepinglee** [comment]
我之前的理解是，页码范围使用 hyphen 是特殊规定，毕竟列出了“起页-止页”。日期还是使用英文习惯的 en dash。

<img width="761" alt="Screenshot 2024-06-03 at 21 41 46" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/22018a6e-fa35-4576-a44e-cc2020771322">

统一使用 hyphen 也没问题。

**Comment by zepinglee** [comment]
在 890e2c7 中修改。

**Comment by narutozxp** [comment]
> 我之前的理解是，页码范围使用 hyphen 是特殊规定，毕竟列出了“起页-止页”。日期还是使用英文习惯的 en dash。
> 
> <img alt="Screenshot 2024-06-03 at 21 41 46" width="761" src="https://private-user-images.githubusercontent.com/12290822/336095843-22018a6e-fa35-4576-a44e-cc2020771322.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0OTE5ODUsIm5iZiI6MTcxNzQ5MTY4NSwicGF0aCI6Ii8xMjI5MDgyMi8zMzYwOTU4NDMtMjIwMThhNmUtZmEzNS00NTc2LWE0NGUtY2MyMDIwNzcxMzIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDA5MDEyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmZmQ2YmZkOWFiZWM1NTMzMjU3MTYzOTMyYTA3Yjg4ODA3ZTU5YjM1NWU0NDRkODI3ZmI3ZGQ2NDE2M2NlOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bzKo4JlwdXJ8SmXF1o6JRxuNLslBs8upxidot8ZUcDA">
> 统一使用 hyphen 也没问题。

模板里面确实是这么写的，但是华科的模板真的很奇怪，有些地方，他的说明与给的示例并不相符。就比如官方模板中的参考文献示例当中的第五条，官方模板的示例就与其描述不一致。

而至于页码之间的连字符，latex中基本都使用`--`，ACM的bibtex使用的也是en-dash，因此我怀疑是模板的问题。

而且连字符不一致，有点影响美观，要么都用hyphen,要么都用en dash

**Comment by zepinglee** [comment]
> 就比如官方模板中的参考文献示例当中的第五条，官方模板的示例就与其描述不一致。

哪里不一致？我好像没注意到

> 而至于页码之间的连字符，latex中基本都使用`--`，ACM的bibtex使用的也是en-dash，因此我怀疑是模板的问题。

APA, Chicago, IEEE 等美国主流体例使用 en dash，然而也有像 Vancouver （<https://www.nlm.nih.gov/bsd/uniform_requirements.html>）这样使用 hyphen 的。

**Comment by narutozxp** [comment]
> > 就比如官方模板中的参考文献示例当中的第五条，官方模板的示例就与其描述不一致。
> 
> 哪里不一致？我好像没注意到
> 
> > 而至于页码之间的连字符，latex中基本都使用`--`，ACM的bibtex使用的也是en-dash，因此我怀疑是模板的问题。
> 
> 嗯，APA, Chicago, IEEE 等美国主流体例使用 en dash，然而也有像 Vancouver （https://www.nlm.nih.gov/bsd/uniform_requirements.html）这样使用 hyphen 的。
模板中的名字缩写是这样的
> Y. Shunsuke, A. Masahide, K. Masayuki, M. Yoshizawa

但是实际应该是名在前（缩写），姓在后
>S. Yamaki, M. Abet, M. Kawamata, M. Yoshizawa.

**Comment by zepinglee** [comment]
> > Y. Shunsuke, A. Masahide, K. Masayuki, M. Yoshizawa
> 
> 但是实际应该是名在前（缩写），姓在后
> 
> > S. Yamaki, M. Abet, M. Kawamata, M. Yoshizawa.

哈，这个是把姓和名搞反了。
