### ISSUE TITLE
科学学与科学技术管理 样式

### ISSUE THREAD

**Issue by fredericky123** [zotero-chinese/styles#319]
**样式信息**

- 期刊/学校名称：
科学学与科学技术管理
- 英文名称：
SCIENCE OF SCIENCE AND MANAGEMENT OF S.&.T
- 参考文献格式：

https://www.ssstm.org/CN/1002-0241/home.shtml
<img width="855" alt="image" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/13982749/e6601166-0e60-461c-a770-780eea0fc73e">

- （期刊）相关领域：

**测试条目**

Zotero ID:

**其他样式信息**

可参考119studies-in-science-of-science.csl
在119的基础上，
1.取消编号
2.将中文参考文献的翻译样式调整为（）包住，并另起一段

**Comment by zepinglee** [comment]
119 的格式中，出版年的位置跟这个也不一样。

另外[投稿指南](https://www.ssstm.org/CN/column/column6.shtml)和[《科学学与科学技术管理》出版格式修改须知](https://www.ssstm.org/fileup/1002-0241/ITEM/20191011163921.doc)似乎都没提到中英文双语著录。这个截图的内容出自哪里？

**Comment by fredericky123** [comment]
感谢感谢，截图出自从知网下载的发表的期刊文章，这个投稿指南应该有些落后，大家投稿的时候也按发表时的格式来的

**Comment by zepinglee** [comment]
在 b099a24 中添加。

其中英文翻译的缩进只能调整为下面的样子，需要手动编辑一下。

<img width="623" alt="Screenshot 2024-06-10 at 09 21 33" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/726a6dc9-fbfe-42ec-8642-918b09d39ae3">

**Comment by fredericky123** [comment]
感谢感谢！
