### ISSUE TITLE
《中国社会科学》目前注意到的几个问题

### ISSUE THREAD

**Issue by ggmtb** [zotero-chinese/styles#320]
CSL 样式：311social-sciences-in-china.csl

- 第一个是重复文献页下注二次引用时，作者后面是冒号而不是逗号。
- 第二个是论文标题中有双引号的，在页下注中，双引号会显示为半角标点的双引号而不是全角双引号。
- 第三个是论文页码有拆分的，补充的页码表现为空格+半角逗号+页码。实际应为全角逗号+页码。<img width="1065" alt="截圖 2024-06-11 03 01 35" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/55423832/d83cf4ac-6509-4bb2-ace4-d30bcf1e40f9">

**Comment by zepinglee** [comment]
> * 第一个是重复文献页下注二次引用时，作者后面是冒号而不是逗号。

在 6860b38 中修正。以下是测试结果。

https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/6860b3870b47edb1367ee264d75d64c03ab78aae/tests/styles/311social-sciences-in-china/test.md?plain=1#L9-L16

另外官方《关于引文注释的规定》的示例只包括了图书和文集析出文献。那么期刊文献是否需要标注刊名呢？

> * 第二个是论文标题中有双引号的，在页下注中，双引号会显示为半角标点的双引号而不是全角双引号。

Unicode 中弯引号「“」、「”」在编码上不能区分半角和全角，这两个字符使用中文字体时显示为全角，使用西文字体时显示为半角。所以这个问题无法在 CSL 这里处理，只能在 Word 中手动设置引号的字体。不知道在 Word 中能否使用宏进行统一处理。

> * 第三个是论文页码有拆分的，补充的页码表现为空格+半角逗号+页码。实际应为全角逗号+页码。

这里的逗号是在 citeproc 引擎中处理的，无法在 CSL 样式中设置。只能手动修改，或者在页码中使用全角标点填写完整的“第62—67，75页”。

**Comment by ggmtb** [comment]
二次引证期刊，不需要加期刊名，标注文章名和页码就行

**Comment by ggmtb** [comment]
> > * 第一个是重复文献页下注二次引用时，作者后面是冒号而不是逗号。
> 
> 在 [6860b38](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/commit/6860b3870b47edb1367ee264d75d64c03ab78aae) 中修正。以下是测试结果。
> 
> https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/6860b3870b47edb1367ee264d75d64c03ab78aae/tests/styles/311social-sciences-in-china/test.md?plain=1#L9-L16
> 
> 另外官方《关于引文注释的规定》的示例只包括了图书和文集析出文献。那么期刊文献是否需要标注刊名呢？
> 
> > * 第二个是论文标题中有双引号的，在页下注中，双引号会显示为半角标点的双引号而不是全角双引号。
> 
> Unicode 中弯引号「“」、「”」在编码上不能区分半角和全角，这两个字符使用中文字体时显示为全角，使用西文字体时显示为半角。所以这个问题无法在 CSL 这里处理，只能在 Word 中手动设置引号的字体。不知道在 Word 中能否使用宏进行统一处理。
> 
> > * 第三个是论文页码有拆分的，补充的页码表现为空格+半角逗号+页码。实际应为全角逗号+页码。
> 
> 这里的逗号是在 citeproc 引擎中处理的，无法在 CSL 样式中设置。只能手动修改，或者在页码中使用全角标点填写完整的“第62—67，75页”。

二次引证期刊，不需要加期刊名，标注文章名和页码就行

**Comment by zepinglee** [comment]
> 二次引证期刊，不需要加期刊名，标注文章名和页码就行

OK，那就不需要修改了。

**Comment by zepinglee** [comment]
关于《中国社会科学》的页码问题（<https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/issues/321#issuecomment-2161211829>）还是回到这个 issue 继续讨论吧。

> > 另外《中国社会科学》发现一个问题，重复引用文献的时候，缺失页码信息。
> 
> 这里的“页码”有两种不同含义，一是析出页码，比如某期刊文章整体位于某卷的 9—16 页；二是引用页码，即引用文献特定部分的内容所处的页码，在 CSL 中称为 locator，比如引用该文章的某段话出自其中第 12 页。按照国外注释体例（比如 Chicago）的习惯，重复引用时会标出引用页码，但不标析出页码。

我发现《关于引文注释的规定》中期刊文章是不标页码的。

<img width="787" alt="Screenshot 2024-06-12 at 07 14 07" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/f0458227-50ef-4d8f-af53-864fce8c9873">

比如第一篇示例文献《读顾诚〈南明史〉》，按照[知网页面](https://kns.cnki.net/kcms2/article/abstract?v=wYgW8A8u9vrOtYYsUyD3a3HGR6_0gC2-OjfssLZ29tuRDobrlApzyzapSoP2lf5NpWpkDS38vvIX7M5GFEsV23kDKGQ4AGfUjWiHLx1sts060x4bmhz89AGEYbOPNE9_SsxLVjObd8s=&uniplatform=NZKPT&language=CHS)该文章的析出页码是 167—173，按照规定首次引用不需要标出这个页码的（目前的 CSL 样式会标出，需要修改）。但如果首次引用第 168 页的特定内容，需要标出“第 168 页”吗？我个人的理解是需要的。如果是重复引用该文献整体，我的理解是作为省略版更没有必要标出“第 167—173 页”。但重复引用第 168 页的特定内容，应当标出该页码：“何龄修:《读顾诚〈南明史〉》，第 168 页。”

另外询问一下 @EdwardSaidZhou 的意见。

备注：《法学引注手册》也有类似的问题。

**Comment by EdwardSaidZhou** [comment]
按照我个人的理解，以下这段话应当如此：如果是重复引用该文献整体，我的理解是作为省略版更没有必要标出“第 167—173 页”。但重复引用第 168 页的特定内容，应当标出该页码：“何龄修:《读顾诚〈南明史〉》，第 168 页。

**Comment by zepinglee** [comment]
> 按照我个人的理解，以下这段话应当如此：如果是重复引用该文献整体，我的理解是作为省略版更没有必要标出“第 167—173 页”。但重复引用第 168 页的特定内容，应当标出该页码：“何龄修:《读顾诚〈南明史〉》，第 168 页。

@EdwardSaidZhou 嗯，跟我的理解一致。

如果是首次引用特定内容呢？

**Comment by zepinglee** [comment]
《中国社会科学》的页码已在 [397e4d7](https://github.com/zotero-chinese/styles/commit/397e4d7fad288abb431a61d044994ef1f5818956) 中修改。
