### ISSUE TITLE
历史研究格式的错误

### ISSUE THREAD

**Issue by ggmtb** [zotero-chinese/styles#321]
**描述错误**

CSL 样式：~308world-history.csl~historical-research.csl

《历史研究》作者后面应接冒号，目前的格式中作者与论文名称中间无标点符号。
期刊论文的页码字体显示为Times New Roman，专著类页码字体是宋体。
专著的出版地点与出版社中间的冒号显示为冒号+空格符，应显示为全角空格符号
期刊期数和页码中间显示为逗号+空格符，应显示为全角逗号

<img width="1049" alt="截圖 2024-06-11 13 03 23" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/55423832/d78c71ea-35a6-4ef6-8f2e-334ac1f92343">

**Comment by zepinglee** [comment]
> CSL 样式：308world-history.csl 《历史研究》

`308world-history.csl` 是《世界历史》的样式，不是《历史研究》。确认没弄错吧？

> 作者后面应接冒号，目前的格式中作者与论文名称中间无标点符号。 

确实，不知道是不是《世界历史》体例改了。

> 期刊论文的页码字体显示为Times New Roman，专著类页码字体是宋体。 

我无法复现这个问题。另外 CSL 样式中无法设置具体的字体，只能控制粗体、斜体等。这个问题应该是在 Word 中设置。

> 专著的出版地点与出版社中间的冒号显示为冒号+空格符，应显示为全角空格符号

308 样式不显示出版地，按理不应出现出版地。建议将出现问题的文献导出为 CSL-JSON 格式，并将其中的内容贴上来方便具体讨论。

> 期刊期数和页码中间显示为逗号+空格符，应显示为全角逗号

无法复现词问题，同样需要将导出的 CSL-JSON 贴上来。

**Comment by ggmtb** [comment]
> > CSL 样式：308world-history.csl 《历史研究》
> 
> `308world-history.csl` 是《世界历史》的样式，不是《历史研究》。确认没弄错吧？
> 
> > 作者后面应接冒号，目前的格式中作者与论文名称中间无标点符号。
> 
> 确实，不知道是不是《世界历史》体例改了。
> 
> > 期刊论文的页码字体显示为Times New Roman，专著类页码字体是宋体。
> 
> 我无法复现这个问题。另外 CSL 样式中无法设置具体的字体，只能控制粗体、斜体等。这个问题应该是在 Word 中设置。
> 
> > 专著的出版地点与出版社中间的冒号显示为冒号+空格符，应显示为全角空格符号
> 
> 308 样式不显示出版地，按理不应出现出版地。建议将出现问题的文献导出为 CSL-JSON 格式，并将其中的内容贴上来方便具体讨论。
> 
> > 期刊期数和页码中间显示为逗号+空格符，应显示为全角逗号
> 
> 无法复现此问题，同样需要将导出的 CSL-JSON 贴上来。

哦哦哦看走眼了是302historical-research 历史研究

**Comment by zepinglee** [comment]
> 哦哦哦看走眼了是302historical-research 历史研究

嗯这里标记为“半成品”，确实可能有格式问题。

https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/8fc262cd927c01ee5db5357e9d0aec2bc6a79e7f/302historical-research.csl#L3

有官方的格式规范吗？我打算完善一下，但是没有找到该刊的官网。CSL 样式中记录的官网已经无法访问了。

https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/blob/8fc262cd927c01ee5db5357e9d0aec2bc6a79e7f/302historical-research.csl#L10

**Comment by zepinglee** [comment]
> [关于《历史研究》文献引证标注方式的规定.pdf](https://github.com/user-attachments/files/15788502/default.pdf) 
>
> 这个pdf文件有完整规定

这份是 2004 年的规定，一直用到现在吗？

另外这个格式粗略看起来跟《中国社会科学》差不多，有哪些差异吗？

**Comment by ggmtb** [comment]
> > [关于《历史研究》文献引证标注方式的规定.pdf](https://github.com/user-attachments/files/15788502/default.pdf)
> > 这个pdf文件有完整规定
> 
> 这份是 2004 年的规定，一直用到现在吗？
> 
> 另外这个格式粗略看起来跟《中国社会科学》差不多，有哪些差异吗？

对，历史研究格式一直没变过。期刊和专著论文引用格式一样，学位论文引用不一样。
另外《中国社会科学》发现一个问题，重复引用文献的时候，缺失页码信息。

**Comment by zepinglee** [comment]
> 对，历史研究格式一直没变过。期刊和专著论文引用格式一样，学位论文引用不一样。

我稍后完善一下。

> 另外《中国社会科学》发现一个问题，重复引用文献的时候，缺失页码信息。

这里的“页码”有两种不同含义，一是析出页码，比如某期刊文章整体位于某卷的 9—16 页；二是引用页码，即引用文献特定部分的内容所处的页码，在 CSL 中称为 locator，比如引用该文章的某段话出自其中第 12 页。按照国外注释体例（比如 Chicago）的习惯，重复引用时会标出引用页码，但不标析出页码。

**Comment by zepinglee** [comment]
关于《中国社会科学》的页码问题还是回到 <https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/issues/320#issuecomment-2161768074> 继续讨论吧。

**Comment by zepinglee** [comment]
284c6c9 中在《中国社会科学》的基础上重制了《历史研究》CSL 样式。

可以参考《中国社会科学》的测试文献进行校对。

https://github.com/zotero-chinese/styles/blob/284c6c9e85924b23198438d1427526d81dab6d40/src/historical-research/index.md?plain=1#L237-L290
