### ISSUE TITLE
错误：请问该如何引用电子资源

### ISSUE THREAD

**Issue by HsiehChakwai** [zotero-chinese/styles#323]
### 涉及到的样式文件

410shanghai-jiao-tong-university.csl

### 描述错误

1. 引用Zenodo文章时，item type不知道该选什么才能显示为[EB/OL]
2. 将item type选为blog post确实可以显示为[EB/OL]，但格式不符合GB7714-2015

> I Builuk. A new solver for rich Vehicle Routing Problem[EB/OL]//Zenodo.

### 条目信息

```json
[
	{
		"id": "builukNewSolverRich2023",
		"type": "post-weblog",
		"container-title": "Zenodo",
		"language": "en-US",
		"title": "A new solver for rich Vehicle Routing Problem",
		"URL": "https://doi.org/10.5281/zenodo.4624037",
		"author": [
			{
				"family": "Builuk",
				"given": "Ilya"
			}
		],
		"issued": {
			"date-parts": [
				[
					"2023"
				]
			]
		}
	}
]
```

**Comment by zepinglee** [comment]
你的这个案例使用 software 类型最合适，毕竟页面中是这么标注的。另外建议将 DOI 填写在 DOI 字段。

<img width="495" alt="Screenshot 2024-06-15 at 14 42 04" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/2baceee3-fa06-49a8-afa4-d4894d2568ae">

根据 <https://gk.sjtu.edu.cn/Data/View/648>，上交使用的是 GB/T 7714—2005 格式，该版本中不显示 DOI。另外根据该标准，文献类型标识应该使用“CP”而不是“EB”。

<img width="879" alt="Screenshot 2024-06-15 at 14 46 50" src="https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/assets/12290822/4d5e97a9-36f8-4f59-99e2-5620f64a3f3b">
