### ISSUE TITLE
错误：经济管理样式在同一处加入多个文献并列时出现错误

### ISSUE THREAD

**Issue by Ricardoxma** [zotero-chinese/styles#324]
### 涉及到的样式文件

经济管理.csl

### 描述错误

当该样式在同一处同时放入多篇不同文献时，文献与文献之间有括号相隔，例如：(中国互联网络信息中心, 2012)[7](Bawden, 2008)[8]
但在该期刊的论文中这种情况应该是将这些论文之间用分号相隔，只会用同一个括号将这一处并列的所有文献括起来，例如：
( Pei,2015[47] ;  褚剑和方军雄,2016[48] )

### 条目信息

```json
  {}
```

**Comment by Ricardoxma** [comment]
不好意思，还发现一个问题，这个样式在使用之后会有很多中文期刊在论文里面只显示作者的姓，没有全名。
比如这篇论文就只会显示赵&杨：
[
	{
		"id": "http://zotero.org/users/9337541/items/22CFSV4G",
		"type": "article-journal",
		"abstract": "数字经济时代，个人投资者借助技术赋能具备了一定程度的以“发声”方式参与公司治理的能力，但是这一新兴的治理要素究竟如何影响审计决策在理论上仍存在分歧。本文以网络互动平台上投资者提问作为散户积极主义的代理变量，利用2010-2017年沪深A股上市公司数据，从审计定价视角考察了审计师对散户积极主义的反应。分析结果表明，散户积极主义有助于降低审计风险，从而导致审计师降低审计收费，这一结论在一系列稳健性检验后依然成立。从作用机制看，散户积极主义主要通过缓解代理冲突、提高信息披露质量发挥作用。研究丰富了股东积极主义相关文献，对数字时代如何充分发挥各类股东的能动性，完善公司治理具有一定的启发。",
		"container-title": "审计研究",
		"ISSN": "1002-4239",
		"issue": "3",
		"language": "中文;",
		"note": "1 citations(CNKI)[2023-12-12]<>",
		"page": "80-91",
		"source": "CNKI",
		"title": "散户积极主义对审计决策的影响",
		"URL": "https://kns.cnki.net/kcms2/article/abstract?v=0kbmF0AymBCO6fSH5mih70BSx4K-U3tGC38nzwfYRFhiJ8wtaQDx4N8nPTZF5Xl1uHv1TYtbWaLSGvYow1Io5Le6bT6NcX4R1Q8yMw8iLRfLMgjMUH51UFMifsauWJh0&uniplatform=NZKPT&language=gb",
		"author": [
			{
				"family": "赵",
				"given": "杨"
			},
			{
				"family": "吕",
				"given": "文栋"
			}
		],
		"issued": {
			"date-parts": [
				[
					"2022"
				]
			]
		}
	}
]

**Comment by zepinglee** [comment]
> 但在该期刊的论文中这种情况应该是将这些论文之间用分号相隔，只会用同一个括号将这一处并列的所有文献括起来，例如：
> ( Pei,2015[47] ; 褚剑和方军雄,2016[48] )

CSL 的逻辑是，要么上标在括号外，要么在括号内，无法同时实现两者。

> 还发现一个问题，这个样式在使用之后会有很多中文期刊在论文里面只显示作者的姓，没有全名。
> 比如这篇论文就只会显示赵&杨：
>
> `"language": "中文;",`

`language` 字段应该填写 `zh-CN`，否则会按照该样式默认的英文格式处理姓名。

**Comment by Ricardoxma** [comment]
> > 但在该期刊的论文中这种情况应该是将这些论文之间用分号相隔，只会用同一个括号将这一处并列的所有文献括起来，例如：
> > ( Pei,2015[47] ; 褚剑和方军雄,2016[48] )
> 
> CSL 的逻辑是，要么上标在括号外，要么在括号内，无法同时实现两者。
> 
> > 还发现一个问题，这个样式在使用之后会有很多中文期刊在论文里面只显示作者的姓，没有全名。
> > 比如这篇论文就只会显示赵&杨：
> > `"language": "中文;",`
> 
> `language` 字段应该填写 `zh-CN`，否则会按照该样式默认的英文格式处理姓名。

是吗，谢谢您，不过这样看来我寄了。
