### ISSUE TITLE
整理样式

### ISSUE THREAD

**Issue by zepinglee** [zotero-chinese/styles#327]
打算移除以下样式，避免给用户造成困惑，比如下图的例子。

<img width="321" alt="Screenshot 2024-06-19 at 00 10 49" src="https://github.com/zotero-chinese/styles/assets/12290822/cde12bd1-d789-47ce-bf13-569c4d7baa1b">

1. [`biotechnology-advances-custom.csl`](https://github.com/zotero-chinese/styles/blob/main/src/biotechnology-advances-custom/biotechnology-advances-customcsl) Biotechnology Advances Custom：这个是在官方 [`biotechnology-advances.csl`](https://github.com/citation-style-language/styles/blob/master/dependent/biotechnology-advances.csl)（即 [`elsevier-harvard.csl`](https://github.com/citation-style-language/styles/blob/master/elsevier-harvard.csl)）的基础上自定义了排序方式，没有必要保留在中文仓库。
4. [`nanjing-agricultural-university-author-date.csl`](https://github.com/zotero-chinese/styles/blob/main/src/nanjing-agricultural-university-author-date/nanjing-agricultural-university-author-date.csl) 旧版样式，在学校更新  2023 新版规范后已经过时。
5. [`nanjing-agricultural-university-numeric.csl`](https://github.com/zotero-chinese/styles/blob/main/src/nanjing-agricultural-university-numeric/nanjing-agricultural-university-numeric.csl) 旧版样式。学校 2023 新版只允许使用著者-出版年和脚注样式。
6. [`nanjing-agricultural-university-old.csl`](https://github.com/zotero-chinese/styles/blob/main/src/nanjing-agricultural-university-old/nanjing-agricultural-university-old.csl) 旧版样式，在学校更新  2023 新版规范后已经过时。
7. [`nanjing-agricultural-university-online-first.csl`](https://github.com/zotero-chinese/styles/blob/main/src/nanjing-agricultural-university-online-first/nanjing-agricultural-university-online-first.csl) 旧版样式，在学校更新  2023 新版规范后已经过时。

下面重复的样式需要合并处理。

- [`acta-physica-sinica-zotero-res.csl`](https://github.com/zotero-chinese/styles/blob/main/src/acta-physica-sinica-zotero-res/acta-physica-sinica-zotero-res.csl) Acta Physica Sinica (物理学报)
- [`acta-physica-sinica.csl`](https://github.com/zotero-chinese/styles/blob/main/src/acta-physica-sinica/acta-physica-sinica.csl) Acta Physica Sinica (物理学报)
- [`zhejiang-university-chinese-punctuation.csl`](https://github.com/zotero-chinese/styles/blob/main/src/zhejiang-university-chinese-punctuation/zhejiang-university-chinese-punctuation.csl) 浙江大学-中文标点
- [`zhejiang-university.csl`](https://github.com/zotero-chinese/styles/blob/main/src/zhejiang-university/zhejiang-university.csl) 浙江大学

下面英文样式提交到官方仓库。

- [`food-materials-research.csl`](https://github.com/zotero-chinese/styles/blob/main/src/food-materials-research/food-materials-research.csl)

@redleafnew 下面样式能找到原来制作时依据的规范（链接）吗？如果没有的话我建议移除，避免被用户误用。

1. [`cas-like-thesis.csl`](https://github.com/zotero-chinese/styles/blob/main/src/cas-like-thesis/cas-like-thesis.csl) cas-like-thesis
2. [`cas-like-thesis-zotero-ask.csl`](https://github.com/zotero-chinese/styles/blob/main/src/cas-like-thesis-zotero-ask/cas-like-thesis-zotero-ask.csl) cas-like-thesisaa
3. [`nsfc-author-date.csl`](https://github.com/zotero-chinese/styles/blob/main/src/nsfc-author-date/nsfc-author-date.csl) NSFC作者年代 (显示全部作者, 姓名取消大写, 无 URL DOI)

**Comment by redleafnew** [comment]
可以的

**Comment by zepinglee** [comment]
南京农业大学的格式规范分为自然科学和人文社科两类，前者使用著者-出版年制，后者可选顺序编码制（其实为脚注样式）和著者-出版年制，但文后参考文献的排列方式与自然科学类不同。所以我打算按照以下修改样式 id 和名称，方便用户选择需要的样式。

- `nanjing-agricultural-university` 南京农业大学（著者-出版年） -> `nanjing-agricultural-university-natural-sciences` 南京农业大学（自然科学类）
- `nanjing-agricultural-university-note` 南京农业大学（人文社科类，脚注）-> `nanjing-agricultural-university-humanities-and-social-sciences-note` 南京农业大学（人文社科类，脚注）

`nanjing-agricultural-university-humanities-and-social-sciences-author-date` 南京农业大学（人文社科类，著者-出版年）等有人提需求再制作吧。
