### ISSUE TITLE
新样式：外语教学与研究杂志

### ISSUE THREAD

**Issue by AsukaInochi** [zotero-chinese/styles#331]
### 期刊 / 学校名称

外语教学与研究杂志

### 英文名称

Foreign Language Teaching and Research

### 相关领域

- [ ] anthropology
- [ ] astronomy
- [ ] biology
- [ ] botany
- [ ] chemistry
- [ ] communications
- [ ] engineering
- [ ] geography
- [ ] geology
- [ ] history
- [ ] humanities
- [ ] law
- [X] linguistics
- [ ] literature
- [ ] math
- [ ] medicine
- [ ] philosophy
- [ ] physics
- [ ] political_science
- [ ] psychology
- [ ] science
- [ ] social_science
- [ ] sociology
- [ ] zoology

### 参考文献格式

[fltrp_stylesheet.pdf](https://github.com/user-attachments/files/15921488/fltrp_stylesheet.pdf)

### 条目信息

```json
 {}
```

**Comment by zepinglee** [comment]
有没有官网的链接？

**Comment by AsukaInochi** [comment]
首先感谢回复！
关于官网的链接，外语教学与研究 - 北京外国语大学学术期刊网 (bfsujournals.com)，这个是该刊的官网；外语教学与研究 (cnki.net)这个是该刊的投稿网址，在后者也可以查到有关论文格式的要求和说明，还请过目。







&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zotero-chinese/styles"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月21日(星期五) 上午9:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zotero-chinese/styles] 新样式：外语教学与研究杂志 (Issue #331)





 
有没有官网的链接？

**Comment by AsukaInochi** [comment]
https://www.bfsujournals.com/tjwz/yyyjy/wgyjxyyj/index.shtml 前者
https://wjyy.cbpt.cnki.net/WKG/WebPublication/index.aspx?mid=wjyy 后者

**Comment by zepinglee** [comment]
> 首先感谢回复！ 关于官网的链接，外语教学与研究 - 北京外国语大学学术期刊网 (bfsujournals.com)，这个是该刊的官网；外语教学与研究 (cnki.net)这个是该刊的投稿网址，在后者也可以查到有关论文格式的要求和说明，还请过目。

> [fltrp_stylesheet.pdf](https://github.com/user-attachments/files/15921488/fltrp_stylesheet.pdf)

我的意思是这份文件有没有官网链接？

**Comment by AsukaInochi** [comment]
没有，这个是同学发的文件，不好意思



---原始邮件---
发件人: "Zeping ***@***.***&gt;
发送时间: 2024年6月21日(周五) 下午2:31
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zotero-chinese/styles] 新样式：外语教学与研究杂志 (Issue #331)




  
首先感谢回复！ 关于官网的链接，外语教学与研究 - 北京外国语大学学术期刊网 (bfsujournals.com)，这个是该刊的官网；外语教学与研究 (cnki.net)这个是该刊的投稿网址，在后者也可以查到有关论文格式的要求和说明，还请过目。
   
fltrp_stylesheet.pdf
  
我的意思是这份文件有没有官网链接？

**Comment by northword** [comment]
https://wjyy.cbpt.cnki.net/WKG/WebPublication/wkTextContent.aspx?navigationContentID=fb02c076-ad27-4740-aa32-01c23807b2f2&mid=wjyy

粗略看上去还是有几个比较接近，比如 https://zotero-chinese.com/styles/east-china-normal-university

**Comment by AsukaInochi** [comment]
感谢回复，看着引用部分是挺像的，但是好像没有序号，是按字母表顺序排序的🥲



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月21日(周五) 下午3:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zotero-chinese/styles] 新样式：外语教学与研究杂志 (Issue #331)




 
https://wjyy.cbpt.cnki.net/WKG/WebPublication/wkTextContent.aspx?navigationContentID=fb02c076-ad27-4740-aa32-01c23807b2f2&amp;mid=wjyy
 
粗略看上去还是有几个比较接近，比如 https://zotero-chinese.com/styles/east-china-normal-university

**Comment by zepinglee** [comment]
> [fltrp_stylesheet.pdf](https://github.com/user-attachments/files/15921488/fltrp_stylesheet.pdf)

这份文件也可以，我晚上处理一下。

我们一般要求提供官网的格式要求，保证其权威性。建议找期刊编辑或同学确认一下文件的来源。

**Comment by AsukaInochi** [comment]
万分感激，他这个文中引用也挺特殊的。
比如说如果是作者基本观点就不需要页码只需要作者名和年份，如果是具体的观点就需要具体页码。
两个人作者的时候就是逗号隔开，英文是&amp;符号，三个人又是只显示第一个作者的名字，后面的中文用等，英文用斜体的et al.来表示。
参考文献条目按照的是字母顺序，中文是按汉语拼音排序。
十分感谢您的回复，回应太迅速了，很感激，谢谢！



---原始邮件---
发件人: "Zeping ***@***.***&gt;
发送时间: 2024年6月21日(周五) 下午4:07
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zotero-chinese/styles] 新样式：外语教学与研究杂志 (Issue #331)




  
fltrp_stylesheet.pdf
  
这份文件也可以，我晚上处理一下。
 
我们一般要求提供官网的格式要求，保证其权威性。建议找期刊编辑或同学确认一下文件的来源。

**Comment by AsukaInochi** [comment]
不好意思补充说明一下，关于参考文献里的条目排列，如果文章是中文标题，能做到捕捉英文标题，并组合本身的中文标题，再通过加[ ]符号的方式补充在英文标题的后面嘛？
参考的图片在附件里







&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zotero-chinese/styles"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月21日(星期五) 下午4:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zotero-chinese/styles] 新样式：外语教学与研究杂志 (Issue #331)





  
fltrp_stylesheet.pdf
  
这份文件也可以，我晚上处理一下。
 
我们一般要求提供官网的格式要求，保证其权威性。建议找期刊编辑或同学确认一下文件的来源。

**Comment by zepinglee** [comment]
> 不好意思补充说明一下，关于参考文献里的条目排列，如果文章是中文标题，能做到捕捉英文标题，并组合本身的中文标题，再通过加[ ]符号的方式补充在英文标题的后面嘛？ 参考的图片在附件里

GitHub 好像看不到邮件中的图片，需要重新上传一下。

**Comment by zepinglee** [comment]
@AsukaInochi 有个问题是，期刊如果有卷号怎么处理？《外语教学与研究》参考文献格式要求的示例只有期号没有卷号。

<img width="683" alt="Screenshot 2024-06-22 at 21 49 05" src="https://github.com/zotero-chinese/styles/assets/12290822/50a8bb3a-1548-433b-b3d5-4f81b99d308b">

**Comment by zepinglee** [comment]
@AsukaInochi 在 fa44a6e7 中添加，需要校对一下。

**Comment by AsukaInochi** [comment]
您好，昨天邮箱没跳提示，附件是参考文献示例的图片
![参考文献示例](https://github.com/zotero-chinese/styles/assets/51010125/c785b1b6-d1ee-4aac-b6d0-20df85123610)

**Comment by AsukaInochi** [comment]
不好意思，我不太理解“添加”，是需要我校对吗？我看不太明白代码....

**Comment by zepinglee** [comment]
> 您好，昨天邮箱没跳提示，附件是参考文献示例的图片 ![参考文献示例](https://private-user-images.githubusercontent.com/51010125/341985151-c785b1b6-d1ee-4aac-b6d0-20df85123610.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwOTg3MTksIm5iZiI6MTcxOTA5ODQxOSwicGF0aCI6Ii81MTAxMDEyNS8zNDE5ODUxNTEtYzc4NWIxYjYtZDFlZS00YWFjLWI2ZDAtMjBkZjg1MTIzNjEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIyVDIzMjAxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmNDc3NGQxZGIyZmYyM2Y3YmIzZjFmOWEwMzk5ZjdjN2M3YmM3MjViYjQ5NDRiOWRhN2FiOTIwMmIyMGIwNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7G6tISu2JWcsFK9Bf7XWhLCajiA73XrQHo3r3qKDguE)

这是已刊发的截图吗？中文文献需要同时提供英文著录？

**Comment by zepinglee** [comment]
> 不好意思，我不太理解“添加”，是需要我校对吗？我看不太明白代码....

嗯，需要你检查一下。可以在 <https://zotero-chinese.com/styles/foreign-language-teaching-and-research/> 查看。

**Comment by AsukaInochi** [comment]
是的，外文文献就不需要，但是中文文献要在英文后面附上中文
好的 我来看看 谢谢您
![截图示例](https://github.com/zotero-chinese/styles/assets/51010125/3c523294-7106-4671-9831-cd98ca663bdf)

**Comment by zepinglee** [comment]
> 是的，外文文献就不需要，但是中文文献要在英文后面附上中文 好的 我来看看 谢谢您 

噢那还需要再修改一下。不过这种双语著录的格式略麻烦。

具体的文献字段填写方式可以参考《心理学报》的示例文献。 <https://www.zotero.org/groups/4677213/chinese_csl_development/collections/7SP7XX8X>。

**Comment by AsukaInochi** [comment]
您好，我检查了一下，除了可能我自己导入英文文献到zotero的途径有问题导致的字段不完整和中文文献要先英后中的这俩问题，其他的功能作用正常。
顺便一问，文中引用的主题观点是用  人名（出版年）、直接或者间接引述某一个具体的观点的时候就是 人名（出版年： 页码）、如果作者的名字不在自己的正文语句中的话就在句子最后面引用（人名 出版年：页码）。
请问这种文中引用的体现方式是需要怎么进行调整呢？

**Comment by zepinglee** [comment]
> 是的，外文文献就不需要，但是中文文献要在英文后面附上中文 好的 我来看看 谢谢您 ![截图示例](https://private-user-images.githubusercontent.com/51010125/342007636-3c523294-7106-4671-9831-cd98ca663bdf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MzMyODIsIm5iZiI6MTcxOTgzMjk4MiwicGF0aCI6Ii81MTAxMDEyNS8zNDIwMDc2MzYtM2M1MjMyOTQtNzEwNi00NjcxLTk4MzEtY2Q5OGNhNjYzYmRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDExMjMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjMjk2NjZjMzNkNjExMGRmNDYwMjdmZTZhZDI0NTliZjNlZTYxMDBhMTI3ZjM3MjNlYWJiNzIxYWEwYzNjNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OlA275WovLfe3VyLRLApouccutm8tDlKFOE9EjiZAdc)

这个截图的格式跟 PDF 文件的中文文献格式完全不同啊。能不能联系编辑要份正式的格式要求？省得我浪费时间。

<img width="688" alt="Screenshot 2024-07-01 at 20 01 39" src="https://github.com/zotero-chinese/styles/assets/12290822/57c9c4f0-9c7d-4840-8adb-84a84d110170">

> 顺便一问，文中引用的主题观点是用 人名（出版年）、直接或者间接引述某一个具体的观点的时候就是 人名（出版年： 页码）、如果作者的名字不在自己的正文语句中的话就在句子最后面引用（人名 出版年：页码）。 请问这种文中引用的体现方式是需要怎么进行调整呢？

需要手动输入姓名，然后插入 citation 时勾选"Omit author"。

页码目前无法正确显示，我稍后修改下。

**Comment by zepinglee** [comment]
> 页码目前无法正确显示，我稍后修改下。

在 eea74b27 中完成。
