### ISSUE TITLE
新样式：国际金融研究

### ISSUE THREAD

**Issue by jokerchz** [zotero-chinese/styles#338]
### 期刊 / 学校名称

国际金融研究

### 英文名称

Studies of International Finance

### 相关领域

social_science

### 参考文献格式

官方网页链接：http://www.gjjryj.org.cn/CN/column/column2.shtml

官方文件链接：http://www.gjjryj.org.cn/attached/file/20231218/20231218172806_284.doc

上传格式文件：
[投稿模板.docx](https://github.com/user-attachments/files/16081130/default.docx)

格式参考：
Hamilton & Wu（2012）
Eickmeier et al.（2013）
何国华和彭意（2014）
谭小芬等（2013）
[1] 何国华，彭意. 美、日货币政策对中国产出的溢出效应研究[J]. 国际金融研究，2014（2）：19-28
[2] 谭小芬，熊爱宗，陈思翀. 美国量化宽松的退出机制、溢出效应与中国的对策[J]. 国际经济评论，2013（5）：98-108
[3] Eickmeier S，Gambacorta L，Hofmann B. Understanding Global Liquidity[J]. European Economic Review，2013，68（3）：1-18
[4] Hamilton J D，Wu J C. The Effectiveness of Alternative Monetary Policy Tools in a Zero Lower Bound Environment[J]. Journal of Money，Credit and Banking，2012（1）：3-46
正文引用文献时，一位或两位作者需全部体现。两位作者时中文用“和”连接，英文使用“&”连接，前后各一个空格。三位及以上作者时仅体现第一位作者，中文采用“等”表示省略，英文采用“et al.”表示省略。
参考文献先中文后英文，按照首字母排序，序号后一个空格。除姓名及文献标识类型后为英文标点“.”加一个空格外，其余符号（包括逗号、顿号、冒号、圆括号）均为中文全角符号。结尾不加标点符号。

### 文件号

- 参考文献格式的更新日期：
- （学校）文件号：
- （期刊）ISSN 号：ISSN 1006-1029

### 相近样式

相近样式：GB/T 7714—2015（著者-出版年，双语，姓名不大写，无 URL、DOI，全角括号）

区别：
1. 当作者是两个时，相近样式使用“张三 等”和“Fan et al.”，而目标样式使用“张三和李四”和“A & B”表示。
2. 三位作者以上时，目标样式的“等”前面没有空格。
3. 目标样式除姓名及文献标识类型后为英文标点“.”加一个空格外，其余符号（包括逗号、顿号、冒号、圆括号）均为中文全角符号。结尾不加标点符号。
4. 目标样式在结尾参考文献，列示全部作者，不用“等”省略。

### 条目信息

```json
{}
```

**Comment by zepinglee** [comment]
> 目标样式在结尾参考文献，列示全部作者，不用“等”省略。

@jokerchz 这条要求是在哪里说的？我似乎没有找到

**Comment by jokerchz** [comment]
> > 目标样式在结尾参考文献，列示全部作者，不用“等”省略。
> 
> @jokerchz 这条要求是在哪里说的？我似乎没有找到

没有明确说，这是我在发表的文章中总结的。如下面两个，四个作者也没有省略
![image](https://github.com/zotero-chinese/styles/assets/128440170/6f5569ea-33b8-4f9e-a145-ee482f1c9251)
![image](https://github.com/zotero-chinese/styles/assets/128440170/ab3c8756-02cf-4ce2-bb4e-cb44e9e0b7a5)

**Comment by zepinglee** [comment]
> > > 目标样式在结尾参考文献，列示全部作者，不用“等”省略。
> > 
> > 
> > @jokerchz 这条要求是在哪里说的？我似乎没有找到
> 
> 没有明确说，这是我在发表的文章中总结的。如下面两个，四个作者也没有省略 ![image](https://private-user-images.githubusercontent.com/128440170/345386505-6f5569ea-33b8-4f9e-a145-ee482f1c9251.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMDMwNTIsIm5iZiI6MTcyMDAwMjc1MiwicGF0aCI6Ii8xMjg0NDAxNzAvMzQ1Mzg2NTA1LTZmNTU2OWVhLTMzYjgtNGY5ZS1hMTQ1LWVlNDgyZjFjOTI1MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QxMDMyMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wODFiYTFhYTczY2MzMDhiZWE5NDdjY2Q0ZTE3NDRhYWU4MmU4MTU1MTRiODBlYTlkYzE0OGY3Y2FkNjhjZmVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Vwb-Vq_Uha--CmutklmQh-gGxY5hax_dDe3zof3HA6k) ![image](https://private-user-images.githubusercontent.com/128440170/345386586-ab3c8756-02cf-4ce2-bb4e-cb44e9e0b7a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMDMwNTIsIm5iZiI6MTcyMDAwMjc1MiwicGF0aCI6Ii8xMjg0NDAxNzAvMzQ1Mzg2NTg2LWFiM2M4NzU2LTAyY2YtNGNlMi1iYjRlLWNiNDRlOWUwYjdhNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QxMDMyMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NjI2YWIxZjIwZjlkYmJhODMwMjg1YWRmMTRjYThiZWY2MDc5MGQ3ZmNlZWMwNzQxNDVkZDIwMjIxZmU0ODZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3FJcCKaIlWJQvJQVVIw8DvcMw0Y-7RXNYcjmPSXlk1Q)

我找了最新的一篇 <http://www.gjjryj.org.cn/CN/Y2024/V0/I6/3> 是按照 GB/T 7714 的格式省略的。所以我倾向于按照国标的格式省略。

<img width="772" alt="Screenshot 2024-07-03 at 18 34 51" src="https://github.com/zotero-chinese/styles/assets/12290822/705036af-99e0-4028-9ec7-23ac14c7dea6">

**Comment by zepinglee** [comment]
另外国标的“著者-出版年”制的年份是紧跟在作者姓名后的，建议给编辑反馈下。

<img width="799" alt="Screenshot 2024-07-03 at 18 36 56" src="https://github.com/zotero-chinese/styles/assets/12290822/828d5e49-250d-40c7-af63-7b09d932e9bc">

**Comment by zepinglee** [comment]
已在 6dc6aa6 中添加。

**Comment by zepinglee** [comment]
> 好的收到，太谢谢您了！ 现在就可以了是吗

是的，见 <https://zotero-chinese.com/styles/studies-of-international-finance/>。

**Comment by jokerchz** [comment]
> > 好的收到，太谢谢您了！ 现在就可以了是吗
> 
> 是的，见 https://zotero-chinese.com/styles/studies-of-international-finance/。

您好，我还想问一下，我在word里插入引用时，外国作者会变成这样，和预览的不一样，这是为什么呀？
![image](https://github.com/zotero-chinese/styles/assets/128440170/62a57614-1f53-4581-a0a2-26ef01c5760a)

**Comment by zepinglee** [comment]
> > > 好的收到，太谢谢您了！ 现在就可以了是吗
> > 
> > 
> > 是的，见 [https://zotero-chinese.com/styles/studies-of-international-finance/。](https://zotero-chinese.com/styles/studies-of-international-finance/%E3%80%82)
> 
> 您好，我还想问一下，我在word里插入引用时，外国作者会变成这样，和预览的不一样，这是为什么呀？ ![image](https://private-user-images.githubusercontent.com/128440170/345402330-62a57614-1f53-4581-a0a2-26ef01c5760a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMDY1MTcsIm5iZiI6MTcyMDAwNjIxNywicGF0aCI6Ii8xMjg0NDAxNzAvMzQ1NDAyMzMwLTYyYTU3NjE0LTFmNTMtNDU4MS1hMGEyLTI2ZWYwMWM1NzYwYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QxMTMwMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YmM1NWE3M2EwMjU2YTcxY2JmMGJmYTA3NjE4MDBiZWFkNjI5ZGM1MTIxMDE5MjI1MzdmZjA1ZWQ0OTM1OGY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vTeAfGGO5Zi2fo88oNVeOdfZnTg8pTX279-JiVA2I3Q)

<https://github.com/zotero-chinese/styles/wiki/FAQ#为何英文文献会显示中文等卷而不是et-al-vol>

**Comment by jokerchz** [comment]
> > > > 好的收到，太谢谢您了！ 现在就可以了是吗
> > > 
> > > 
> > > 是的，见 [https://zotero-chinese.com/styles/studies-of-international-finance/。](https://zotero-chinese.com/styles/studies-of-international-finance/%E3%80%82)
> > 
> > 
> > 您好，我还想问一下，我在word里插入引用时，外国作者会变成这样，和预览的不一样，这是为什么呀？ ![image](https://private-user-images.githubusercontent.com/128440170/345402330-62a57614-1f53-4581-a0a2-26ef01c5760a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMDY1MTcsIm5iZiI6MTcyMDAwNjIxNywicGF0aCI6Ii8xMjg0NDAxNzAvMzQ1NDAyMzMwLTYyYTU3NjE0LTFmNTMtNDU4MS1hMGEyLTI2ZWYwMWM1NzYwYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QxMTMwMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YmM1NWE3M2EwMjU2YTcxY2JmMGJmYTA3NjE4MDBiZWFkNjI5ZGM1MTIxMDE5MjI1MzdmZjA1ZWQ0OTM1OGY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vTeAfGGO5Zi2fo88oNVeOdfZnTg8pTX279-JiVA2I3Q)
> 
> [https://github.com/zotero-chinese/styles/wiki/FAQ#为何英文文献会显示中文等卷而不是et-al-vol](https://github.com/zotero-chinese/styles/wiki/FAQ#%E4%B8%BA%E4%BD%95%E8%8B%B1%E6%96%87%E6%96%87%E7%8C%AE%E4%BC%9A%E6%98%BE%E7%A4%BA%E4%B8%AD%E6%96%87%E7%AD%89%E5%8D%B7%E8%80%8C%E4%B8%8D%E6%98%AFet-al-vol)
> 
> 需要将样式改成默认语言为英文吗（这样中文文献需要设置 `zh-CN`）？这个期刊普遍引用中文文献多还是英文文献多？

引用中文多。但我明白我的问题了，有重复的项目，有一份文献标记了语言，有一份文献没有标记，我错误引用了旧版本
