### ISSUE TITLE
新样式：财贸经济

### ISSUE THREAD

**Issue by Bigconfidence666** [zotero-chinese/styles#339]
### 期刊 / 学校名称

财贸经济

### 英文名称

Finance & Trade Economics

### 相关领域

social_science

### 参考文献格式

官方网页链接：https://cmjj.ajcass.com/

官方文件链接：中文：<https://cmjj.ajcass.com/UploadFile/SiteContent/FJList/iri0srop.doc>；
                          英文：https://cmjj.ajcass.com/UploadFile/SiteContent/FJList/t03nic1y.doc

上传格式文件：
[英文参考文献说明.docx](https://github.com/user-attachments/files/16201529/5-.docx)
[中文参考文献说明.docx](https://github.com/user-attachments/files/16201530/6-.docx)

格式参考：
引注和参考文献表的格式，请分别见上传的格式文件，期刊有简洁且直观的说明

### 文件号

- 参考文献格式的更新日期：2016.4.20
- （学校）文件号：
- （期刊）ISSN 号：ISSN1002-8102

### 相近样式

相近样式：管理世界：http://www.zotero.org/styles/journal-of-management-world

区别：
与相近样式相比，目前发现目标样式中有如下几处区别：
1、参考文献表，中文著作，无“主编”二字，出版社后无逗号直接跟XX年版
2、参考文献表，中文期刊，期刊名后无逗号直接跟XX年XX期
3、引注，2个英文作者以“和”而不是and连接，3个及以上英文作者用“等”而不是et al.
4、参考文献表，英文著作、英文期刊的格式有几处不同，比对格式文献示例可知（直接看示例会比较直观）

### 条目信息

```json
{}
```

**Comment by zepinglee** [comment]
好的，体例信息很完整，我稍后制作。

顺便问一下，经济学领域哪个期刊的参考文献格式比较有影响力？《管理世界》吗？

**Comment by Bigconfidence666** [comment]
> 好的，体例信息很完整，我稍后制作。
> 
> 顺便问一下，经济学领域哪个期刊的参考文献格式比较有影响力？《管理世界》吗？

WOW感谢您！
经济学（国内）期刊中，大致认为这5大期刊排第1梯队：经济研究、管理世界、中国工业经济、世界经济、经济学（季刊）。
目前这5本名期刊的CSL社区已有提供啦。我请求的《财贸经济》大致处于第2.5梯队，也挺不错的hhh

**Comment by zepinglee** [comment]
在 4ab00ab 中添加。

> 经济学（国内）期刊中，大致认为这5大期刊排第1梯队：经济研究、管理世界、中国工业经济、世界经济、经济学（季刊）。 

我只是想吐槽下，这几个期刊的格式怎么各不相同。

**Comment by Bigconfidence666** [comment]
> 在 [4ab00ab](https://github.com/zotero-chinese/styles/commit/4ab00ab61be965fb2da4056d417ecdceaddbcad5) 中添加。
> 
> > 经济学（国内）期刊中，大致认为这5大期刊排第1梯队：经济研究、管理世界、中国工业经济、世界经济、经济学（季刊）。
> 
> 我只是想吐槽下，这几个期刊的格式怎么各不相同。

太强了，感谢大佬解燃眉之急！！！可能不同期刊编辑审美不同hhhh
还想请教下您，我现在点插入引注后，正文只出现默认引注格式比如（XX、XX，20XX）、（XX等，20XX），但我有时也需要将名字提出来，写成XX和XX（20XX）、XX等（20XX）这种形式。请问这是直接修改默认引注，还是点击插入引注时可选的呢？

**Comment by northword** [comment]
> 还想请教下您，我现在点插入引注后，正文只出现默认引注格式比如（XX、XX，20XX）、（XX等，20XX），但我有时也需要将名字提出来，写成XX和XX（20XX）、XX等（20XX）这种形式。请问这是直接修改默认引注，还是点击插入引注时可选的呢？

https://zotero-chinese.com/user-guide/ms-word-plugin#%E7%9C%81%E7%95%A5%E4%BD%9C%E8%80%85-%E5%9C%A8%E6%96%87%E6%9C%AC%E4%B8%AD%E4%BD%BF%E7%94%A8%E4%BD%9C%E8%80%85

分别插入引注，插入时，勾选“省略作者”，并在正文中手动键入作者。

**Comment by Bigconfidence666** [comment]
> > 还想请教下您，我现在点插入引注后，正文只出现默认引注格式比如（XX、XX，20XX）、（XX等，20XX），但我有时也需要将名字提出来，写成XX和XX（20XX）、XX等（20XX）这种形式。请问这是直接修改默认引注，还是点击插入引注时可选的呢？
> 
> https://zotero-chinese.com/user-guide/ms-word-plugin#%E7%9C%81%E7%95%A5%E4%BD%9C%E8%80%85-%E5%9C%A8%E6%96%87%E6%9C%AC%E4%B8%AD%E4%BD%BF%E7%94%A8%E4%BD%9C%E8%80%85
> 
> 分别插入引注，插入时，勾选“省略作者”，并在正文中手动键入作者。

感谢感谢！
