### ISSUE TITLE
请问GB/T7714-2015(顺序编码，双语，姓名取消大写，无URL DOI，引注有页码)可否增加存储到“脚注”的选项

### ISSUE THREAD

**Issue by yzy1228682367** [zotero-chinese/styles#340]
### 期刊 / 学校名称

GB/T7714-2015

### 英文名称

GB/T7714-2015

### 相关领域

None

### 参考文献格式

官方网页链接：

官方文件链接：http://www.gdfxh.org.cn/xhdt/tzwj/content/post_158523.html

上传格式文件：

格式参考：
　　论文中引用参考文献注释序号用上标方括号加数字如[1]表示，参考文献采用当页脚注，按国家标准规范标注。
　　（1）专著：[序号]作者.专著名[M].出版地：出版社，出版年.
　　（2）期刊文献：[序号]作者.题（篇）名[J].刊名，出版年（期号）.
　　（3）论文集：[序号]作者.题（篇）名[C].出版地：出版社，出版年.
　　（4）学位论文：[序号]作者.题（篇）名[D].授学位地：授学位单位，授学位年.
　　（5）专利文献：[序号]专利申请者.专利题名[P].专利国别：专利号，出版日期.
　　（6）报纸文章：[序号]作者.题（篇）名[N].报纸名，出版日期.
　　（7）电子文档：[序号]作者.题（篇）名[文献类型/载体类型].网址，发表日期.

### 文件号

- 参考文献格式的更新日期：
- （学校）文件号：
- （期刊）ISSN 号：

### 相近样式

相近样式：

区别：

### 条目信息

```json
{}
```

**Comment by zepinglee** [comment]
直接使用 [GB/T 7714—2015（脚注，双语，姓名不大写，无 URL、DOI）](https://zotero-chinese.com/styles/gb-t-7714-2015-note-bilingual-no-uppercase-no-url-doi)。“上标方括号加数字如[1]”需要在 Word 的脚注编号中设置，CSL 无法处理。

**Comment by yzy1228682367** [comment]
感谢大佬！我的我的，没有仔细看仓库(/∇＼*)

**Comment by yzy1228682367** [comment]
大佬，那请问这个版本可不可以重复引注不省略呀🙏

**Comment by zepinglee** [comment]
> 大佬，那请问这个版本可不可以重复引注不省略呀🙏

见修改后的 [GB/T 7714—2015（脚注，双语，姓名不大写，无 URL、DOI，重复引用不省略）](https://zotero-chinese.com/styles/gb-t-7714-2015-note-bilingual-no-uppercase-no-url-doi-no-ibid)。

**Comment by yzy1228682367** [comment]
多谢大佬！
