### ISSUE TITLE
申请新格式：Chinese Science Bulletin

### ISSUE THREAD

**Issue by JoyceWang321** [zotero-chinese/styles#341]
### 期刊 / 学校名称

中国科学通报

### 英文名称

Chinese Science Bulletin 

### 相关领域

None

### 参考文献格式

官方网页链接：https://www.sciengine.com/CSB/authorCenter?scroll=section_2

官方文件链接：

上传格式文件：https://www.sciengine.com/cfs/files/files/upfile/Chinese%20Science%20Bulletin.ens

### 文件号

- 参考文献格式的更新日期：
- （学校）文件号：
- （期刊）ISSN 号：

### 相近样式

相近样式：

区别：

### 条目信息

```json
{}
```

**Comment by JoyceWang321** [comment]
1. 对于作者姓名，姓氏的完整拼写出现在给定姓名首字母之前，中间有一个空格。

2. 如果作者超过3人，则前3人姓名后跟“et al”。

3. 文章标题应以首字母大写字母标识，标题的其余部分为小写。

4. 期刊名称的正确缩写，请参阅ISO指南（例如，中国科学通报的中国科学公牛，中国生命科学的中国生命科学）。

5. 对于书名和后续名称，所有名义词和功能词的首字母均大写 4 个以上的字母。

6. 论文集需要提供编辑姓名、出版人、出版地址、开头和结尾页。

7. 未发表的材料或没有卷号和期号的论文不能作为参考文献引用，但有 DOI 的除外。

8. 网站和主页不能作为参考引用。

**Comment by zepinglee** [comment]
需要处理中文文献格式吗？

<img width="393" alt="Screenshot 2024-07-15 at 16 50 17" src="https://github.com/user-attachments/assets/557f1168-adbc-4be6-8004-126c75d077a4">

**Comment by JoyceWang321** [comment]
应该需要的

**Comment by zepinglee** [comment]
在 9c50df1 中添加。你检查下还有没有格式问题。

**Comment by JoyceWang321** [comment]
非常感谢
