### ISSUE TITLE
新样式：数量经济技术经济研究

### ISSUE THREAD

**Issue by Xiong-Xiao** [zotero-chinese/styles#342]
### 期刊 / 学校名称

数量经济技术经济研究

### 英文名称

JOURNAL OF QUANTITATIVE & TECHNOLOGICAL ECONOMICS

### 相关领域

social_science

### 参考文献格式

官方网页链接：http://www.jqte.net/sljjjsjjyj/ch/index.aspx    

官方文件链接：http://www.jqte.net/download_upload_file.aspx?file_name=/uploadfile/news_images/sljjjsjjyj/2023-06-06/%E3%80%8A%E6%95%B0%E9%87%8F%E7%BB%8F%E6%B5%8E%E6%8A%80%E6%9C%AF%E7%BB%8F%E6%B5%8E%E7%A0%94%E7%A9%B6%E3%80%8B%E4%BD%93%E4%BE%8B%EF%BC%88%E5%AE%9A%E7%A8%BF%EF%BC%89.doc

上传格式文件：

格式参考：

### 文件号

- 参考文献格式的更新日期：
- （学校）文件号：
- （期刊）ISSN 号：1000-3894

### 相近样式

相近样式：财贸经济https://zotero-chinese.com/styles/finance-and-trade-economics/

区别：文中引用看起来是相同的，都是author-date格式。且无论中英文，两个作者都用"和"相连，三个以及以上都用"等"。

 文后参考文献格式不同。文后参考文献格式更像这种：https://zotero-chinese.com/styles/gb-t-7714-2015-author-date-bilingual-no-uppercase

### 条目信息

我会增补这一段内容。

**Comment by zepinglee** [comment]
文件链接无法访问，需要在 issue 中上传一份 doc 文档。

**Comment by Xiong-Xiao** [comment]
[数量经济技术经济研究_投稿格式.pdf](https://github.com/user-attachments/files/16243565/_.pdf)

谢谢回复。
doc文件不支持上传，我转为了pdf文件。原始doc文件可以通过在官网http://www.jqte.net/sljjjsjjyj/ch/index.aspx界面的”常用下载”-《数量经济技术经济研究》体例获取。

**Comment by zepinglee** [comment]
在 7ec196c 中添加。

这个中文和英文的格式不完全一样，比如出版年的位置，处理起来真是麻烦。

**Comment by Xiong-Xiao** [comment]
> 在 [7ec196c](https://github.com/zotero-chinese/styles/commit/7ec196c51abec1d47f77284de3cb1f756ed0a585) 中添加。
> 
> 这个中文和英文的格式不完全一样，比如出版年的位置，处理起来真是麻烦。

辛苦了，我可以做一些什么？

**Comment by zepinglee** [comment]
> 辛苦了，我可以做一些什么？

你只需要检查一下有没有格式问题 <https://zotero-chinese.com/styles/journal-of-quantitative-and-technological-economics/>。

**Comment by zepinglee** [comment]
可以将录入的 Zotero 信息导出为 CSL-JSON 格式（再压缩成 zip）发上来吗？我来测试下。

**Comment by Xiong-Xiao** [comment]
[导出的条目.zip](https://github.com/user-attachments/files/16251632/default.zip)

我分别从知网、百度学术、谷歌学术和学校图书馆等渠道通过zotero摘去的这些信息。有一些摘取信息和原文显示的不一致，我进行了修改，但是没有全都修改(因为有一些找不到对应格式)。

**Comment by zepinglee** [comment]
> 谢谢！ 我将这本期刊的格式范例中的文献全都导入了zotero，并插入。发现了一些不同。
> 
> 1. 文末参考文献的排序不同，不过我没看出参考文本中他是按什么排序的，可能是他排序有误。

著者-出版年制只能按照著者、出版年进行索引，所以参考文献表一般也按照这两者进行排序。而且体例要求“参考文献先中文后外文”。

> 2. 文末参考文献清单中作者之间的逗号应该是英文逗号","而不是中文逗号"，"。

目前中文文献的是西文半角逗号加空格，不是中文全角逗号。

> 3. 标识不对。比如“刘冲, 沙学康, 张妍. 交错双重差分：处理效应异质性与估计方法选择“这篇文章是网络首发，所以应该是[J/OL]标识。但是我也不知道zotero是否支持这个格式，我是直接在知网抓取的信息，好像没有所谓的网络首发或者论文集[C]格式。或许可以忽略。

网络首发文献没有卷次和期号，所以 CSL 样式是以这两者为依据判断的。所以删掉 volume 和 issue 就如预期了。

https://github.com/zotero-chinese/styles/blob/af88372c8632773647d7c25cfcf464a1ee748218/src/journal-of-quantitative-and-technological-economics/journal-of-quantitative-and-technological-economics.csl#L261-L267

> 4. 中文著作的格式有误。 正确的为：
>    [2]	张晓峒.计量经济分析[M].（专著题目，专著用[M]，后接点号）南开大学出版社,（出版社名称，后接逗号）2000.（年份，以点号结尾）
>    目前为：
>    [5] 张晓峒, 2000, 计量经济分析 [M]. 南开大学出版社.
>    主要差异在：年份位置有误，应该放在出版社后面。且作者后面是用.而不是逗号","

CSL 不能自动识别文献的语言，二是根据 `language` 字段的内容处理的。建议使用茉莉花或者 <https://github.com/northword/zotero-format-metadata> 之类的插件，在录入文献时自动填写 `language`。

> 5. 中文期刊的格式有误。正确的为：
>    [1]	李万利,潘文东,袁凯彬.企业数字化转型与中国实体经济发展[J].（论文题目，期刊论文用[J]，后接点号）数量经济技术经济研究,（期刊名，后接逗号）2022,(9):1~25.（发表年份，后接逗号，括号内写期数，后接冒号，接起止页码，以点号结尾）
>    目前为：
>    [2] 李万利, 潘文东, 袁凯彬. 企业数字化转型与中国实体经济发展[J]. 数量经济技术经济研究, 2022, 39, (9): 1~25.
>    主要差异在：时间格式有差异。年份,(期数):起始页~终止页码。不需要出现39这个卷次。

原来这个体例中文期刊不显示卷次，但是英文期刊显示卷次。已修改，见 [fe2d837](https://github.com/zotero-chinese/styles/commit/fe2d837da099765ca8f0aed782f82a17147790e6) 中 `index.md` 的变化。

> 6. 中文网络首发文献没有提供DOI号。不知道是否和3是同一个问题，即zotero不支持网络首发这个格式。

见上面的回复。

> 7. 中文学位论文格式有误。
>    正确的是：
>    王津港.（作者与论文题目间用点号）动态面板数据模型[D].（论文题目，学位论文用[D]，后接点号）华中科技大学博士学位论文,（学校名称加学位论文类别，后接逗号）2009.（年份，以点号结尾）
>    目前的是：
>    王津港, 2009, 动态面板数据模型估计及其内生结构突变检验理论与应用 [D]. 华中科技大学.
>    主要差异在：年份位置有误，应该在结尾。且作者后面是用.而不是逗号。除了学校名称之外还有“博士学位论文“这几个字。

文献语言问题同上。另外“博士学位论文”需要填写在 `Type` 字段。

> 8. 英文学位论文格式有误。
>    在[D]后面是逗号,而不是点号.
> 
> 英文的有许多对不太上，但是感觉不是代码的问题了。而是zotero本身支持和我输入的问题。

是我搞错了西文文献的分隔符，应该是逗号，跟中文格式的句点完全不同。已修改。

**Comment by Xiong-Xiao** [comment]
> 目前中文文献的是西文半角逗号加空格，不是中文全角逗号。
那么应该是多了一个空格。中文文献的作者之间只有逗号,没有空格。类似的，中文最后一位作者接.之后也没有空格就衔接到了文章标题。类似的，主编也没有空格。
![image](https://github.com/user-attachments/assets/276725e9-d041-4e9b-a434-e05accb19d70)


另外，请问您知道对于“论文集”这一类型[C], zotero是否支持？如果支持我应该把他定义为哪一个类型？

**Comment by zepinglee** [comment]
> 那么应该是多了一个空格。中文文献的作者之间只有逗号,没有空格。类似的，中文最后一位作者接.之后也没有空格就衔接到了文章标题。类似的，主编也没有空格。 

已在 797d0aa 中去掉中文文献的空格。

> 另外，请问您知道对于“论文集”这一类型[C], zotero是否支持？如果支持我应该把他定义为哪一个类型？

Zotero 和 CSL 不区分“论文集”和“图书”（book），不过一般情况引用的是论文集的其中一篇，所以问题不大。

另外我刚发现这个体例对“[C]”的理解更国标不懂，国标的[C]特指会议论文集（Conference），而这个体例中似乎包含了所有论文集（Collection?）已在 bb439a5 中修改。

**Comment by Xiong-Xiao** [comment]
谢谢细致的工作。

我又核对了一下，还有几处遗漏：
1. 中文的论文集[C]好像也不需要报告卷数
2. 英文期刊[J]的卷次和期号之间没有逗号。
![image](https://github.com/user-attachments/assets/54238fbb-a873-4163-8145-1d8f1712c2fd)

其他我也没发现异常了。
我需要关闭这个issue吗？

**Comment by zepinglee** [comment]
> 1. 中文的论文集[C]好像也不需要报告卷数

有时候专著或论文集是多卷书，需要卷次进行区分。参考 GB/T 7714。

<img width="765" alt="Screenshot 2024-07-17 at 22 54 16" src="https://github.com/user-attachments/assets/e2c52566-f516-4421-8900-b27a378ad7a0">

> 2. 英文期刊[J]的卷次和期号之间没有逗号。

已在 a94c394 中修改。

你觉得没问题了就可以关掉 issue。
