### ISSUE TITLE
新样式：《原子核物理评论》

### ISSUE THREAD

**Issue by zhengyidandawn** [zotero-chinese/styles#343]
### 期刊 / 学校名称

原子核物理评论

### 英文名称

Nuclear Physics Review

### 相关领域

physics

### 参考文献格式

官方网页链接：http://www.npr.ac.cn/news/tougaozhinan.htm

官方文件链接：http://www.npr.ac.cn/news/lunwenmoban.htm

上传格式文件：
[npr论文模板.docx](https://github.com/user-attachments/files/16346310/npr.docx)

格式参考：2.3 参考文献以文中出现的先后次序排序并加方括号，文献作者要求写出前三名。内部资料、未公开发表的最好不要引用。为了便于国外数据库的检索，文后所列中文参考文献的格式应是先给出英文译文，并在该文献后用括号注明(in Chinese)，然后附上相应的中文文献。格式如下：

         1) 期 刊 [序号] 作者姓名(前三名，作者姓前名后，不加缩写点). 文题名[J]. 期刊名称，出版年，卷号(期号): 起始页码. DOI号.

         2) 专 著 [序号] 作者姓名(前三名). 书名[M]. 版本(第１版可略).出版地: 出版者，出版年，起-止页码.

         3) 论文集 [序号] 作者姓名(前三名). 文题名//编者. 论文集名. 出版地: 出版者，出版年，起始页码.

         4) 学位论文 [序号] 作者姓名. 论文题名[D]. 学位获得地地名: 学位获得单位，出版年(月份)，起-止页码.

### 文件号

- 参考文献格式的更新日期：2024/07/23
- （学校）文件号：
- （期刊）ISSN 号：1007-4627

### 相近样式

相近样式：https://zotero-chinese.com/styles/acta-physica-sinica/

区别：需要URL, DOI，姓全部大写，中文文献需中英文对照

### 条目信息

例子：英文期刊文献： [1] COLO G , GIAI N V, MEYER J, et al. Microscopic determination of the nuclear incompressibility within the nonrelativistic framework[J]. Phys Rev C, 2004, 70: 024307. doi: 10.1103/PhysRevC.70.024307 
         中文期刊的中文文献：
[2]LI Qiang , WEI Zengquan. Basic Theory of Heavy Ion Beam Used in Tumor Radiotherapy[J]. Nuclear Physics Review, 1996, 13(4): 39(in Chinese). doi: 10.11804/NuclPhysRev.13.04.039
(李强，卫增泉. 重离子径迹结构的Monte Carlo计算模型[J].原子核物理评论，1996，13(4): 39. 
doi: 10.11804/NuclPhysRev.13.04.039)
    

2）专 著  [序号] 作者姓名(前三名)，等.书名. 版本(第１版可略). 出版地: 出版者，出版年：起—止页码.  
[4]DING Da Zhao, CHEN Yong Shou, ZHANG Huan Qiao. Progress in Nuclear Physics[M]. Shanghai, Shanghai Science and Technology Publishing House, 1997：299-382 (in Chinese) .
(丁大钊，陈永寿，张焕乔. 原子核物理进展[M]. 上海:上海科学技术出版社, 1997：299-382.)
3）论文集  [序号] 作者姓名(前三名). 文题名[C]//编者. 论文集名. 出版地: 出版者, 出版年：起始页码
示例： 
[5] MATSUMOTO H, KAZACOV S, SAITO K. A New Design for a Super-Conducting Cavity Input Coupler[C] // Horak C ed. Proceedings of the Particle Accelerator Conference. New York: Institute of Electrical and Electronics Engineers, 2005： 4141.

4）学位论文 [序号] 作者姓名. 论文题名[D]. 学位获得所在地地名：学位获得单位，出版年(月份)：起—止页码. 

5) 预印本(Preprint): 例如：SJOSTRAND T, LOONNBLAD L, MRENNA S. arXiv: hep-ph/0108264, 2001.

6）专利文献［序号］ 专利申请者或所有者. 专利题名: 专利国别，专利号[文献类型标志]. 公告日期或公开日期[引用日期]. 获取和访问路径.

7）电子文献[序号]主要责任者. 题名: 其他题名信息[文献类型标志/文献载体标志]. 出版地: 出版者, 公告日期或公开日期[引用日期]. 获取和访问路径.
    关于网络参考文献，本刊从即日起,执行国家参考文献标准中的新规定，因此对参考文献的有些地方进行了调整，特别是网络参考文献做了大的改动，因此，若是论文中有网络参考文献，请以此为参考。
    若其他信息没有或是无法查到，至少补充题目、引用日期（访问的日期），及网址等三项（若有作者，最好加上）。
关于[文献类型标志/文献载体标志]，本刊推荐为[EB/OL]。 
  比如：
    [1] 萧钰. 出版业信息化迈入快车道[EB/OL]. [2002-04-15]. http:∥www.creader.com/news/200112190019. htm.

**Comment by zepinglee** [comment]
OK，我晚上处理一下。

顺便问下你们不用 LaTeX 模板吗？

**Comment by zepinglee** [comment]
在 c43b7d2 中添加。

**Comment by zhengyidandawn** [comment]
感谢回复与增加样式！（以及目前还在纠结最后用latex模板还是干脆用word，latex用得不太熟练）

**Comment by zepinglee** [comment]
> 感谢回复与增加样式！

还有有什么问题的话欢迎及时反馈。

（以及目前还在纠结最后用latex模板还是干脆用word，latex用得不太熟练）

那个 latex 模板是我写的。
