### ISSUE TITLE
新样式：GB/T7714-2015 (顺序编码，双语，姓名不大写，全部作者)

### ISSUE THREAD

**Issue by LXSKING** [zotero-chinese/styles#345]
### 期刊 / 学校名称

GB/T7714-2015 (顺序编码，双语，姓名不大写，全部作者)

### 英文名称

GB/T7714-2015 (顺序编码，双语，姓名不大写，全部作者)

### 相关领域

None

### 参考文献格式

官方网页链接：

官方文件链接：

上传格式文件：

格式参考：
GB/T7714-2015 (顺序编码，双语，姓名不大写，全部作者)

### 文件号

- 参考文献格式的更新日期：
- （学校）文件号：
- （期刊）ISSN 号：

### 相近样式

相近样式：

区别：

### 条目信息

```json
{}
```

**Comment by zepinglee** [comment]
在 1ac896b 中添加。这是哪个期刊/学校的格式吗？

**Comment by LXSKING** [comment]
您好，感谢您的回复。此格式并非学校要求，而是在基金申报中要求的格式，特别是国自然申报时要求列出所有作者姓名。 
希望能出两个样式 
1. GB/T7714-2015 (顺序编码，双语，姓名不大写，全部作者) 
2.GB/T7714-2015 (顺序编码，双语，姓名不大写，全部作者（全拼，非缩写））
Xu-Sheng Liu
Researcher
***@***.***
Taihe Hospital
Hubei University of Medicine
---- 回复的原邮件 ----
发件人Zeping ***@***.***>发送日期2024年08月01日 09:22 ***@***.***> ***@***.***>,
***@***.***>主题Re: [zotero-chinese/styles] 新样式：GB/T7714-2015 (顺序编码，双语，姓名不大写，全部作者) (Issue #345)
在 1ac896b 中添加。这是哪个期刊/学校的格式吗？

**Comment by zepinglee** [comment]
>  2. GB/T7714-2015 (顺序编码，双语，姓名不大写，全部作者（全拼，非缩写）） Xu-Sheng Liu

都是按照名前姓后的格式？

**Comment by LXSKING** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    您好，为了更好的向您解释，我写下了这个格式的内容供您参考学术成果 格式Liu, Xu-Sheng; Zhang, Yu; Liu, Zi-Yue; Gao, Yan; Yuan, Ling-Ling; Zeng, Dao-Bing; Tan, Fan; Wan, Hua-Bing; Pei, Zhi-Jun, METTL3 as a novel diagnosis and treatment biomarker and its association with glycolysis, cuproptosis and ceRNA in oesophageal carcinoma[J], JOURNAL OF CELLULAR AND MOLECULAR MEDICINE, 2024, 28(6): e18195. doi: 10.1111/jcmm.18195.
        
    
    
        
            
        
    
    
      
    
        
            
    
        
            
                    
                        
                    
                    
                        Xu-Sheng Liu
                            Researcher
                    
            
                
                    
                            ***@***.***
                            Taihe Hospital
                            Hubei University of Medicine
                    
                
        
    

        
    
 
    

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            Zeping ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2024年08月1日 09:41
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [zotero-chinese/styles] 新样式：GB/T7714-2015 (顺序编码，双语，姓名不大写，全部作者) (Issue #345)
        
      
    
  
  


GB/T7714-2015 (顺序编码，双语，姓名不大写，全部作者（全拼，非缩写）） Xu-Sheng Liu


都是按照名前姓后的格式？

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by zepinglee** [comment]
除了姓名格式，这个格式还有以下要素与 GB/T 7714 不同。能不能提供这个格式的官方文件以及链接（按照 issue 模板），方便我一次性处理完？

1. 姓名与题名、题名与期刊名之间的分隔符是逗号；
2. 期刊名全大写；
3. 使用文章编号“e18195”替代页码；

**Comment by LXSKING** [comment]
> 除了姓名格式，这个格式还有以下要素与 GB/T 7714 不同。能不能提供这个格式的官方文件以及链接（按照 issue 模板），方便我一次性处理完？
>> _抱歉，这个没有官方文件，是在网站中可以导出https://www.scholarmate.com/psnweb/resume/resumedetail?des3ResumeId=wizQa%2B9d61k%3D_
> 1. 姓名与题名、题名与期刊名之间的分隔符是逗号；
>> _姓名与题名之间是“;”，题名与刊名之间是“,”。_
> 2. 期刊名全大写；
>> _期刊名全大写，且为斜体_
> 3. 使用文章编号“e18195”替代页码；
>> 使用文章自己的页码，这里的“e18195”是此篇文献的页码。

Liu, Xu-Sheng; Zhang, Yu; Liu, Zi-Yue; Gao, Yan; Yuan, Ling-Ling; Zeng, Dao-Bing; Tan, Fan; Wan, Hua-Bing; Pei, Zhi-Jun; METTL3 as a novel diagnosis and treatment biomarker and its association with glycolysis, cuproptosis and ceRNA in oesophageal carcinoma[J], _JOURNAL OF CELLULAR AND MOLECULAR MEDICINE_, 2024, 28(6): e18195. doi: 10.1111/jcmm.18195.

**Comment by zepinglee** [comment]
> _抱歉，这个没有官方文件，是在网站中可以导出https://www.scholarmate.com/psnweb/resume/resumedetail?des3ResumeId=wizQa%2B9d61k%3D_

或者将网页保存下来，压缩成 zip 格式传到 github。

> 而是在基金申报中要求的格式，特别是国自然申报时要求列出所有作者姓名。

相关的完整名称是什么？如果不是官方性质的样式，我们一般不会收录到仓库中。

**Comment by LXSKING** [comment]
或者是这样，依据GB/T7714-2015 (顺序编码，双语，姓名不大写，全部作者) 这个格式，仅增加显示作者姓名全拼，例Liu X S为Liu Xu-Sheng，其他不变。命名为GB/T7714-2015 (顺序编码，双语，姓名不大写，全部作者，全拼) 。这样是否可行？
Xu-Sheng Liu
Researcher
***@***.***
Taihe Hospital
Hubei University of Medicine
---- 回复的原邮件 ----
发件人Zeping ***@***.***>发送日期2024年08月01日 13:32 ***@***.***> ***@***.***>,
***@***.***>主题Re: [zotero-chinese/styles] 新样式：GB/T7714-2015 (顺序编码，双语，姓名不大写，全部作者) (Issue #345)
抱歉，这个没有官方文件，是在网站中可以导出https://www.scholarmate.com/psnweb/resume/resumedetail?des3ResumeId=wizQa%2B9d61k%3D
或者将网页保存下来，压缩成 zip 格式传到 github。
而是在基金申报中要求的格式，特别是国自然申报时要求列出所有作者姓名。
相关的完整名称是什么？如果不是官方性质的样式，我们一般不会收录到仓库中。

**Comment by northword** [comment]
据我所知，国自然并未对申报书的参考文献格式作要求，仅部分学校在校审形式审查中做出了相比于国自然更细致的的要求。

确实有部分学校要求列出全部作者，但不是国自然本身要求。

其他格式细节我就不清楚了。我通常用的 [GB/T 7714—2015（顺序编码，双语，姓名不大写，无 URL、DOI）](https://zotero-chinese.com/styles/gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi) 。

**Comment by zepinglee** [comment]
> 或者是这样，依据GB/T7714-2015 (顺序编码，双语，姓名不大写，全部作者) 这个格式，仅增加显示作者姓名全拼，例Liu X S为Liu Xu-Sheng，其他不变。命名为GB/T7714-2015 (顺序编码，双语，姓名不大写，全部作者，全拼) 。这样是否可行？ 

在 3d88092 中添加。

注意部分姓名如果写成 `Liu, Xusheng` 或者 `Liu, Xu Sheng` 的格式，需要手动在原始数据中改为使用连字符的 `Liu, Xu-Sheng`。CSL 不能自动加连字符。

**Comment by LXSKING** [comment]
> > 或者是这样，依据GB/T7714-2015 (顺序编码，双语，姓名不大写，全部作者) 这个格式，仅增加显示作者姓名全拼，例Liu X S为Liu Xu-Sheng，其他不变。命名为GB/T7714-2015 (顺序编码，双语，姓名不大写，全部作者，全拼) 。这样是否可行？
> 
> 在 [3d88092](https://github.com/zotero-chinese/styles/commit/3d880922e0876331d552898880d89e66cdeebe2d) 中添加。
> 
> 注意部分姓名如果写成 `Liu, Xusheng` 或者 `Liu, Xu Sheng` 的格式，需要手动在原始数据中改为使用连字符的 `Liu, Xu-Sheng`。CSL 不能自动加连字符。

> > 感谢，我下载使用了GB/T7714-2015 (顺序编码，双语，姓名不大写，全部作者，姓名不缩写)，基本实现了我期望的格式。再次感谢，太高效了！我文章中使用的就是这个Liu, Xu-Sheng，所以自带了连字符。

**Comment by LXSKING** [comment]
> 据我所知，国自然并未对申报书的参考文献格式作要求，仅部分学校在校审形式审查中做出了相比于国自然更细致的的要求。
> 
> 确实有部分学校要求列出全部作者，但不是国自然本身要求。
> 
> 其他格式细节我就不清楚了。我通常用的 [GB/T 7714—2015（顺序编码，双语，姓名不大写，无 URL、DOI）](https://zotero-chinese.com/styles/gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi) 。

>> 感谢回复。我知道，目前国自然申报是通过 科研之友 平台制作含有文献作品的简历，该简历中文的文献是展示了所有作者的姓名以及全拼。目前，该项目组工作人员已经帮忙制作好了我需要的格式，谢谢！
