### ISSUE TITLE
错误：经济研究csl格式有误

### ISSUE THREAD

**Issue by tyk-1999** [zotero-chinese/styles#346]
### 涉及到的样式文件

经济研究.csl

### 描述错误

Ang, J. S., C. Hsu, D. Tang, and C. Wu, 2021, “The Role of Social Media in Corporate Governance”, _ACCOUNTING REVIEW_, 96(2), 1—32.，此处期刊ACCOUNTING REVIEW,应为是为首字母大写，其他小写，即正确格式为_Accounting Review_

### 条目信息

```json
  {}
```

**Comment by northword** [comment]
此处按 Zotero 中信息原样输出，请修改 Zotero 中“刊名”字段的大小写。
