### ISSUE TITLE
错误：american-meteorological-society.csl有误

### ISSUE THREAD

**Issue by Hazuki91** [zotero-chinese/styles#351]
### 涉及到的样式文件

american-meteorological-society.csl

### 描述错误

我安装了AMS的csl，它在我的zotero上引用文献格式是：
Rayner N. A., Parker D. E., Horton E. B., Folland C. K., Alexander L. V., Rowell D. P., Kent E. C., and Kaplan A., 2003: Global analyses of sea surface temperature, sea ice, and night marine air temperature since the late nineteenth century. J. Geophys. Res., 108, 4407, https://doi.org/10.1029/2002JD002670.

预期的格式应该是：
Rayner, N. A., D. E. Parker, E. B. Horton, C. K. Folland, L. V. Alexander, D. P. Rowell, E. C. Kent, and A. Kaplan, 2003: Global analyses of sea surface temperature, sea ice, and night marine air temperature since the late nineteenth century. J. Geophys. Res., 108, 4407, https://doi.org/10.1029/2002JD002670.

第一作者的family name后应该有逗号，第二位作者开始应该先given再family。
我不确定是csl的问题还是zotero7的问题。
AMS参考文献官网的网址是：https://www.ametsoc.org/index.cfm/ams/publications/author-information/formatting-and-manuscript-components/references/

### 条目信息

```json
  {
                "id": "http://zotero.org/users/11938965/items/TUG4WS7S",
		"type": "article-journal",
		"container-title": "J. Geophys. Res.",
		"DOI": "10.1029/2002JD002670",
		"ISSN": "2156-2202",
		"issue": "D14",
		"language": "zh-CN",
		"license": "Copyright 2003 by the American Geophysical Union.",
		"note": "_eprint: https://onlinelibrary.wiley.com/doi/pdf/10.1029/2002JD002670",
		"page": "4407",
		"source": "Wiley Online Library",
		"title": "Global analyses of sea surface temperature, sea ice, and night marine air temperature since the late nineteenth century",
		"URL": "https://onlinelibrary.wiley.com/doi/abs/10.1029/2002JD002670",
		"volume": "108",
		"author": [
			{
				"family": "Rayner",
				"given": "N. A."
			},
			{
				"family": "Parker",
				"given": "D. E."
			},
			{
				"family": "Horton",
				"given": "E. B."
			},
			{
				"family": "Folland",
				"given": "C. K."
			},
			{
				"family": "Alexander",
				"given": "L. V."
			},
			{
				"family": "Rowell",
				"given": "D. P."
			},
			{
				"family": "Kent",
				"given": "E. C."
			},
			{
				"family": "Kaplan",
				"given": "A."
			}
		],
		"accessed": {
			"date-parts": [
				[
					"2024",
					8,
					13
				]
			]
		},
		"issued": {
			"date-parts": [
				[
					"2003"
				]
			]
		}
}
```

**Comment by redleafnew** [comment]
> `"language": "zh-CN",` 

修改为正确的语言

**Comment by Hazuki91** [comment]
> > `"language": "zh-CN",`
> 
> 条目语言设置得不正确，修改为正确的语言

感谢，已解决
