### ISSUE TITLE
错误：《心理学报》的csl文件的文献参考列表与官网不符，申请修改

### ISSUE THREAD

**Issue by olivia0317** [zotero-chinese/styles#352]
### 涉及到的样式文件

[Uploading acta-psychologica-sinica.csl.txt…]()

### 描述错误

问题：**《心理学报》的cls文件的参考文献列表与官网不符**。
官网要求文献列表按著者姓氏字母顺序排列（中文是混在一起的），但用CSL 官方仓库中的《心理学报》csl样式，在word里面是英文参考文献在前，中文参考文献在后。这里官网的：！[7853ac9f25d151b83cac2775b40e2b8c]（https://github.com/user-attachments/assets/72938a14-478b-4b36-951b-25464d1b7d1c）官网要求文献列表按著者姓氏字母顺序排列（中文是混在一起的），但用CSL 官方仓库中的《心理学报》csl样式，在word里面是英文参考文献在前，中文参考文献在后。

举例，以下是官网已发表期刊的样式：
*Guerra, V. S., Asher, S. R., & DeRosier, M. E. (2004). Effect of children's perceived rejection on physical aggression. Journal of Abnormal Child Psychology, 32(5), 551−563.
 *Guo, B. L., & Zhang, L. (2002). Social behavior and peer status of aggressive and victimized rural Chinese children. Chinese Journal of Clinical Psychology, 10(4), 260− 262+259. 
[郭伯良, 张雷. (2002). 不同攻击受害类型农村儿童的社交 行为和同伴关系. 中国临床心理学杂志, 10(4), 260− 262+259.]
 *Guo, F. (2016). Adolescents’ executive function and peer rejection: The mediating role of aggression (Unpublished master’s thesis). Shandong Normal University, China.

以下是用cls文件在word中导出参考文献的样式：
Yao, Z., & Enright, R. (2023). Social class and prosocial behavior in early adolescence: The moderating roles of family and school factors. Journal of Moral Education, 52(3), 310–324.
Zhu, H., Huiru, Z., Zhiwei, C., & Xiaoshan, J. (2023). The suppression effect of subjective social status and tolerance for uncertainties on the relationship between family socioeconomic status and prosocial risk taking. Children and Youth Services Review, 150, 106986.
[丁毅, 纪婷婷. (2024). 低阶层感知抑制较高客观阶层者的亲社会性. 心理科学, 47(3), 711–717.]
[刘凤芹, 卢玮静. (2013). 社会经济地位对慈善捐款行为的影响. 北京师范大学学报(社会科学版), 3, 113–120.]
[唐蕾, 刘衍玲, 杨营凯. (2022). 亲社会行为的认知过程及脑神经基础. 心理发展与教育, 38(3), 437–446.]

### 条目信息

```json
  {}
```

**Comment by northword** [comment]
看起来似乎是你的中文文献没有对应的英文译文导致的？

**Comment by olivia0317** [comment]
> 看起来是你的中文文献没有对应的英文翻译文导致的？> 看起来是你的中文文献没有对应的英文翻译文导致的？
请问在zotero的右边栏的信息加上这个英文翻译，可以解决这个问题么？我已尝试这种做，但我发现我的zotero6.0中的中文文献无法添加标题翻译（点击无反应）

**Comment by olivia0317** [comment]
很感谢您的耐心回复，中文文献的语言是选择的'zh-CN。但请问extra中的 "original-author, 'original-title, original-
container-title,original-publisher-place,original-publisher字段是在那里填写呀？

![WechatIMG579](https://github.com/user-attachments/assets/380db0e2-4b44-4c01-93fa-06acc6a9541f)

**Comment by northword** [comment]
自行录入，每行一个属性，属性和值之间是英文冒号

```
original-title: xxxxxxx
original-xxx: xxxxx
```

**Comment by olivia0317** [comment]
> 自行录入，每行一个属性，属性和值之间是英文冒号
> 
> ```
> original-title: xxxxxxx
> original-xxx: xxxxx
> ```

非常感谢，经过尝试，我发现只需在“其他”中手动填入original-author：xxxxx，就可以解决参考文献列表的中英文顺序问题。
再次感谢您的耐心解答，谢谢！
