### ISSUE TITLE
错误：英文作者只显示姓

### ISSUE THREAD

**Issue by LXSKING** [zotero-chinese/styles#355]
### 涉及到的样式文件

导出作者、刊名、年卷期页
src/export-author-journal-year-vol-issue-pages/export-author-journal-year-vol-issue-pages.csl

### 描述错误

该格式导出参考文献，英文作者只显示姓
[1] Liu et al. Scientific Reports, 2024, 14(1): 9881.
正确的应该是
[1] Liu Xu-Sheng et al. Scientific Reports, 2024, 14(1): 9881.

### 条目信息

```json
  {}
```

**Comment by zepinglee** [comment]
这个导出的格式没有具体的格式要求，你可以自己去掉 `form="short" `。

https://github.com/zotero-chinese/styles/blob/af20977801400e28a1eaf30def5ba8e795fe84c5/src/export-author-journal-year-vol-issue-pages/export-author-journal-year-vol-issue-pages.csl#L36
