### ISSUE TITLE
错误：安装 CSL 样式时发生未可预知的错误

### ISSUE THREAD

**Issue by qianmoeast** [zotero-chinese/styles#357]
### 涉及到的样式文件

lanzhou-university

### 描述错误

zotero7安装lanzhou-university格式的时候出现未知错误

### 条目信息

```json
  {}
```

**Comment by zepinglee** [comment]
将你下载的 `.csl` 文件打包成 `.zip` 格式发上来看一下。

**Comment by Huaweidev** [comment]
> 将你下载的 `.csl` 文件打包成 `.zip` 格式发上来看一下。

[01gb-t-7714-2015-numeric-no-date-url.zip](https://github.com/user-attachments/files/16848496/01gb-t-7714-2015-numeric-no-date-url.zip)
报错信息如下：安装 Zotero\CSL\01gb-t-7714-2015-numeric-no-date-url.csl”时发生未可预知的错误

**Comment by northword** [comment]
你下载了错误的文件，或下载方式错误。

从 GitHub 安装时，只需要点开链接，等待 Connector 弹出确认框，不是直接在链接上右击。只有括号注明右击另存为的才需要右击另存为。
