### ISSUE TITLE
错误：法学引注手册错误：安装 CSL 样式时发生未可预知的错误、不是有效的样式

### ISSUE THREAD

**Issue by NORACAT233** [zotero-chinese/styles#359]
### 涉及到的样式文件

几个链接保存了结果都一样

### 条目信息

```json
  {}
```

**Comment by NORACAT233** [comment]
开梯子下载后又可以安装了好奇怪

**Comment by northword** [comment]
可能：

1. 网络问题导致文件未下载完整
2. 参：https://github.com/zotero-chinese/styles/issues/357#issuecomment-2326398414
