### ISSUE TITLE
新样式：华东理工大学 - 社会与公共管理学院

### ISSUE THREAD

**Issue by user78458** [zotero-chinese/styles#360]
### 期刊 / 学校名称

华东理工大学 - 社会与公共管理学院

### 英文名称

East China University of Science and Technology - School of Social and Public Administration

### 相关领域

social_science

### 参考文献格式

官方网页链接：

官方文件链接：

[上传格式文件：
[7.社会与公共管理学院研究生学位论文撰写规范.zip](https://github.com/user-attachments/files/16920971/7.zip)

格式参考：
引用文献采取脚注方式，脚注：页面底端，编号格式1, 2, 3, …，编号：每页重新编号。脚注序号和文献之间要空1格，中文小5号宋体，英文小5号Times New Roman体，两端对齐，单倍行距。
脚注部分引用文献书写格式见2.8参考文献部分，在脚注中要求详细说明引文页码，而参考文献中页码则可忽略。
引文：1-10
脚注：
1 费孝通：《乡土中国》，北京出版社2005年版，第26-39页。
2 梁漱溟：《中国文化要义》，上海人民出版社2005年版，第176页。
3 [美]道格拉斯·C·诺斯著：《经济史中的结构与变迁》，陈郁、罗华平译，上海人民出版社1994年版，第53-54页。
4 [美]西奥多·W·舒尔茨著：《改造传统农业》，梁小民译，商务印书馆2006年版，第6-19页。
5 Scott C James. Weapons of the Weak: Everyday Forms of Peasant Resistance, New Haven and London: Yale University Press, 1985. p.165.

### 文件号

- 参考文献格式的更新日期：
- （学校）文件号：
- （期刊）ISSN 号：

### 相近样式

相近样式：
社会学研究
区别：
引注为序号脚注
且在每个页面重新计算引注
参考文献分类排列

### 条目信息

```json
{}
```

**Comment by user78458** [comment]
[学位论文格式样本.zip](https://github.com/user-attachments/files/16920983/default.zip)
学校文件中提到，依照的是GB7713-87《科学技术报告、学位论文和学术论文的编写格式》的有关规定
现在能找到的基本上都是GB7714的标准
感谢！！

**Comment by zepinglee** [comment]
请将官网链接、更新日期等内容填写完整。我们需要记录下这些信息，如果以后学校更新了格式规范，方便参考、对比。

另外这个格式比较接近《中国社会科学》或《综合性期刊文献引证技术规范》，而不是 GB/T 7714。

**Comment by user78458** [comment]
谢谢！但是目前这一版本的格式要求没有找到官网发布的链接，基本都是内部流传，我找到了一个被人上传到百度文档的格式要求链接，推测这一版本最晚更新于2022年。https://wenku.baidu.com/view/9ab6d46c5427a5e9856a561252d380eb6394231f.html?_wkts_=1725796983847&bdQuery=%E4%B8%80%E7%BA%A7%E6%A0%87%E9%A2%98%28%E7%AB%A0%29%E4%B9%8B%E9%97%B4%E4%B8%8D%E6%8E%A5%E6%8E%92%2C%E5%9C%A8%E7%BB%93%E6%9D%9F%E5%A4%84%E8%AF%B7%E4%BD%BF%E7%94%A8Ctrl%2BEnter%E5%8F%A6%E8%B5%B7%E4%B8%80%E9%A1%B5%3B%E4%B8%89%E7%BA%A7%E6%A0%87%E9%A2%98%E4%B8%8B%E5%86%85%E5%AE%B9%E7%BB%93%E6%9D%9F%E5%A4%84

**Comment by zepinglee** [comment]
在 873a8ab 中添加。

有什么问题的话可以继续在本 issue 中反馈。

**Comment by user78458** [comment]
感恩的心！！感谢！！但是学校规定了引用文献的脚注需要在每一页中重新编码，我想咨询一下这个是zotero可以设置的还是直接在word中就可以了。另外，如下方内容所示的参考文献排版是不是只能在word中手动实现，感谢！！
参考文献
一、著作类
[1]	费孝通：《乡土中国》，北京出版社2005年版。
[2]	梁漱溟：《中国文化要义》，上海人民出版社2005年版。
[3]	[美]道格拉斯·C·诺斯著：《经济史中的结构与变迁》，陈郁、罗华平译，上海人民出版社1994年版。
[4]	[美]西奥多·W·舒尔茨著：《改造传统农业》，梁小民译，商务印书馆2006年版。
[5]	Scott C James. Weapons of the Weak: Everyday Forms of Peasant Resistance, New Haven and London: Yale University Press, 1985.
[6]	Coleman J S. Foundation of Social Theory, Cambridge: Belknap Press of Harvard University Press, 1990.
二、论文类
[1]	边燕杰、张文宏：《经济体制、社会网络与职业流动》，《中国社会科学》2001年第2期。
[2]	吕卓红：《川西茶馆：作为公共空间的生成和变迁》，中央民族大学2003年博士学位论文。
[3]	Yanjie Bian. Bringing Strong Ties Back in: Indirect Connection, Bridge, and Job Search in China, American Sociological Review, 1997, (62). 
[4]	Grannovetter Mark. The Strength of Weak Ties, The American Journal of Sociology, 1973, 78(6).

三、统计资料类
[1]	中华人民共和国国家统计局编：《中国统计年鉴》(2012)，中国经济出版社2012年版。
[2]	中华人民共和国农业部政策法规司、中华人民共和国国家统计局农村司编：《中国农村40年》，中原农民出版社1989年版。

**Comment by user78458** [comment]
另外，学位论文的引用当中，好像缺少了学校年份和层级的信息。
学校给的案例当中学位论文引用的样式为：
  吕卓红：《川西茶馆：作为公共空间的生成和变迁》，中央民族大学2003年博士学位论文，第38-42页。
实际上应用于word之后学位论文引用只剩下了：
叶乔：《泥塑粉男化女性偶像的性别想象研究》，第35—36页。
--------------
：和，前的空格大小好像和学校案例的距离不太一样，我调整了一下脚注的字号，好像还是不太一样，图片在下方附上。第一篇文献为费孝通的，是学校所给的案例示意。感谢！！
<img width="563" alt="屏幕截图 2024-09-09 142122" src="https://github.com/user-attachments/assets/e27b867c-ebeb-4528-9c41-d218d37ec35e">
<img width="504" alt="屏幕截图 2024-09-09 142147" src="https://github.com/user-attachments/assets/687c248c-de42-46fd-9ebe-72698dc5372a">

**Comment by user78458** [comment]
另外，学位论文的引用当中，好像缺少了学校年份和层级的信息。
学校给的案例当中学位论文引用的样式为：
吕卓红：《川西茶馆：作为公共空间的生成和变迁》，中央民族大学2003年博士学位论文，第38-42页。
实际上应用于word之后学位论文引用只剩下了：
叶乔：《泥塑粉男化女性偶像的性别想象研究》，第35—36页。
-------------
<img width="563" alt="屏幕截图 2024-09-09 142122" src="https://github.com/user-attachments/assets/9db8c350-6230-428d-b429-31fc68a50985">
<img width="504" alt="屏幕截图 2024-09-09 142147" src="https://github.com/user-attachments/assets/c1704e54-e870-489c-9fda-50e6a5f0a5cb">

：和，前的空格大小好像和学校案例的距离不太一样，我调整了一下脚注的字号，好像还是不太一样，图片在下方附上。第一篇文献为费孝通的，是学校所给的案例示意。感谢！！

**Comment by user78458** [comment]
另外，学位论文的引用当中，好像缺少了学校年份和层级的信息。
学校给的案例当中学位论文引用的样式为：
吕卓红：《川西茶馆：作为公共空间的生成和变迁》，中央民族大学2003年博士学位论文，第38-42页。
实际上应用于word之后学位论文引用只剩下了：
叶乔：《泥塑粉男化女性偶像的性别想象研究》，第35—36页。
<img width="563" alt="屏幕截图 2024-09-09 142122" src="https://github.com/user-attachments/assets/c481026f-437f-4e76-8365-d55cedae5785">
<img width="504" alt="屏幕截图 2024-09-09 142147" src="https://github.com/user-attachments/assets/1c5a8979-96af-4a89-ad86-a751d715777f">

：和，前的空格大小好像和学校案例的距离不太一样，我调整了一下脚注的字号，好像还是不太一样，图片在下方附上。第一篇文献为费孝通的，是学校所给的案例示意。感谢！！

**Comment by user78458** [comment]
您好！在实际的使用中还发现了著作类引用缺少著作出版商与版次的情况，而翻译作品中还缺少该作品的译者。
<img width="1014" alt="屏幕截图 2024-09-11 162848" src="https://github.com/user-attachments/assets/b5acbdef-6ccf-4423-8bdb-6caa04b05d99">
辛苦了！！感谢！！！

**Comment by zepinglee** [comment]
> 感恩的心！！感谢！！但是学校规定了引用文献的脚注需要在每一页中重新编码，我想咨询一下这个是zotero可以设置的还是直接在word中就可以了。

这个是在 Word 中设置的。

> 另外，如下方内容所示的参考文献排版是不是只能在word中手动实现，感谢！！ 

目前输出的参考文献表是按这个顺序的，但需要手动插入“一、著作类”等标题，并修改编号。

> 另外，学位论文的引用当中，好像缺少了学校年份和层级的信息。 学校给的案例当中学位论文引用的样式为： 吕卓红：《川西茶馆：作为公共空间的生成和变迁》，中央民族大学2003年博士学位论文，第38-42页。 实际上应用于word之后学位论文引用只剩下了： 叶乔：《泥塑粉男化女性偶像的性别想象研究》，第35—36页。 <img alt="屏幕截图 2024-09-09 142122" width="563" src="https://private-user-images.githubusercontent.com/180815232/365534492-c481026f-437f-4e76-8365-d55cedae5785.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzMjUyMzAsIm5iZiI6MTcyNjMyNDkzMCwicGF0aCI6Ii8xODA4MTUyMzIvMzY1NTM0NDkyLWM0ODEwMjZmLTQzN2YtNGU3Ni04MzY1LWQ1NWNlZGFlNTc4NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNFQxNDQyMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03N2YyMjdkYjkyOTk2NjdhOTQzYjhjMWJmYTNhYTI0MmE5MmJhYjBjODZiNzMwYWFmNzFkYmFkMDdlZjdhZWU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Cp47yZ7KmBPGpWzbB-sbPWsCbo1fpPwpQgUGVHcb9go"> <img alt="屏幕截图 2024-09-09 142147" width="504" src="https://private-user-images.githubusercontent.com/180815232/365534504-1c5a8979-96af-4a89-ad86-a751d715777f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzMjUyMzAsIm5iZiI6MTcyNjMyNDkzMCwicGF0aCI6Ii8xODA4MTUyMzIvMzY1NTM0NTA0LTFjNWE4OTc5LTk2YWYtNGE4OS1hZDg2LWE3NTFkNzE1Nzc3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNFQxNDQyMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OWE1NGE4MDNiZmZiMGE4ZGUyYjA0MWFmMTA2OTk3NDFhODI2OGQ3YjM4ZDgwNmNjZjc3ZmJhY2U3Yjg1NWMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-a2L2isEwgRu2NL7yGgNfrbHuSr_n2IF6xY9e8VLyFc">

这个是因为《中国社会科学》要求再次引证时的项目简化（“同一文献再次引证时只需标注责任者、题名、页码，出版信息可以 省略”），但你们学校的格式似乎没有要求，我复制过来时忘记修改了。已在 58ef090 中修正。

> ：和，前的空格大小好像和学校案例的距离不太一样，我调整了一下脚注的字号，好像还是不太一样，图片在下方附上。第一篇文献为费孝通的，是学校所给的案例示意。感谢！！

这个是 Word 中的标点压缩的设置不同。CSL 只负责输出文本字符，具体的排版效果由 Word 处理。

**Comment by user78458** [comment]
谢谢！！！非常感谢！！！
