### ISSUE TITLE
错误：国科大格式，正文引用中带名

### ISSUE THREAD

**Issue by usernameCL311** [zotero-chinese/styles#362]
### 涉及到的样式文件

https://raw.githubusercontent.com/zotero-chinese/styles/main/src/university-of-chinese-academy-of-sciences-author-date/university-of-chinese-academy-of-sciences-author-date.csl](https://links.jianshu.com/go?to=https%3A%2F%2Fraw.githubusercontent.com%2Fzotero-chinese%2Fstyles%2Fmain%2Fsrc%2Funiversity-of-chinese-academy-of-sciences-author-date%2Funiversity-of-chinese-academy-of-sciences-author-date.csl

### 描述错误

在zotero样式预览里不带名，但是在word里就带上了，格式出错
![image](https://github.com/user-attachments/assets/444311fb-414c-415c-832f-8cfb7bf513e2)
格式很混乱，在一些文献里可以只显示姓，在一些文献里同时显示姓+名的第一个字母，还有一些就跟上述一样
![image](https://github.com/user-attachments/assets/b4ec1c7c-0ae2-40cd-8a19-99ee7f96e25d)
![image](https://github.com/user-attachments/assets/24605fd4-6a7f-4d96-b017-1520f61c08e3)

### 条目信息

```json
  {}
```
[导出的条目2.json](https://github.com/user-attachments/files/16922567/2.json)
[导出的条目1.json](https://github.com/user-attachments/files/16922568/1.json)
[导出的条目.json](https://github.com/user-attachments/files/16922569/default.json)

**Comment by northword** [comment]
may be: https://github.com/zotero-chinese/styles/wiki/FAQ#%E4%B8%BA%E4%BD%95%E8%91%97%E8%80%85%E5%87%BA%E7%89%88%E5%B9%B4%E5%88%B6%E4%BC%9A%E6%98%BE%E7%A4%BA%E5%A4%9A%E4%BD%99%E7%9A%84%E5%90%8D%E4%BE%8B%E5%A6%82wang-y-et-al

**Comment by usernameCL311** [comment]
按照链接所述，我的论文中应该包含歧义引用，但是我的论文中并没有上述举例中其他同姓作者QAQ，所以这仍然是个问题...

**Comment by zepinglee** [comment]
```json
		"language": "eng",
		"note": "🏷️ Animals、Humans、Mutation、Genetics, Population、Amino Acid Sequence、Gene Frequency、DNA、Biological Evolution、Nucleotides、Cytochromes、Haploidy、Mathematics",
		"page": "624-626",
		"source": "PubMed",
		"title": "Evolutionary rate at the molecular level",
		"volume": "217",
		"author": [
			{
				"family": "Kimura",
				"given": "M."
			}
		],
```

这里的 `language` 为 `eng`，不符合 Zotero 要求的“two letter [ISO language codes](http://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) followed by two letter [ISO country codes](http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) (e.g., en-US for American English, or de-DE for German)”，所以实际输出时使用样式默认的中文（zh-CN）格式，即输出姓和名。

**Comment by usernameCL311** [comment]
非常有帮助，谢谢！
