### ISSUE TITLE
错误：国科大格式，同一作者同一年份文章没有显示a,b，而是分开了

### ISSUE THREAD

**Issue by usernameCL311** [zotero-chinese/styles#363]
### 涉及到的样式文件

[https://raw.githubusercontent.com/zotero-chinese/styles/main/src/university-of-chinese-academy-of-sciences-author-date/university-of-chinese-academy-of-sciences-author-date.csl](https://links.jianshu.com/go?to=https%3A%2F%2Fraw.githubusercontent.com%2Fzotero-chinese%2Fstyles%2Fmain%2Fsrc%2Funiversity-of-chinese-academy-of-sciences-author-date%2Funiversity-of-chinese-academy-of-sciences-author-date.csl](https://raw.githubusercontent.com/zotero-chinese/styles/main/src/university-of-chinese-academy-of-sciences-author-date/university-of-chinese-academy-of-sciences-author-date.csl%5D(https://links.jianshu.com/go?to=https%3A%2F%2Fraw.githubusercontent.com%2Fzotero-chinese%2Fstyles%2Fmain%2Fsrc%2Funiversity-of-chinese-academy-of-sciences-author-date%2Funiversity-of-chinese-academy-of-sciences-author-date.csl)

### 描述错误

![image](https://github.com/user-attachments/assets/3fc872d9-3429-4d11-ab36-05135d16bc00)
在样式预览中使用正常，但是插入到word就分开了

### 条目信息

```json
  {}
```
[导出的条目1.json](https://github.com/user-attachments/files/16923241/1.json)
[导出的条目.json](https://github.com/user-attachments/files/16923242/default.json)

**Comment by zepinglee** [comment]
我在 Word 中无法复现你的问题，建议：

1. 刷新一下，即切换为别的样式，再切换为国科大的；
2. 检查有无其他的 Pond et al. 文献；
3. 将 `Simon D.W.` 改为 `Simon D. W.`；虽然国科大的样式不涉及，但是在 citeproc-js 中这两个会被当成不同的姓名，可能内部的 bug 导致错误的输出。

<img width="600" alt="Screenshot 2024-09-09 at 10 46 50" src="https://github.com/user-attachments/assets/3332e48c-0b1f-4be4-a307-cf04eb4c4997">

**Comment by usernameCL311** [comment]
将 Simon D.W. 改为 Simon D. W.；虽然国科大的样式不涉及，但是在 citeproc-js 中这两个会被当成不同的姓名，可能内部的 bug 导致错误的输出 这个方法奏效，谢谢！
