### ISSUE TITLE
新样式：海洋与湖沼

### ISSUE THREAD

**Issue by ZWZ55555** [zotero-chinese/styles#365]
### 期刊 / 学校名称

海洋与湖沼

### 英文名称

Journal of Oceanology and Limnology

### 相关领域

geography

### 参考文献格式

官方网页链接：http://qdhys.ijournal.cn/hyyhz/ch/first_menu.aspx?parent_id=2009030193027001

官方文件链接：http://qdhys.ijournal.cn/uploadfile/hyyhz/20211119/%E6%B5%B7%E6%B4%8B%E4%B8%8E%E6%B9%96%E6%B2%BC%E5%8F%82%E8%80%83%E6%96%87%E7%8C%AE%E6%A0%BC%E5%BC%8F%E6%A8%A1%E6%9D%BF-2021-11-19.pdf

上传格式文件：
[海洋与湖沼参考文献格式模板-2021-11-19.pdf](https://github.com/user-attachments/files/16938618/-2021-11-19.pdf)

格式参考：
1. 来自连续出版物（期刊）的文献： 
主要责任者, 出版年. 文献题名[文献类型标识]. 连续出版物题名, 卷(期): 页码范围. （电
子文献注明获取和访问路径） 
例如： 
汪青, 包永波, 霍礼辉, 等, 2012. 泥蚶血红蛋白基因(Tg-HbIIA)克隆、分析及免疫表达研究
[J]. 海洋与湖沼, 43(1): 88-94. 
注意：当作者超过三个时，只列举前三个，后面加, 等 
如果有合期时，用分隔号/将各期列出，如: 43(1/2/3) 
      如果没有卷号时，出版物名称后直接加(期号)，如: 海洋与湖沼(4) 

### 文件号

- 参考文献格式的更新日期：
- （学校）文件号：
- （期刊）ISSN 号：0029-814X  

### 相近样式

相近样式：GB/T 7714—2015（著者-出版年，双语）
https://zotero-chinese.com/styles/gb-t-7714-2015-author-date-bilingual

区别：
文中引用时第一作者和等中间无空格；
引用多个文献时，按年代“旧-新”排序; 如果两篇或多篇文献为同一年份，按照先英文再中文的顺序排列；如果同为英文（或中文）
文献，再按照第一作者姓氏的字母（或拼音）排序; 

### 条目信息

```json
{}
```

**Comment by zepinglee** [comment]
在 256bb54 中添加。

**Comment by zepinglee** [comment]
有个问题是，“引用多个文献按照第一作者姓氏的拼音排序”，跟“文后的参考文献表中文文献按照姓氏比划‘少-多’顺序排列” 在 CSL 中是冲突的，无法同时按照两种排序方式处理中文。考虑到前者出现的情况较少，所以舍弃前者。

**Comment by ZWZ55555** [comment]
好的，谢谢您！另外我有一点不太清楚，请问应该如何下载使用呢？src/journal-of-oceanology-and-limnology/journal-of-oceanology-and-limnology.csl这个csl文件无法跳转到下载页面

> 有个问题是，“引用多个文献按照第一作者姓氏的拼音排序”，跟“文后的参考文献表中文文献按照姓氏比划‘少-多’顺序排列” 在 CSL 中是冲突的，无法同时按照两种排序方式处理中文。考虑到前者出现的情况较少，所以舍弃前者。

**Comment by zepinglee** [comment]
> 好的，谢谢您！另外我有一点不太清楚，请问应该如何下载使用呢？src/journal-of-oceanology-and-limnology/journal-of-oceanology-and-limnology.csl这个csl文件无法跳转到下载页面。（我好像找到了，点击 更多-View file 可以下载）
> 
> > 有个问题是，“引用多个文献按照第一作者姓氏的拼音排序”，跟“文后的参考文献表中文文献按照姓氏比划‘少-多’顺序排列” 在 CSL 中是冲突的，无法同时按照两种排序方式处理中文。考虑到前者出现的情况较少，所以舍弃前者。

1. 在 <https://zotero-chinese.com/styles/journal-of-oceanology-and-limnology/> 找到“下载样式”板块。
2. GitHub 上 <https://github.com/zotero-chinese/styles/blob/main/src/journal-of-oceanology-and-limnology/journal-of-oceanology-and-limnology.csl> 右上角有“Download raw file”按钮。
<img width="303" alt="Screenshot 2024-09-14 at 23 06 15" src="https://github.com/user-attachments/assets/b51c4d45-1e23-4c4b-adf5-207cce14bbaf">

**Comment by ZWZ55555** [comment]
> > 好的，谢谢您！另外我有一点不太清楚，请问应该如何下载使用呢？src/journal-of-oceanology-and-limnology/journal-of-oceanology-and-limnology.csl这个csl文件无法跳转到下载页面。（我好像找到了，点击 更多-View file 可以下载）
> > > 有个问题是，“引用多个文献按照第一作者姓氏的拼音排序”，跟“文后的参考文献表中文文献按照姓氏比划‘少-多’顺序排列” 在 CSL 中是冲突的，无法同时按照两种排序方式处理中文。考虑到前者出现的情况较少，所以舍弃前者。
> 
>     1. 在 https://zotero-chinese.com/styles/journal-of-oceanology-and-limnology/ 找到“下载样式”板块。
> 
>     2. GitHub 上 https://github.com/zotero-chinese/styles/blob/main/src/journal-of-oceanology-and-limnology/journal-of-oceanology-and-limnology.csl 右上角有“Download raw file”按钮。
> 
> 
> <img alt="Screenshot 2024-09-14 at 23 06 15" width="303" src="https://private-user-images.githubusercontent.com/12290822/367523901-b51c4d45-1e23-4c4b-adf5-207cce14bbaf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzMjY3MzcsIm5iZiI6MTcyNjMyNjQzNywicGF0aCI6Ii8xMjI5MDgyMi8zNjc1MjM5MDEtYjUxYzRkNDUtMWUyMy00YzRiLWFkZjUtMjA3Y2NlMTRiYmFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDE1MDcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5MjY4NGU3OTYxNWMyNjdmNTFmNjg0MGJlYzgwOTg5MTVmYWI0ZTYwODViNDE3ODg2MjAyMWY2ZjY4MjAxZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.V-Zz9_pygNZCrjyiLuug6KgFUx_G_L1bj__L3prZ5nk">

好的，谢谢您！我刚刚下载测试了一下，基本能满足期刊要求，但是该期刊还要求“作者的中文姓名如果是两个字的，比如“张三”，姓和名之间空两格，即“张  三””，目前的版本中姓名之前没有空格。请问能麻烦您帮忙再改改吗？谢谢！
[《海洋与湖沼》写作规范.docx](https://github.com/user-attachments/files/17003036/default.docx)

**Comment by zepinglee** [comment]
> 好的，谢谢您！我刚刚下载测试了一下，基本能满足期刊要求，但是该期刊还要求“作者的中文姓名如果是两个字的，比如“张三”，姓和名之间空两格，即“张 三””，目前的版本中姓名之前没有空格。请问能麻烦您帮忙再改改吗？谢谢！ [《海洋与湖沼》写作规范.docx](https://github.com/user-attachments/files/17003036/default.docx)

这个在 CSL 中无法实现。

**Comment by ZWZ55555** [comment]
> > 好的，谢谢您！我刚刚下载测试了一下，基本能满足期刊要求，但是该期刊还要求“作者的中文姓名如果是两个字的，比如“张三”，姓和名之间空两格，即“张 三””，目前的版本中姓名之前没有空格。请问能麻烦您帮忙再改改吗？谢谢！ [《海洋与湖沼》写作规范.docx](https://github.com/user-attachments/files/17003036/default.docx)
> 
> 这个在 CSL 中无法实现。

好的，谢谢！
