### ISSUE TITLE
中文文献需要中英文条目同时存在时，一直没合适的csl格式文件

### ISSUE THREAD

**Issue by yypdiy** [zotero-chinese/styles#371]
### 涉及到的样式文件

中文文献需要中英文条目同时存在时，一直没合适的csl格式文件，之前下载的1个，已经是最好的了，GB/T 7714-2015 (顺序编码, 双语, 姓名取消全大写, 无 URL DOI, 增加英文翻译)，但还是有bug，就是条目后面会出现空行，其实不需要空行，需要条目连续排列下来。涉及到gb-t-7714-2015-numeric-bilingual-no-uppercase-no-url-doi.csl

### 描述错误

条目与条目之间会出现空行，其实不需要空行，需要条目连续排列下来。
![c9a99abd-b2d4-447d-a738-cab41a802b9b](https://github.com/user-attachments/assets/72fc42bb-9453-41e5-bc48-f6325feaf677)

### 条目信息

```json
  {}
```
[导出的条目.json](https://github.com/user-attachments/files/17110072/default.json)
[导出的条目.json](https://github.com/user-attachments/files/17110077/default.json)

**Comment by zepinglee** [comment]
> 中文文献需要中英文条目同时存在时，一直没合适的csl格式文件

具体哪个期刊/学校的格式？

> 之前下载的1个，已经是最好的了，GB/T 7714-2015 (顺序编码, 双语, 姓名取消全大写, 无 URL DOI, 增加英文翻译)，但还是有bug

把 `.csl` 样式发上来。

**Comment by yypdiy** [comment]
&nbsp;
&nbsp; &nbsp; 就像这种格式。我之前下载的也是你发的这个csl，bug就是2条目之间会出现空格。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zotero-chinese/styles"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月27日(星期五) 中午12:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zotero-chinese/styles] 中文文献需要中英文条目同时存在时，一直没合适的csl格式文件 (Issue #371)





  
中文文献需要中英文条目同时存在时，一直没合适的csl格式文件
  
具体哪个期刊/学校的格式？
  
之前下载的1个，已经是最好的了，GB/T 7714-2015 (顺序编码, 双语, 姓名取消全大写, 无 URL DOI, 增加英文翻译)，但还是有bug
  
把 .csl 样式发上来。

**Comment by zepinglee** [comment]
> &nbsp; &nbsp; &nbsp; 就像这种格式。我之前下载的也是你发的这个csl，bug就是2条目之间会出现空格。

通过邮件无法上传文件，需要在 GitHub 网页上传 `.csl` 文件。

**Comment by lbj-007** [comment]
我也想知道咋解决的，最近要投的《储能科学与技术》就要求这个。
![Image](https://github.com/user-attachments/assets/08948f84-a4e0-4071-8d9f-3544bc105f26)

**Comment by yypdiy** [comment]
zotero引用结束了怎么办？就是前面的引用结束了，后面再添加进去，是重新从1开始，能和前面的续上吗？我都不知道为什么出现这种情况了？后面参考文献清单也是2个了。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zotero-chinese/styles"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月29日(星期天) 下午2:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zotero-chinese/styles] 中文文献需要中英文条目同时存在时，一直没合适的csl格式文件 (Issue #371)





  
&nbsp; &nbsp; &nbsp; 就像这种格式。我之前下载的也是你发的这个csl，bug就是2条目之间会出现空格。
  
通过邮件无法上传文件，需要在 GitHub 网页上传 .csl 文件。

**Comment by yypdiy** [comment]
zotero引用结束了怎么办？就是前面的引用结束了，后面再添加进去，是重新从1开始，能和前面的续上吗？我都不知道为什么出现这种情况了？后面参考文献清单也是2个了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zotero-chinese/styles"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月23日(星期三) 晚上10:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zotero-chinese/styles] 中文文献需要中英文条目同时存在时，一直没合适的csl格式文件 (Issue #371)





 
我也想知道咋解决的，最近要投的《储能科学与技术》就要求这个。
 image.png (view on web)

**Comment by yypdiy** [comment]
zotero引用结束了怎么办？就是前面的引用结束了，后面再添加进去，是重新从1开始，能和前面的续上吗？我都不知道为什么出现这种情况了？后面参考文献清单也是2个了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zotero-chinese/styles"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月29日(星期天) 下午2:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zotero-chinese/styles] 中文文献需要中英文条目同时存在时，一直没合适的csl格式文件 (Issue #371)





  
&nbsp; &nbsp; &nbsp; 就像这种格式。我之前下载的也是你发的这个csl，bug就是2条目之间会出现空格。
  
通过邮件无法上传文件，需要在 GitHub 网页上传 .csl 文件。

**Comment by northword** [comment]
1. 不要在同一个 issue 里发起与该 issue 无关的话题
2. 不要刷屏评论相同的内容
3. 你需要确认前一引用的是否已经断开链接（将域代码转为纯文本），如果已经断开链接，你需要重新插入所有引文
4. 如果确认先前的引用没有断开链接，请在 Zotero 官方论坛打开一个错误报告的帖子。

**Comment by zepinglee** [comment]
@lbj-007 按照“申请新样式”的模板发 issue，将期刊信息填写完整。

**Comment by zepinglee** [comment]
> > 就像这种格式。我之前下载的也是你发的这个csl，bug就是2条目之间会出现空格。
> 
> 通过邮件无法上传文件，需要在 GitHub 网页上传 `.csl` 文件。

@yypdiy 如果还有问题的话，请在 GitHub 网页端上传相关的 CSL 样式继续讨论。
