### ISSUE TITLE
新样式：信息安全学报

### ISSUE THREAD

**Issue by mbs0221** [zotero-chinese/styles#372]
### 期刊 / 学校名称

信息安全学报

### 英文名称

Journal of Cyber Security

### 相关领域

engineering

### 参考文献格式

官方网页链接：https://jcs.iie.ac.cn/ch/reader/view_news.aspx?id=20160123113857030

官方文件链接：[《信息安全学报》模板](https://jcs.iie.ac.cn/uploadfile/xxaqxb/20240426/%E3%80%8A%E4%BF%A1%E6%81%AF%E5%AE%89%E5%85%A8%E5%AD%A6%E6%8A%A5%E3%80%8B%E6%A8%A1%E6%9D%BF.doc)

上传格式文件：
[《信息安全学报》模板.pdf](https://github.com/user-attachments/files/17178788/default.pdf)

### 文件号

- 参考文献格式的更新日期：
- （学校）文件号：无
- （期刊）ISSN 号：2096-1146

### 相近样式

相近样式：https://zotero-chinese.com/styles/beihang-university

区别：

1、	三个作者以上的文章，只写前三位作者，后面的用et al.代替

### Zotero ID

anders221

### 条目信息

```json
{}
```

**Comment by redleafnew** [comment]
> 三个作者以上的文章，只写前三位作者，后面的用et al.代替

现在的不是吗

**Comment by zepinglee** [comment]
@redleafnew 我正在制作这个。

**Comment by redleafnew** [comment]
好的

**Comment by zepinglee** [comment]
在 096414c 中添加。

**Comment by mbs0221** [comment]
> 在 [096414c](https://github.com/zotero-chinese/styles/commit/096414cf78ac1aee9c35f655a501ef4ed9216faf) 中添加。

感谢@zepinglee 支持！但我测试发现，参考文献前面多了一个换行。

![Image](https://github.com/user-attachments/assets/59594203-1710-4590-b5b2-7d87d57fe04e)

**Comment by zepinglee** [comment]
> 感谢[@zepinglee](https://github.com/zepinglee) 支持！但我测试发现，参考文献前面多了一个换行。

在 d464853 中修正。如果还有什么问题的话欢迎继续反馈。

**Comment by mbs0221** [comment]
感谢[@zepinglee](https://github.com/zepinglee) 支持！目前还有点小问题：

文献换行之后，左侧没有保持对齐：
![Image](https://github.com/user-attachments/assets/8f4f59ca-c3ea-44fc-a8e2-888c55d345ac)

就像下面这样，左侧是对齐的：
![Image](https://github.com/user-attachments/assets/fad26d57-8a3a-4ae5-af2b-875648ff762c)

**Comment by mbs0221** [comment]
感谢[@zepinglee](https://github.com/zepinglee) 支持！

还有一个小问题，参考文献左侧未对齐：
![Image](https://github.com/user-attachments/assets/516d1251-17be-40b6-9bb2-5cfdac8a2545)
![Image](https://github.com/user-attachments/assets/64f3aa00-b35d-4b39-80e7-a1335655eabe)

**Comment by northword** [comment]
请尝试 #404 的版本呢

**Comment by mbs0221** [comment]
可能是之前没有表述清楚，刚刚尝试了一下，文字左侧还是没有对齐。

![Image](https://github.com/user-attachments/assets/33bb1a25-a6bc-4330-a96f-50f99467fba4)

**Comment by northword** [comment]
好像 CSL 无法修改了（我不太确定），要不然就是到这种，中文和英文对齐而不是中文从行首开始：

![Image](https://github.com/user-attachments/assets/4a7ac4aa-0cd0-4ce8-a006-0d9def7e42ce)


也许可以通过调整 Word 中的制表符宽度解决吗？

**Comment by mbs0221** [comment]
> 好像 CSL 无法修改了（我不太确定），要不然就是到这种，中文和英文对齐而不是中文从行首开始：
> 
> ![Image](https://github.com/user-attachments/assets/4a7ac4aa-0cd0-4ce8-a006-0d9def7e42ce)
> 
> 也许可以通过调整 Word 中的制表符宽度解决吗？

就是这种对齐方式了。我把Word上的标尺挪了一下，第一行就可以跟下面对齐了。其他CSL也有这种对齐方式，或许可以参考。

**Comment by zepinglee** [comment]
这个需要在 Word 中设置段落格式，将悬挂缩进的距离和制表符宽度设成相同的。
