### ISSUE TITLE
新样式：世界经济与政治论坛

### ISSUE THREAD

**Issue by Gyizi** [zotero-chinese/styles#376]
### 期刊 / 学校名称

世界经济与政治论坛

### 英文名称

Forum of World Economics & Politics

### 相关领域

political_science

### 参考文献格式

官方网页链接：
http://www.jsass.org.cn/skzy/xsqk/sjjjyzz/tgxz/202004/t20200402_13224.html
官方文件链接：

上传格式文件：
[Uploading 韩国对美国“印太战略”态度演变的动因探析_凌胜利.pdf…]()

格式参考：
![Uploading image.png…]()

### 文件号

- 参考文献格式的更新日期：
- （学校）文件号：
- （期刊）ISSN 号：
[Uploading 韩国对美国“印太战略”态度演变的动因探析_凌胜利.pdf…]()

### 相近样式

相近样式：南京农业大学（人文社科类，脚注）

区别：南京农业大学（人文社科类，脚注）的作者名称为大写，而《世界经济与政治论坛》的作者名称为小写。只有这一个区别

### 条目信息

```json
{}
```

**Comment by redleafnew** [comment]
姓名首字母大写吧

**Comment by redleafnew** [comment]
https://github.com/zotero-chinese/styles/commit/0667d82aaba57f657297a4a96dbb24892cdfda25

**Comment by Gyizi** [comment]
> 姓名首字母大写吧

对是的，不过作者名称是全称的，不是只有last name。是first name last name 的格式，

**Comment by Gyizi** [comment]
像这种的
Brock F Tessman. System Structure and State Strategy: Adding Hedging to the Menu[J]. Security Studies,
2012,21(2):203-205.
Glenn H Snyder. The Security Dilemma in Alliance Politics[J]. World Politics,1984,36(4):461-495.

**Comment by Gyizi** [comment]
> [0667d82](https://github.com/zotero-chinese/styles/commit/0667d82aaba57f657297a4a96dbb24892cdfda25)

请问我需不需要重新开一个issue？

**Comment by redleafnew** [comment]
> 像这种的 Brock F Tessman. System Structure and State Strategy: Adding Hedging to the Menu[J]. Security Studies, 2012,21(2):203-205. Glenn H Snyder. The Security Dilemma in Alliance Politics[J]. World Politics,1984,36(4):461-495.

这个条目的JSON格式传上来一下

**Comment by Gyizi** [comment]
> > 像这种的 Brock F Tessman. System Structure and State Strategy: Adding Hedging to the Menu[J]. Security Studies, 2012,21(2):203-205. Glenn H Snyder. The Security Dilemma in Alliance Politics[J]. World Politics,1984,36(4):461-495.
> 
> 这个条目的JSON格式传上来一下

[
  {
    "author": "Brock F Tessman",
    "title": "System Structure and State Strategy: Adding Hedging to the Menu",
    "journal": "Security Studies",
    "year": 2012,
    "volume": 21,
    "issue": 2,
    "pages": "203-205"
  },
  {
    "author": "Glenn H Snyder",
    "title": "The Security Dilemma in Alliance Politics",
    "journal": "World Politics",
    "year": 1984,
    "volume": 36,
    "issue": 4,
    "pages": "461-495"
  }
]

**Comment by Gyizi** [comment]
网页的
{
  "author": "Ministry of Foreign Affairs of Republic of Korea",
  "title": "Joint Press Release by the United States of America and the Republic of Korea",
  "type": "EB/OL",
  "date": "2017-11-08",
  "accessed": "2024-03-24",
  "url": "https://www.korea.net/Government/Briefing-Room/Press-Releases"
}

**Comment by Gyizi** [comment]
[导出的条目.json](https://github.com/user-attachments/files/17252564/default.json)


> 这不是JSON格式吧，我导入不进去![Image](https://github.com/user-attachments/assets/04f0e05e-721d-495c-bd2d-88a9930ff88d)，右击条目，导出

是这种吗

**Comment by Gyizi** [comment]
[网页条目.json](https://github.com/user-attachments/files/17252611/default.json)
[导出的条目2.json](https://github.com/user-attachments/files/17252612/2.json)
[中文条目.json](https://github.com/user-attachments/files/17252619/default.json)

**Comment by Gyizi** [comment]
> > > 像这种的 Brock F Tessman. System Structure and State Strategy: Adding Hedging to the Menu[J]. Security Studies, 2012,21(2):203-205. Glenn H Snyder. The Security Dilemma in Alliance Politics[J]. World Politics,1984,36(4):461-495.
> > 
> > 
> > 这个条目的JSON格式传上来一下
> 
> [ { "author": "Brock F Tessman", "title": "System Structure and State Strategy: Adding Hedging to the Menu", "journal": "Security Studies", "year": 2012, "volume": 21, "issue": 2, "pages": "203-205" }, { "author": "Glenn H Snyder", "title": "The Security Dilemma in Alliance Politics", "journal": "World Politics", "year": 1984, "volume": 36, "issue": 4, "pages": "461-495" } ]

这是这两个条目的json格式
[Glenn H. Snyder.json](https://github.com/user-attachments/files/17252656/Glenn.H.Snyder.json)
[Brock F. Tessman.json](https://github.com/user-attachments/files/17252657/Brock.F.Tessman.json)

**Comment by redleafnew** [comment]
> 像这种的 Brock F Tessman. System Structure and State Strategy: Adding Hedging to the Menu[J]. Security Studies, 2012,21(2):203-205. Glenn H Snyder. The Security Dilemma in Alliance Politics[J]. World Politics,1984,36(4):461-495.

这种需要显示成什么样子的？

**Comment by Gyizi** [comment]
> > 像这种的 Brock F Tessman. System Structure and State Strategy: Adding Hedging to the Menu[J]. Security Studies, 2012,21(2):203-205. Glenn H Snyder. The Security Dilemma in Alliance Politics[J]. World Politics,1984,36(4):461-495.
> 
> 这种需要显示成什么样子的？

   您好，就是显示为这种样子，这个就是《世界经济与政治论坛》的格式。以往这种GB的格式几乎都是 Tessman, B. System Structure and State Strategy: Adding Hedging to the Menu[J]. Security Studies, 2012,21(2):203-205. 这种或者TESSMAN, B. System Structure and State Strategy: Adding Hedging to the Menu[J]. Security Studies, 2012,21(2):203-205.。所以也就是英文的名字没显示全。

**Comment by Gyizi** [comment]
> > > 像这种的 Brock F Tessman. System Structure and State Strategy: Adding Hedging to the Menu[J]. Security Studies, 2012,21(2):203-205. Glenn H Snyder. The Security Dilemma in Alliance Politics[J]. World Politics,1984,36(4):461-495.
> > 
> > 
> > 这种需要显示成什么样子的？
> 
> 您好，就是显示为这种样子，这个就是《世界经济与政治论坛》的格式。以往这种GB的格式几乎都是 Tessman, B. System Structure and State Strategy: Adding Hedging to the Menu[J]. Security Studies, 2012,21(2):203-205. 这种或者TESSMAN, B. System Structure and State Strategy: Adding Hedging to the Menu[J]. Security Studies, 2012,21(2):203-205.。所以也就是英文的名字没显示全。

脚注，双语，名字不大写（但是英文名是全的，不是只有姓氏last name而省略名字 first name），无URL（的网页有）无doi，重复引用不省略。这个和“[GB/T 7714—2015（脚注，双语，姓名不大写，无 URL、DOI，重复引用不省略）](https://zotero-chinese.com/styles/gb-t-7714-2015-note-bilingual-no-uppercase-no-url-doi-no-ibid)”是一样的，但是GB这个作者名称那里自由姓氏，名字省略了。应该是Brock F Tessman而不是Tessman, B

**Comment by redleafnew** [comment]
显示成这样？
`Brock F. Tessman．System Structure and State Strategy: Adding Hedging to the Menu［J］．Security Studies，2012，21（2）：192-231．`

**Comment by Gyizi** [comment]
> 显示成这样？ `Brock F. Tessman．System Structure and State Strategy: Adding Hedging to the Menu［J］．Security Studies，2012，21（2）：192-231．`

Brock F. Tessman是Brock F Tessman。没有“.”

**Comment by Gyizi** [comment]
> > 显示成这样？ `Brock F. Tessman．System Structure and State Strategy: Adding Hedging to the Menu［J］．Security Studies，2012，21（2）：192-231．`
> 
> Brock F. Tessman是Brock F Tessman。没有“.”

您好，如果这个点很难弄，就不弄了，正规的英语名字缩写得标个点，如果到时候编辑部那边这个要求去掉，我就手动删除就可以了。

**Comment by redleafnew** [comment]
你这个条目上作者就有点(`.`)，`Brock F.`这个条目的作者应该是经过缩写的。

**Comment by Gyizi** [comment]
> 你这个条目上作者就有点(`.`)，`Brock F.`这个条目的作者应该是经过缩写的。

嗯嗯，所以那就不管他了

**Comment by redleafnew** [comment]
其它条目是这样的。
`Felix Heiduk, Gudrun Wacker. From Asia-Pacific to Indo-Pacific: significance, implementation and challenges[EB/OL]. 2020. https://nbn-resolving.org/urn:nbn:de:0168-ssoar-69352-6.`

**Comment by Gyizi** [comment]
> 其它条目是这样的。 `Felix Heiduk, Gudrun Wacker. From Asia-Pacific to Indo-Pacific: significance, implementation and challenges[EB/OL]. 2020. https://nbn-resolving.org/urn:nbn:de:0168-ssoar-69352-6.`

嗯嗯好的，辛苦了，非常感谢，请问这些网页到时会有自动有想GB那个有发布时间和访问时间吗

**Comment by redleafnew** [comment]
什么意思？
现在就是最终显示效果。

**Comment by Gyizi** [comment]
> 什么意思？ 现在就是最终显示效果。

像国标这个，如果我的条目有这两个信息(2024-04-29)[2024-09-06]，也会放到脚注上面：Kuo M A. China’s Alternative Global Trade System[EB/OL]. (2024-04-29)[2024-09-06]. https://thediplomat.com/2024/04/chinas-alternative-global-trade-system/.

**Comment by redleafnew** [comment]
在条目中将2020改为发布时间，在访问时间中添加时间。![Image](https://github.com/user-attachments/assets/f1b002f9-742d-4cd2-82f2-1e4cc117ee65)

**Comment by Gyizi** [comment]
> 在条目中将2020改为发布时间，在访问时间中添加时间。![Image](https://github.com/user-attachments/assets/f1b002f9-742d-4cd2-82f2-1e4cc117ee65)
> 

非常感谢！

**Comment by redleafnew** [comment]
已更新

**Comment by Gyizi** [comment]
> 已更新

非常感谢，辛苦了！我也想参与zotero文献样式的创建等等，请问有什么渠道加入或者学习嘛？

**Comment by Gyizi** [comment]
您好，这个csl有问题，一添加库里面，在word插入文献，参考文献样式就显示不出来。![Image](https://github.com/user-attachments/assets/4c993d96-3ad0-4d5e-97e1-507a7dc5cebe)

**Comment by redleafnew** [comment]
https://github.com/zotero-chinese/styles?tab=readme-ov-file#%E8%B4%A1%E7%8C%AE%E6%8C%87%E5%8D%97

http://docs.citationstyles.org/en/stable/specification.html

**Comment by redleafnew** [comment]
> 您好，这个csl有问题，一添加库里面，在word插入文献，参考文献样式就显示不出来。![Image](https://github.com/user-attachments/assets/4c993d96-3ad0-4d5e-97e1-507a7dc5cebe)

Zotero中的显示吗？禁用所有插件试试。

**Comment by redleafnew** [comment]
改了个文件名，把原来的删除再试试

**Comment by redleafnew** [comment]
https://github.com/zotero-chinese/styles/tree/main/src/forum-of-world-economics-and-politics

**Comment by Gyizi** [comment]
> https://github.com/zotero-chinese/styles/tree/main/src/forum-of-world-economics-and-politics

您好，这个问题已经解决了，非常感谢。但是有一些引用的标点全角，另一些时半角。这些是什么原因？
![Image](https://github.com/user-attachments/assets/bcf66853-13ba-40b3-815b-0131cddd977a)
![Image](https://github.com/user-attachments/assets/7c0a5b86-8d12-447b-8bee-36bebf012ba1)
![Image](https://github.com/user-attachments/assets/b1756932-4cd8-4d1d-9e14-ec5b310dcba4)

**Comment by redleafnew** [comment]
具体是指哪个？应该是全角还是半角

**Comment by Gyizi** [comment]
> 具体是指哪个？应该是全角还是半角

要全半角

**Comment by Gyizi** [comment]
> 具体是指哪个？应该是全角还是半角

要全部都是半角。和GB那个一样

**Comment by redleafnew** [comment]
你可以试着修改 如 suffix="．" delimiter="．"等引号中的全角改为半角。

**Comment by Gyizi** [comment]
> 你可以试着修改 如 suffix="．" delimiter="．"等引号中的全角改为半角。

您好，我目前还是看不懂，还得麻烦您一下，真的不好意思。逗号, 中括号[] 点. 括号() 这些都需要半角。

**Comment by redleafnew** [comment]
已更新，不知道是不是全改了

**Comment by Gyizi** [comment]
> 已更新，不知道是不是全改了

非常感谢，已经全改了。真的太感谢了，辛苦了！
