### ISSUE TITLE
错误：东南大学样式，建议部分标点符号，如"[" "]" ，应当都使用英文半角，以便排版正确。目前中英文下使用不同的半全角，导致排版怪异

### ISSUE THREAD

**Issue by wrlssqi** [zotero-chinese/styles#377]
### 涉及到的样式文件

491southeast-university.csl

### 描述错误

首先感谢维护者的无私奉献！
目前，由于中英文文献下，一些标点符号使用了不同的标点（半全角），特别是方括号[]，导致生成参考文献时无法对齐。
建议，可以在中英文文献下，统一部分标点符号，至少像方括号应该都用英文半角。
![Image](https://github.com/user-attachments/assets/012d5dce-fbb4-4a00-822c-f0cb831cc0d8)

### 条目信息

```json
  {}
```

**Comment by zepinglee** [comment]
#312 中提供的这份 Word 文档中，中文文献使用的是全角方括号。

**Comment by wrlssqi** [comment]
是的，按照学校的文件是这样，但是实际写作上，大家（我大概找了十几份博士论文，几个不同学院）都是用的英文半角方括号。学校也正常接收没有什么异议。
大概是下图的样子
![Image](https://github.com/user-attachments/assets/a6835db8-88b1-4e73-8f2b-d1f63bcefce8)

实际上来说，半全角方括号混用，实在很难排版。 那个文件，我都怀疑写的老师压根没主意标点半全角的问题，可能就是输入法在中文状态下编辑，就这么敲上去了。。。。

**Comment by zepinglee** [comment]
噢原来你说的是序号的方括号呀，确实在转换时忘记修改了，已在 4990d40 中修改。

> [10] 杨保军．新闻道德论［D］：［博士学位论文］．北京：中国人民大学出版社，2012．</div>

后面“［D］：［博士学位论文］”处的方括号呢？暂时在中文文献中保留了方括号。跟学校的格式规定一致（注意 word 文档中开启了标点压缩）。

![Image](https://github.com/user-attachments/assets/623b57eb-82b7-4d8a-b877-0e2a5a3336d4)

> 大概是下图的样子 ![Image](https://github.com/user-attachments/assets/a6835db8-88b1-4e73-8f2b-d1f63bcefce8)

这里学位论文的格式“[D]；”也不符合学校的格式规定呀。

**Comment by wrlssqi** [comment]
感谢修改！

>这里学位论文的格式“[D]；”也不符合学校的格式规定呀。

按照我看过的十来篇学位论文（数量不算多），大伙在中文参考里，[D] [M] [J]等这些地方的方括号也都是用的英文半角，实际看起来也顺眼一些。这些论文能提交到知网那肯定也是通过学校的审核的，说明学校本身也没咋关心这些细节。 像是文档里要求的学位论文需要标注 [博士学位论文] [硕士学位论文]这些，但实际上我看的哪十来篇论文里面，压根没人标。。。

**Comment by zifeiyu1999** [comment]
你好，大佬，为什么同时添加两个参考文献的时候，中间没有逗号。
![Image](https://github.com/user-attachments/assets/c8a6198d-7922-4d6b-887f-e30bc9f8aca0)

**Comment by zepinglee** [comment]
> 你好，大佬，为什么同时添加两个参考文献的时候，引注中间没有逗号。 ![Image](https://github.com/user-attachments/assets/c8a6198d-7922-4d6b-887f-e30bc9f8aca0)

同 #414，在 ed94c35 中修正。
