### ISSUE TITLE
错误：不是有效的CSL1.0.2样式文件

### ISSUE THREAD

**Issue by asenlinmu** [zotero-chinese/styles#381]
### 涉及到的样式文件

tianjin-university-numberic.csl

### 描述错误

http://www.zotero.org/styles/tianjin-university-numberic
中的天津大学（顺序编码）安装提示不是有效的CSL1.0.2样式文件

### 条目信息

```json
  {}
```

**Comment by northword** [comment]
1. https://zotero-chinese.com/user-guide/citation-styles#%E6%B3%A8%E6%84%8F
2. ![Image](https://github.com/user-attachments/assets/f1e91a7d-21f5-4383-8b4e-b2962abf5dc4)

**Comment by asenlinmu** [comment]
https://github.com/zotero-chinese/styles/blob/main/src/tianjin-university-numberic/tianjin-university-numberic.csl
在zotero官网的不知道为什么

**Comment by northword** [comment]
这是正常现象，请阅读：https://zotero-chinese.com/user-guide/citation-styles#%E6%B3%A8%E6%84%8F 。
