### ISSUE TITLE
错误：西安交大参考文献格式第三个作者和“等”字之间应该有逗号

### ISSUE THREAD

**Issue by echo1115** [zotero-chinese/styles#382]
### 涉及到的样式文件

xi-an-jiaotong-university.csl

### 描述错误

根据[西安交通大学博士、硕士学位论文模板（2021版）](https://gs.xjtu.edu.cn/info/1209/7605.htm)：

> 1. 顺序编码制
> 文献中的作者不超过三位时全部列出，超过三位时，一般只列前三位，中文的后面加 “，等”字，英文的后面加 “, et al”，作者姓名之间用逗号分开。
> 外国人名一般采用姓在前，名在后的著录法，姓全写且第一个字母大写，名简写成单个大写字母且不加标点，姓和名之间空1格，如：“Metcalf S W”。也可采用名在前，姓在后的著录法，姓全写且第一个字母大写，名简写成单个大写字母且不加标点，名和姓之间空1格，如：“S W Metcalf”。
> 中文人名的英文表达方式：
> 简写时，采用姓在前，名在后的著录法，姓全写且第一个字母大写，名简写成单个大写字母且不加标点，如，“钱学森”，简写为“Qian XS”。
> 全拼时，名在前，姓在后的著录法，名的第一个字母大写，名连写，名后空1格写姓，姓的第一个字母大写。如，“钱学森”，写为“Xuesen Qian”。
> 文后参考文献著录格式范例样板，采用五号。
> 

后面模板（[西安交通大学博士、硕士学位论文模板（2021版）](https://gs.xjtu.edu.cn/info/1209/7605.htm)）中自己忘记加逗号：

> [9]	高义民，张凤华，邢建东等．颗粒增强不锈钢基复合材料冲蚀磨损性能研究［J］．西安交通大学学报，2001，35(7)：727-730．

_**给学生产生了误导！！**_

麻烦作者修正，或者添加一个“等”字之前有中文逗号的版本！

谢谢！

**Comment by zepinglee** [comment]
我倾向于加逗号，因为原 GB/T 7714 是有逗号的。cc 样式原作者 @pencilheart 

在 ec25c25 中修改。

> *给学生产生了误导！！*

吐槽请发给你们研究生院。这里是公益社区，大家一起协作维护的。你又没赞助过钱，不要在这里颐指气使。

**Comment by echo1115** [comment]
我吐槽的就是研究院呀，他们发的文件内容前后不一致给学生产生了误导.

**Comment by zepinglee** [comment]
> 我吐槽的就是研究院呀，他们发的文件内容前后不一致给学生产生了误导.
> 
> 感谢修改

不好意思，我理解错了。
