### ISSUE TITLE
错误：中南林业科技大学样式错误

### ISSUE THREAD

**Issue by shinepreventer** [zotero-chinese/styles#385]
### 涉及到的样式文件

central-south-university-of-forestry-and-technology.csl

### 描述错误

[1]	戴廷波, 曹卫星, 荆奇. 氮形态对不同小麦基因型氮素吸收和光合作用的影响[Z]. 见: 应用生态学报[M]. 2001: 849-852.
[2]	贺纪正, 沈菊培, 张丽梅. 土壤硝化作用的新机理——氨氧化古菌在酸性土壤氨氧化中的主导作用[Z]. 见: 科学观察: 卷 1[M]. 2012: 58-60.

不应该出现：
见: 应用生态学报
见: 科学观察: 卷 1

以下部分有问题：
![Image](https://github.com/user-attachments/assets/f8b20de9-382f-4041-9ac2-1d1fbb732ae3)

### 条目信息

```json
  {}
```

**Comment by shinepreventer** [comment]
<terms>
      <term name="edition" form="short">版</term>
      <term name="in">见</term>
      <term name="patent">专利</term>
      <term name="open-quote">“</term>
      <term name="close-quote">”</term>
      <term name="open-inner-quote">‘</term>
      <term name="close-inner-quote">’</term>
      <term name="editor" form="short">主编</term>
    </terms>
  </locale>

**Comment by zepinglee** [comment]
将相关的文献条目道出为 CSL-JSON 格式贴上来。

大概率是 `extra` 中有 `Type: xxx` 的信息。

**Comment by shinepreventer** [comment]
感谢提醒，我的extra中被插件自动添加了字段导致了这个问题删掉就没有了
