### ISSUE TITLE
错误：物理学报，博士参考文献引用错误

### ISSUE THREAD

**Issue by Ying-Zi66** [zotero-chinese/styles#393]
### 涉及到的样式文件

src/acta-physica-sinica/acta-physica-sinica.csl

### 描述错误

[硕/博论文] 作者姓名 年 论文题目 Ph.D. Dissertation/ M.S. Dissertation ( 城市名: 单位名)
[8] Yang K H 2001 Ph. D. Dissertation （Beijing: Peking University） (in Chinese)  [杨凯华 2001 博士学位论文 (北京:北京大学)]
这是物理学报官方说明，2019 Ph.D Dissertation (in Chinese) [赵法明 2019 博士 (南京航空航天大学)]，这是我引用一个博士论文的样式，英文缺少姓名，中文缺少地点，博士学位论文

### 条目信息

```json
  {}
```

**Comment by northword** [comment]
![Image](https://github.com/user-attachments/assets/557d23f9-31ac-40cc-aa68-6451b6b68a68)

自动测试条目一切正常，确认你的条目信息是完整的。

**Comment by Ying-Zi66** [comment]
请问博士参考引用文献中前面的英文怎么显示呢？需要在zotero李手动输入吗

**Comment by northword** [comment]
https://zotero-chinese.com/styles/acta-physica-sinica/

![Image](https://github.com/user-attachments/assets/8c3f6712-0b54-44d8-9db1-06eeee3a463a)

**Comment by Ying-Zi66** [comment]
我用的是中文版本zotero，请问’extra‘在哪里？
`extra` 中的 `original-author`, `original-title`, `original-container-title-short`, `original-publisher-place`, `original-publisher` 字段。

**Comment by northword** [comment]
https://github.com/zotero-chinese/styles/issues/352#issuecomment-2293521613

**Comment by Ying-Zi66** [comment]
请问参考文献列表里45中图书的页数如何搞？第几页或者某些页如何引用

**Comment by Ying-Zi66** [comment]
太强大了，佬，十分感谢，收我一拜

**Comment by Ying-Zi66** [comment]
不对啊，我用了定位符，页数那一栏填写“451-453”，参考文献还是没有更新页码，并且中文图书我更新了英文的作者、标题、出版社、地址，参考文献没有英文的，请问这个如何解决呢？

**Comment by Ying-Zi66** [comment]
页码需要在图书章节里，页码填写，我填写83-128，只会出现83，-128不会出现，终止页码没有，这个如何解决呢？

**Comment by Ying-Zi66** [comment]
图书章节页码已经解决，请问中文的会议论文，英文会议名称在extra里如何写呢

**Comment by northword** [comment]
original-conference-name ？

**Comment by Ying-Zi66** [comment]
没有成功显示，作者源代码里没有original-conference，可能是没有考虑中文会议的英文格式

**Comment by zepinglee** [comment]
> 不对啊，我用了定位符，页数那一栏填写“451-453”，参考文献还是没有更新页码，并且中文图书我更新了英文的作者、标题、出版社、地址，参考文献没有英文的，请问这个如何解决呢？

请将相关的文献导出为 CSL-JSON 格式并贴上来，方便定位问题。否则只能靠猜。

**Comment by zepinglee** [comment]
> 页码需要在图书章节里，页码填写，我填写83-128，只会出现83，-128不会出现，终止页码没有，这个如何解决呢？

因为《〈物理学报〉投稿须知》中要求的是“起始页码”，不是“起止页码”。

![Image](https://github.com/user-attachments/assets/816d787d-0741-40e9-9263-c5b57e07b8a2)

**Comment by zepinglee** [comment]
> 图书章节页码已经解决，请问中文的会议论文，英文会议名称在extra里如何写呢

将会议论文集题名（通常为 Proceedings of ...）填写到 `original-container-title`。
