### ISSUE TITLE
关于正文中引用序号的字号大小

### ISSUE THREAD

**Issue by dltsam** [zotero-chinese/styles#399]
![Image](https://github.com/user-attachments/assets/b9cb9e44-18dd-464f-baa2-ba8cd045ca6b)
根据 #286 和 [广东工业大学研究生学位论文撰写规范（2023年9月）.docx](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/14872337/2023.9.docx) 
正文为小四号而正文中的引用字号为小五，请问csl是否可以修改正文上标的字号，如果不行请问如何解决比较合适？

**Comment by redleafnew** [comment]
不能，可以尝试用Word的样式

**Comment by dltsam** [comment]
> 不能，可以尝试用Word的样式

好的谢谢
