### ISSUE TITLE
某些会议论文的参考文献信息显示不全

### ISSUE THREAD

**Issue by wang2028** [zotero-chinese/styles#4]
例如这篇文章： TinyLink 2.0: integrating device, cloud, and client development for IoT applications

使用包括 1gb-t-7714-2015-numeric-no-date-url.csl 在内的多个样式导出时，均会出现 **末尾两个“点”**，两个点之间没有显示出的内容应该是年份、页码等：
[1] Guan G, Li B, Gao Y, 等. TinyLink 2.0: integrating device, cloud, and client development for IoT applications[C]//Proceedings of the 26th Annual International Conference on Mobile Computing and Networking. .

使用谷歌学术直接导出的结果是：
Guan G, Li B, Gao Y, et al. TinyLink 2.0: integrating device, cloud, and client development for IoT applications[C]//Proceedings of the 26th Annual International Conference on Mobile Computing and Networking. 2020: 1-13.

可以看到谷歌输出的GB/T格式的末尾内容是正常的。
这个情况有出现在我参考文献中大约一半的会议论文中，并不是所有会议论文都这样。（我试了试，使用Zotero官方的GB/T输出和谷歌一样，没有问题，但官方的样式的作者名称是大写的，所以我没有用官方的）
希望作者能解决一下，感谢作者的贡献~

**Comment by redleafnew** [comment]
麻烦你把这个文献导出发给我测试一下吧（Zotero能导入的格式都可以）。另外，哪个csl最接近你的需要，最终你想得到的格式是什么样子的？

**Comment by Zen-w** [comment]
我是直接谷歌学术搜索这篇文章，然后用浏览器中的Zotero插件导入的，
谷歌学术链接：
https://scholar.google.com/scholar?q=TinyLink+2.0:+integrating+device,+cloud,+and+client+development+for+IoT+applications&hl=zh-CN&as_sdt=0,5
直接点进去链接，然后用zotero插件导入后，再生成的引文目录就是末尾有两个点的那个。

目前的 1gb-t-7714-2015-numeric-no-date-url.csl 的结果可以基本满足我的需求，也就是下图这个：
![image](https://user-images.githubusercontent.com/24369380/111429390-e6c9d180-8733-11eb-8ae6-243ab479307d.png)
但有两个小问题：
1. 上述的关于会议型论文的问题；
2. 对“网页”型的文献，如何导出 [OL]，也就是类似于这种的：
    [1]  工业和信息化部. “5G+工业互联网”512工程推进方案[OL]．http://www.cac.gov.cn/2019-11/24/c_1576133540276534.htm. 
    目前在zotero中把文献设置为“网页”类型，导出的是：
    [1] 工业和信息化部. “5G+工业互联网”512工程推进方案[EB](2019).

**Comment by Zen-w** [comment]
这是导出的 .bib 文件：

@inproceedings{guan_tinylink_2020,
	title = {{TinyLink} 2.0: integrating device, cloud, and client development for {IoT} applications},
	shorttitle = {{TinyLink} 2.0},
	booktitle = {Proceedings of the 26th {Annual} {International} {Conference} on {Mobile} {Computing} and {Networking}},
	author = {Guan, Gaoyang and Li, Borui and Gao, Yi and Zhang, Yuxuan and Bu, Jiajun and Dong, Wei},
	year = {2020},
	pages = {1--13},
	file = {Snapshot:C\:\\Users\\wangxw\\Zotero\\storage\\7HGTL8RQ\\3372224.html:text/html}
}

**Comment by redleafnew** [comment]
网页类型的你也发一下吧。

**Comment by Zen-w** [comment]
这是网页文献的 .bib，这个文献应该是我手动在zotero中创建的：

@misc{_5g512_2019,
	title = {“{5G}+工业互联网”512工程推进方案},
	url = {http://www.cac.gov.cn/2019-11/24/c_1576133540276534.htm},
	author = {工业和信息化部},
	year = {2019}
}

**Comment by redleafnew** [comment]
这个我导入是一本书

**Comment by redleafnew** [comment]
另外，是否所有会议论文、网页都是这样显示？

**Comment by Zen-w** [comment]
关于这个网页：
这个网页型文献是我手动在zotero创建的，手动把“条目类型”改为“网页”了，可能导出的 bib 类型不太准；
几乎所有网页导出的reference都是 [EB] 而不是 [OL]。
我使用官方的 GB/T 的样式导出后可以显示出 [OL]，但显示的日期有点多余，如下图：
![image](https://user-images.githubusercontent.com/24369380/111432715-56da5680-8738-11eb-937e-fa07eadad070.png)


关于这个会议论文：
大约一半的会议论文是有这个问题的。
但我使用zotero官方的 GB/T 的样式导出后是没有这个问题的（也就是末尾的年份和页码能够正常显示），我用的官方的是下面这个：
![image](https://user-images.githubusercontent.com/24369380/111432629-3ad6b500-8738-11eb-86af-c8272ddf0efc.png)

**Comment by Zen-w** [comment]
但是官方的作者名是大写的，且包含了日期，这两点不太好，所以我最终没采用官方的

**Comment by redleafnew** [comment]
包含日期是GB的要求

**Comment by redleafnew** [comment]
会议论文调整结果：
[1] Guan G, Li B, Gao Y, et al. TinyLink 2.0: integrating device, cloud, and client development for IoT applications[C]//Proceedings of the 26th Annual International Conference on Mobile Computing and Networking. 2020: 1–13.

**Comment by redleafnew** [comment]
[1] Guan G, Li B, Gao Y, et al. TinyLink 2.0: integrating device, cloud, and client development for IoT applications[C]//Proceedings of the 26th Annual International Conference on Mobile Computing and Networking. 2020: 1–13.	
[2] 工业和信息化部. “5G+工业互联网”512工程推进方案[OL].(2019). http://www.cac.gov.cn/2019-11/24/c_1576133540276534.htm.
看看是否符合要求，可以的话我上传csl

**Comment by Zen-w** [comment]
可以！棒！

**Comment by redleafnew** [comment]
已更新

**Comment by Zen-w** [comment]
谢谢~

**Comment by ranck626** [comment]
请问更新在什么地方了呢？

**Comment by northword** [comment]
@ranck626 请勿在关闭很多年的 issue 里继续添加评论，这样可能会打扰到很多人。如果有需要反馈的，请打开新的 issue。

更新后的 CSL 文件都在本仓库中，你可以在 src 目录自行获取。

同时，仓库主页的描述中也提到了如何获取样式文件，见 https://github.com/zotero-chinese/styles#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8
