### ISSUE TITLE
错误：人民出版社CSL样式对仅对部分条目有效，其他条目显示为错误样式

### ISSUE THREAD

**Issue by LitchiRuirui** [zotero-chinese/styles#402]
### 涉及到的样式文件

src/peoples-publishing-house/peoples-publishing-house.csl

### 描述错误

对于不同的条目，同样都选择人民出版社的引用格式，出来的效果却有的正确有的错误。![Image](https://github.com/user-attachments/assets/33753ddc-c424-4c65-aca2-088496f5e3d5)
![Image](https://github.com/user-attachments/assets/d5f4bf69-42ca-48be-a0fb-6c050a815cbd)![Image](https://github.com/user-attachments/assets/2f267231-3e1d-4e5d-b3c1-b5d356428b23)
![Image](https://github.com/user-attachments/assets/bc976dcd-c117-47a5-8c57-93e989136935)

### 条目信息

```json
  {}
```

**Comment by northword** [comment]
1. 请提供条目信息，当条目类型一致，有正确的就证明 CSL 没有问题，你需要检查条目信息。
2. 阅读以下说明 
  - https://github.com/zotero-chinese/styles?tab=readme-ov-file#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9
  - https://zotero-chinese.com/user-guide/faqs/word-addon#%E4%B8%AD%E8%8B%B1%E6%96%87%E6%B7%B7%E6%8E%92
  - https://github.com/zotero-chinese/styles/wiki/FAQ#%E4%B8%BA%E4%BD%95%E8%8B%B1%E6%96%87%E6%96%87%E7%8C%AE%E4%BC%9A%E6%98%BE%E7%A4%BA%E4%B8%AD%E6%96%87%E7%AD%89%E5%8D%B7%E8%80%8C%E4%B8%8D%E6%98%AFet-al-vol

**Comment by LitchiRuirui** [comment]
我比较了一下，似乎是条目信息中语言的问题，语言为“zh-CN”时，就显示正确效果，语言显示为“中文”的时候，就是错误效果。请问是否所有中文csl样式都需要语言在zh-CN的情况下才能正常运行？有没有办法批量修改所有条目信息中的“语言”这一项呢？感谢！

**Comment by northword** [comment]
请认真阅读给出的链接：

> https://zotero-chinese.com/user-guide/faqs/word-addon#%E4%B8%AD%E8%8B%B1%E6%96%87%E6%B7%B7%E6%8E%92

![Image](https://github.com/user-attachments/assets/12109f90-0b70-4b2f-80c8-ffb5aa1f1ede)
