### ISSUE TITLE
新样式：华南农业大学本科毕业论文（设计）撰写规范修订

### ISSUE THREAD

**Issue by Chung-JH** [zotero-chinese/styles#413]
### 期刊 / 学校名称

华南农业大学本科毕业论文（设计）

### 英文名称

South China Agricultural University

### 相关领域

None

### 参考文献格式

官方网页链接：https://jwc.scau.edu.cn/2024/1126/c5113a393788/page.htm

官方文件链接：https://jwc.scau.edu.cn/_upload/article/files/c1/4e/d47cac4e428d8f608f6eee28854a/6b81726d-e94b-4074-a1ed-493b380a2061.rar

上传格式文件：

格式参考：[附件1-5.华南农业大学本科毕业论文（设计）撰写规范（封面模板、原创性声明及使用授权声明、正文结构参考样式、参考文献著录规则、评分参考标准）.pdf](https://github.com/user-attachments/files/18019064/1-5.pdf)

### 文件号

- 参考文献格式的更新日期：2024年7月18日
- （学校）文件号：[华南农办〔2024〕56号]
- （期刊）ISSN 号：

### 相近样式

相近样式：https://zotero-chinese.com/styles/south-china-agricultural-university-undergraduate/

区别：

### 条目信息

```json
{}
```

**Comment by zepinglee** [comment]
在 [02443b8](https://github.com/zotero-chinese/styles/commit/02443b8f9f2c0309a7e50a017db8d4332a3ac27f) 更新。

另外有两个问题：

一、引注中的括号是全角吗？

![Image](https://github.com/user-attachments/assets/3b6e9cbc-ef04-494a-882f-cc16ac063a9b)

二、GB/T 7714—2015 第 9.2 节的规定的参考文献表格式中，年份是紧跟在著者姓名后的，而不是像你们学校一样在出版者后。建议向你们学校老师反馈一下。

![Image](https://github.com/user-attachments/assets/66fb231f-f736-43dd-8962-649a0ebfcb03)

![Image](https://github.com/user-attachments/assets/02409938-b110-42f3-87c4-238c750cefc1)

**Comment by 0671Zhong** [comment]
一、这里引注中的圆括号用中文状态；括号内标点用英文状态，逗号、分号后面应有一个半角空格。
二、了解了，这个也是学校文件规定的格式。
十分感谢！
