### ISSUE TITLE
新样式：西安电子科技大学研究生学位论文

### ISSUE THREAD

**Issue by ADaJiDaLi** [zotero-chinese/styles#415]
### 期刊 / 学校名称

西安电子科技大学研究生学位论文

### 英文名称

Xidian University

### 相关领域

None

### 参考文献格式

官方网页链接：https://gr.xidian.edu.cn/info/1047/5086.htm or https://gr.xidian.edu.cn/info/1047/5087.htm

官方文件链接：https://gr.xidian.edu.cn/info/1047/5086.htm 倒数第二个附件

上传格式文件：
[1、西安电子科技大学研究生学位论文模板（2015年版）-2022.11修订.docx](https://github.com/user-attachments/files/18046144/1.2015.-2022.11.docx)
[1、西安电子科技大学研究生学位论文模板（2015年版）-2022.11修订.pdf](https://github.com/user-attachments/files/18046149/1.2015.-2022.11.pdf)

格式参考：
参考文献的著录要符合《文后参考文献著录规则》（GB/T7714-2005）要求

### 文件号

- 参考文献格式的更新日期：2024.4
- （学校）文件号：未找到
- （期刊）ISSN 号：

### 相近样式

相近样式：Xidian University Ungergraduate

区别：![Image](https://github.com/user-attachments/assets/a07562af-5745-4d19-87a9-a5905d219595)
本科与研究生论文参考格式不同，研究生英文期刊作者需要名字大写，本科生只需要首字母大写
本科生参照GB/T 7714-2015 研究生参照 GB/T7714-2005

### 条目信息

```json
{}
```

**Comment by redleafnew** [comment]
> 本科与研究生论文参考格式不同，研究生英文期刊作者需要名字大写，本科生只需要首字母大写

仅有这一个区别吗？

**Comment by zepinglee** [comment]
在 [dbbd9b3](https://github.com/zotero-chinese/styles/commit/dbbd9b3a31c92a8464cc47aa8df4cc160be57ad4) 中添加。

> 本科与研究生论文参考格式不同，研究生英文期刊作者需要名字大写，本科生只需要首字母大写
> 本科生参照GB/T 7714-2015 研究生参照 GB/T7714-2005

我制作的是研究生的 CSL 样式，其中似乎没有提到本科生吧？

**Comment by ADaJiDaLi** [comment]
是的，这是研究生的格式，没有本科生

**Comment by ADaJiDaLi** [comment]
> > 本科与研究生论文参考格式不同，研究生英文期刊作者需要名字大写，本科生只需要首字母大写
> 
> 仅有这一个区别吗？

我看只有这个区别，等发现问题再提吧！
