### ISSUE TITLE
新样式：金融评论

### ISSUE THREAD

**Issue by wahayiyaka** [zotero-chinese/styles#423]
### 期刊 / 学校名称

金融评论

### 英文名称

Chinese Review of Financial Studies

### 相关领域

social_science

### 参考文献格式

官方网页链接：https://mp.weixin.qq.com/s/ojm3BFLHQKY4E_OJEag6Ew

官方文件链接：https://mp.weixin.qq.com/s/ojm3BFLHQKY4E_OJEag6Ew

上传格式文件：![Image](https://github.com/user-attachments/assets/d92b28a0-05b4-4ae9-8664-37a1be7f557a)

格式参考：

格式示例：期刊论文

何平（2021）：《货币形态演进的中国经验与未来走向》，《金融评论》，第1期。

Li, Z., K. Ye, C. Zeng and B. Zhang (1987): “Ending at the Wrong Time: The Financial Reporting Consequences of a Uniform Fiscal Year-End”, Accounting Review, 98, 367-396.

格式示例：网络发表

闵峰、吴宝辉、文凤华（2023）：《股权溢价的驱动因素和传导机制研究：基于中国股票市场的证据》，《系统工程理论与实践》，2023年1月16日。

McNerney, J., C. Savoie, F. Caravelli, V. Carvalho and J. Farmer (2022): “How Production Networks Amplify Economic Growth”, Proceedings of the National Academy of Sciences, 119, e2106031118.

格式示例：图书

李建军等（2023）：《“一带一路”沿线基础设施投资问题研究》，中国财政经济出版社。

Reinhart, C. and K. Rogoff (2009): This Time is Different: Eight Centuries of Financial Folly, Princeton University Press.

UNCTAD (2021): Digital Economy Report 2021: Cross-border Data Flows and Development: For Whom the Data Flow, United Nations Publication.

格式示例：图书或报告的选节

胡滨、范云朋（2023）：《问题金融机构处置：理论逻辑、国际经验与政策建议》，载于《中国金融监管报告（2023）》（胡滨主编），社会科学文献出版社。

Eichengreen, B. (2013): “International Policy Coordination: The Long View”, In: Feenstra R. and A. Taylor, Globalization in an Age of Crisis: Multilateral Economic Cooperation in the Twenty-First Century, University of Chicago Press.

格式示例：公开发表的工作论文（市场报告）

徐忠、邹传伟（2018）：《区块链能做什么、不能做什么？》，中国人民银行工作论文，第4号。

Fang, H., J. Wu, R. Zhang and L. Zhou (2022): “Understanding the Resurgence of the SOEs in China: Evidence from the Real Estate Sector”, National Bureau of Economic Research Working Paper, No.29688.

McKinsey & Company (2022): “The McKinsey 2022 Global Payments Report”, Available at: https://www.mckinsey.com/~/media/mckinsey/industries/financial%20services/our%20insights/the%202022%20mckinsey%20globa1%20payments%20report/the-2022-mckinsey-global-payments-report.pdf

格式示例：会议论文（讲话）

易纲（2022）：《易纲行长在2022金融街论坛年会开幕式上的讲话》，2022金融街论坛年会开幕式上的讲话，2022年11月21日。

陈道富（2023）：《三个视角观察金融产业科技的良性循环》，首届中国金融学论坛，2023年5月20日。

Antill, S. and C. Clayton (2023): “Crisis Interventions in Corporate Insolvency”, 2023 AFA Annual Meeting.

Borio, C. (2019): “A Tale of Two Financial Cycles: Domestic and Global”, Lecture at the University of Zürich. Retrieved from https://www. bis. org/speeches/sp191119a. pdf

格式示例：专利、技术文件

European Parliament (2018): “Fair Taxation of the Digital Economy”, Technical Document, Brussels.

### 文件号

- 参考文献格式的更新日期：
- （学校）文件号：
- （期刊）ISSN 号：1674-7690

### 相近样式

相近样式：

区别：

### 条目信息

```json
{}
```

**Comment by zepinglee** [comment]
在 d0a876f 中添加。

还有个问题是，作者数量达到多少时省略为「等」？

<img width="719" alt="Image" src="https://github.com/user-attachments/assets/62b3c8c3-4ac8-4aa6-9e7a-5a6cdd3e1ddf" />

**Comment by wahayiyaka** [comment]
> 在 [d0a876f](https://github.com/zotero-chinese/styles/commit/d0a876f534a8af574828dcf5519ae71d9044b54a) 中添加。
> 
> 还有个问题是，作者数量达到多少时省略为「等」？
> 
> <img alt="Image" width="719" src="https://private-user-images.githubusercontent.com/12290822/398562568-62b3c8c3-4ac8-4aa6-9e7a-5a6cdd3e1ddf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxODU0NzMsIm5iZiI6MTczNTE4NTE3MywicGF0aCI6Ii8xMjI5MDgyMi8zOTg1NjI1NjgtNjJiM2M4YzMtNGFjOC00YWE2LTllN2EtNWE2Y2RkM2UxZGRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDAzNTI1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1ZDE0N2VkNjZjMDZjY2ZjYjk5MWZjNTM0MTc4MDUyMTk3NmZlNDhjNWRkMzdhN2ExYTE0MjFiZjNiMmRjY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.asMVfmsaC6w5va70ETV0PiU1AgSubkOvCrWn_MMQloY">

需要列示所有作者
![Image](https://github.com/user-attachments/assets/83243092-0264-42eb-a734-27d94b0e7e29)

**Comment by zepinglee** [comment]
> 需要列示所有作者 ![Image](https://github.com/user-attachments/assets/83243092-0264-42eb-a734-27d94b0e7e29)

噢原来在这个图片中说明的。目前就是显示全部作者的，不需要修改了。
