### ISSUE TITLE
待办事项（VuePress 方案）

### ISSUE THREAD

**Issue by northword** [zotero-chinese/styles#6]
进度搬过来方便勾选和讨论，只一点点似乎不必要用 Projects 。

- [x] `cs:info` 提取
  - [x] 基本的标题、分类、说明等信息
  - [ ] 作者、更新时间等信息
  - [ ] ⭐`cs:category` 中英文映射
- [x] 样式预览
- [x] ⭐`second-field-align`，`hangingindent` 选项适配
- [x] 子文件夹示例数据覆盖：子文件夹存放 `sample-data.json` 和 `sample-cite.json`
- [x] ⭐⭐⭐页面详情页添加样式安装链接和样式源文件链接：通过拼接路径和仓库产生 URL 写入 md
- [ ] 样式文件格式化
  - [ ] 将原预览文件中的简介移入 CSL 文件的 `summary` 字段，以方便脚本调用
  - [ ] 核对每条样式文件的 self_link ，应指向仓库链接
  - [x] ~~id -> uuid （optional）~~
  - [x] 去掉样式文件及其文件夹的编号前缀
  - [x] ~~`cs:category -> field` 是否需要不遵循 CSL 规范，添加 thesis（对于学位论文）、other（对于导出标题.csl）等~~
  - [x] 为需要特别适配示例数据的样式文件增加覆盖数据

- [ ] 最终合并 styles 仓库
- [ ] 确定哪些样式可以合入上游官方仓库

**Long term**

- [ ] 网页上实现多标签筛选样式 —— 目前 vuepress-theme-hope 不支持，[可以实现但将放弃服务端渲染](https://github.com/vuepress-theme-hope/vuepress-theme-hope/issues/2136)，vuepress-theme-vdoing 目前也不支持，可能可以支持。

**Comment by zepinglee** [comment]
`cs:category` 的 `field` 属性的完整列表在 <https://docs.citationstyles.org/en/stable/specification.html#appendix-i-categories>。

> `second-field-align` 选项适配

鉴于 markdown 中不能很好地对齐显示（比如下图），不妨直接生成 html 用于显示？也可以另生成一份 markdown 用于在 GitHub 仓库中预览。

<img width="720" alt="Screen Shot 2022-08-18 at 16 34 31" src="https://user-images.githubusercontent.com/12290822/185349779-c72f23b8-6544-49ec-9245-c0ac54600027.png">

> cs:category -> field 是否需要不遵循 CSL 规范，添加 thesis（对于学位论文）、other（对于导出标题.csl）等

我更倾向于保存在样式对应的目录中的一个 YAML 文件中。另外与 `thesis` 对应的还有 `journal` 期刊样式。

个人感觉，这个属性不太重要，https://zotero-cn.github.io/styles/ 没必要弄单独“所属领域”一项。或许可以跟各种标签混合起来。

> 为需要特别适配示例数据的样式文件增加覆盖数据。

这些数据主要保存在 <https://www.zotero.org/groups/4677213/chinese_csl_development/library>，这个可以交给我处理。

**Comment by northword** [comment]
> 鉴于 markdown 中不能很好地对齐显示（比如下图），不妨直接生成 html 用于显示？也可以另生成一份 markdown 用于在 GitHub 仓库中预览。

由 Markdown 产生的 HTML 里可以正常显示，因此之需要输出时候改好样式就行。


> 我更倾向于保存在样式对应的目录中的一个 YAML 文件中。另外与 `thesis` 对应的还有 `journal` 期刊样式。
 
直接写在 csl 里是一种最简单的方式。
写 YAML 文件的话，这个文件目前就只有 thesis journal 这一个数据，如果后面有其他数据的话可以这种，只这一个分类的话会不会有一些繁琐。

我看看有没有能让脚本仅修改 md 指定区域内容的方法，这样的话就可以写在 md 的 yaml 区域，脚本更新 md 文件时候可以不覆盖，只修改。

> 个人感觉，这个属性不太重要，https://zotero-cn.github.io/styles/ 没必要弄单独“所属领域”一项。或许可以跟各种标签混合起来。

意思是把 citation-format 和 field 混起来？还是 field 和 thesis/journal 这种标签混起来？

VuePress 目前不支持多标签筛选，我去他们仓库提一个看有没可能增加这种支持，这样的话体验会更好一些。

**Comment by zepinglee** [comment]
> > 鉴于 markdown 中不能很好地对齐显示（比如下图），不妨直接生成 html 用于显示？也可以另生成一份 markdown 用于在 GitHub 仓库中预览。
> 
> 由 Markdown 产生的 HTML 里可以正常显示，因此之需要输出时候改好样式就行。

目前的 <https://zotero-cn.github.io/styles/gb-t-7714-2015/000gb-t-7714-2015-numeric-bilingual/> 显示效果如下图，它的悬挂缩进方式与 csl 样式实际效果有一定差异。

<img width="711" alt="Screen Shot 2022-08-18 at 19 53 10" src="https://user-images.githubusercontent.com/12290822/185388364-08a9206c-bd84-4f34-a061-183a2f185170.png">

我的意思是生成这样的 HTML：
```html
<html>
<body>
<div class="csl-bib-body" style="line-height: 1.35; ">
  <div class="csl-entry" style="clear: left; ">
    <div class="csl-left-margin" style="float: left; padding-right: 0.5em;text-align: right; width: 1em;">[1]</div><div class="csl-right-inline" style="margin: 0 .4em 0 1.5em;">FAN X, SOMMERS C H. Food irradiation research and technology[M/OL]. 2nd ed. Ames, Iowa: Blackwell Publishing, 2013: 25-26[2014-06-26]. <a href="http://onlinelibrary.wiley.com/doi/10.1002/9781118422557.ch2/summary">http://onlinelibrary.wiley.com/doi/10.1002/9781118422557.ch2/summary</a>.</div>
  </div>
  <div class="csl-entry" style="clear: left; ">
    <div class="csl-left-margin" style="float: left; padding-right: 0.5em;text-align: right; width: 1em;">[2]</div><div class="csl-right-inline" style="margin: 0 .4em 0 1.5em;">库恩. 科学革命的结构: 第 4 版[M]. 金吾伦, 胡新和, 译. 2 版. 北京: 北京大学出版社, 2012.</div>
  </div>
  <div class="csl-entry" style="clear: left; ">
    <div class="csl-left-margin" style="float: left; padding-right: 0.5em;text-align: right; width: 1em;">[3]</div><div class="csl-right-inline" style="margin: 0 .4em 0 1.5em;">FOURNEY M E. Advances in holographic photoelasticity[C]//Symposium on Applications of Holography in Mechanics, August 23–25, 1971, University of Southern California, Los Angeles, California. New York: ASME, c1971: 17-38.</div>
  </div>
</div></body>
</html>
```

<img width="542" alt="Screen Shot 2022-08-18 at 19 50 16" src="https://user-images.githubusercontent.com/12290822/185388022-a1eea534-b984-4908-80fe-f78f58a0764c.png">


 
> > 我更倾向于保存在样式对应的目录中的一个 YAML 文件中。另外与 `thesis` 对应的还有 `journal` 期刊样式。
> 
> 直接写在 csl 里是一种最简单的方式。 写 YAML 文件的话，这个文件目前就只有 thesis journal 这一个数据，如果后面有其他数据的话可以这种，只这一个分类的话会不会有一些繁琐。
> 
> 我看看有没有能让脚本仅修改 md 指定区域内容的方法，这样的话就可以写在 md 的 yaml 区域，脚本更新 md 文件时候可以不覆盖，只修改。
> 
> > 个人感觉，这个属性不太重要，https://zotero-cn.github.io/styles/ 没必要弄单独“所属领域”一项。或许可以跟各种标签混合起来。
> 
> 意思是把 citation-format 和 field 混起来？还是 field 和 thesis/journal 这种标签混起来？
> 
> VuePress 目前不支持多标签筛选，我去他们仓库提一个看有没可能增加这种支持，这样的话体验会更好一些。

我建议尽量不要在 csl 中添加额外的内容。`citeproc-js` 在处理 .csl 时不会检查 schema，`<category field="thesis"/>` 并不会导致报错，但是其他引擎的实现可能会检查从而导致报错。仓库中的 csl 样式最好做得更通用一些。

我之前设想的是每个样式带有多个 tag，比如“不显示 URL”、“姓氏大写”。“学位论文”、‘期刊“可以跟这些混合起来。既然多标签筛选很麻烦就先不这么搞了。

我想到一个 trick：检测样式样式标题中有没有“学位”或者“thesis”单词，如果有的话就判定为“学位论文”类型。

**Comment by northword** [comment]
> 我的意思是生成这样的 HTML：

我应该是理解了你的意思。

我目前计划的是，生成的这种 HTML 写入 README.md （不产生 xxx.html ），VuePress 将 md 渲染为网页后，悬挂缩进是可以正常显示的，虽然在 GitHub 直接查看这个 md 文件时显示并不正确。

`citeproc-js`有什么选项可以直接产生这样的 HTML 吗？还是说我们需要在脚本里根据 second-field-align 自行对 HTML 做修改？


> 我想到一个 trick：检测样式样式标题中有没有“学位”或者“thesis”单词，如果有的话就判定为“学位论文”类型。

这是一个可行的策略。

**Comment by zepinglee** [comment]
> `citeproc-js`有什么选项可以直接产生这样的 HTML 吗？还是说我们需要在脚本里根据 second-field-align 自行对 HTML 做修改？

似乎没有直接的选项，其实只要去掉这里的魔改即可。

https://github.com/zotero-cn/styles/blob/16803eba8ea4e92e2ae665ac2741c223beec8ecd/lib/generate.js#L5-L10

原来的内容是：

https://github.com/zotero-cn/styles/blob/16803eba8ea4e92e2ae665ac2741c223beec8ecd/lib/citeproc_commonjs.js#L22230-L22238

应该可以用类似方法加 `style` 属性，或者设置 CSS（我对 HTML/CSS 的了解比较浅薄）。

**Comment by northword** [comment]
> 应该可以用类似方法加 `style` 属性，或者设置 CSS（我对 HTML/CSS 的了解比较浅薄）。

明白了，我试一下！

**Comment by zepinglee** [comment]
> 去掉样式文件及其文件夹的编号前缀

这个交给我来搞。

> 确定哪些样式可以合入上游官方仓库

这些样式基本都是用 `citeproc-js` 的 [CSL-M](https://citeproc-js.readthedocs.io/en/latest/csl-m/index.html) 的扩展功能来支持双语（[cs:layout](https://citeproc-js.readthedocs.io/en/latest/csl-m/index.html#cs-layout-extension)），所以无法直接合入官方 [styles](https://github.com/citation-style-language/styles) 仓库。如过要合入官方仓库的话，需要将双语的支持部分删掉。
