### ISSUE TITLE
大佬您好，我运用了您之前开发的管理世界的格式，然后出现了一个小问题，就是我的参考文献英文出现了两个a-z的序列，请问怎么解决呀？问题如下：

### ISSUE THREAD

**Issue by YUKITOfoxx** [zotero-chinese/styles#91]
**描述错误**

CSL 样式：journal-of-management-world.csl
参考文献中出现了两条a-z的序列，即41之前为一条，42新开了一条。

预期是只有一条。

**屏幕截图**
<img width="357" alt="截屏2022-11-07 23 50 47" src="https://user-images.githubusercontent.com/115545817/200354158-959405c4-5600-41ce-9478-d51d9d432c1b.png">

**条目信息**

导出的json格式文本框表示不支持

**其他相关信息**

在此处添加有关该问题的其他信息。

**Comment by zepinglee** [comment]
把这几篇文献导出 CSL-JSON 格式贴过来，不然没法复现。

或者加入群组 <https://www.zotero.org/groups/4677213/chinese_csl_development/>，提供Zotero ID，赋予编辑权限后，将这几篇文献拖动到群组中。

<img width="294" alt="Screen Shot 2022-11-08 at 00 09 17" src="https://user-images.githubusercontent.com/12290822/200358356-9e2c64f2-d7b0-451f-bb2f-0331d1e6f76d.png">

**Comment by YUKITOfoxx** [comment]
[文献.zip](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/files/9956555/default.zip)

**Comment by YUKITOfoxx** [comment]
请问这样可以吗，导出的文献json放在文件夹里了。

**Comment by redleafnew** [comment]
![image](https://user-images.githubusercontent.com/22135631/200447048-e669f32e-b951-42c0-9e55-713979f5998f.png)
qe解压是乱码。
将json格式贴到这里即可。

**Comment by YUKITOfoxx** [comment]
[
	{
		"id": "http://zotero.org/users/8429396/items/HDTUJ7AA",
		"type": "article-journal",
		"abstract": "A clear understanding of the characteristics of generated household food waste (HFW) is necessary to formulate an effective food waste management policy. The present study has focused on the quantity and composition of generated HFW as well as the driving forces, and further explored potential means of reducing HFW. The quantity of avoidable HFW generated in Shenzhen City in 2015 was estimated to be two-fold greater than that in 2001, which consequently produced 1,378 thousand metric tonnes CO2 eq. emissions during their ultimate waste disposal. This suggests that HFW prevention can yield great environment benefits by reducing carbon emissions. Based on a survey in which 418 households in Shenzhen City participated, it was apparent that both household size and income are the major drivers to HFW generation. A substantial reduction in HFW generation can be achieved through improvements in consumer behaviors, consciousness and attitudes. Priority should be given to the strategies that can increase people’s awareness of HFW induced problems, with the purposes to achieve a more sustainable development.",
		"container-title": "Waste Management",
		"DOI": "10.1016/j.wasman.2018.06.010",
		"journalAbbreviation": "Waste Management",
		"language": "en-US",
		"source": "ResearchGate",
		"title": "Characterization of household food waste and strategies for its reduction: A Shenzhen City case study",
		"title-short": "Characterization of household food waste and strategies for its reduction",
		"volume": "78",
		"author": [
			{
				"family": "Zhang",
				"given": "Hui"
			},
			{
				"family": "Duan",
				"given": "Huabo"
			},
			{
				"family": "Andrić",
				"given": "Jelena"
			},
			{
				"family": "Song",
				"given": "Mingwei"
			},
			{
				"family": "Yang",
				"given": "Bo"
			}
		],
		"issued": {
			"date-parts": [
				[
					"2018",
					6,
					23
				]
			]
		}
	}
]

**Comment by YUKITOfoxx** [comment]
[
	{
		"id": "http://zotero.org/users/8429396/items/ZDFQC2ZU",
		"type": "article-journal",
		"abstract": "The Waste Framework Directive (WFD-2008/98/EC) has set clear waste prevention procedures, including reporting, reviewing, monitoring and evaluating. Based on the WFD, the European Commission and will offer support to Member States on how to develop waste prevention programmes through guidelines and information sharing on best practices. Monitoring and evaluating waste prevention activities are critical, as they constitute the main tools to enable policy makers, at the national and local level, to build their strategic plans and ensure that waste prevention initiatives are effective and deliver behaviour change. However, how one can measure something that is not there, remains an important and unresolved research question. The paper reviews and attempts to evaluate the methods that are being used for measuring waste prevention and the impact of relevant implemented activities at the household level, as the available data is still limited.",
		"container-title": "Waste Management",
		"DOI": "10.1016/j.wasman.2012.12.017",
		"ISSN": "0956-053X",
		"issue": "5",
		"journalAbbreviation": "Waste Management",
		"language": "en-US",
		"page": "1047-1056",
		"source": "ScienceDirect",
		"title": "Measuring waste prevention",
		"URL": "https://www.sciencedirect.com/science/article/pii/S0956053X1200582X",
		"volume": "33",
		"author": [
			{
				"family": "Zorpas",
				"given": "Antonis A."
			},
			{
				"family": "Lasaridi",
				"given": "Katia"
			}
		],
		"accessed": {
			"date-parts": [
				[
					"2022",
					9,
					26
				]
			]
		},
		"issued": {
			"date-parts": [
				[
					"2013",
					5,
					1
				]
			]
		}
	}
]

**Comment by YUKITOfoxx** [comment]
[
	{
		"id": "http://zotero.org/users/8429396/items/4ILV9NIN",
		"type": "article-journal",
		"abstract": "Food waste is a waste stream with serious economic, environmental and social implications. The emphasis of the reported research is on the food waste generated by households in Greece. A structured questionnaire was utilised in order to identify the attitudes of the respondents and investigate the prevalence of certain behavioural good practices that can prevent the generation of food waste. The research, to our knowledge the first of its kind in Greece, took place in February and March 2012. Face-to-face interviews were employed, resulting to a total of 231 consumers fully completing the questionnaire. Results indicate that, based on self-reported behaviour, people in Greece have positive attitudes towards food waste prevention and that their habits are close to the good practices suggested in the literature for reducing food waste. For instance, most respondents do plan their food shopping in a multitude of ways and are very careful in their purchases of fresh food supplies. However, about 40% misunderstand the meaning of food date labels. The positive findings are strongly influenced by the severe recession experienced in the country, which makes consumers more conscious of their spending. Results may serve as a yardstick to further promote and establish food waste prevention behaviour at the household level on an environmental and social awareness basis that may outlast the economic crisis.",
		"container-title": "Waste Management & Research",
		"DOI": "10.1177/0734242X14521681",
		"ISSN": "0734-242X",
		"issue": "3",
		"journalAbbreviation": "Waste Manag Res",
		"language": "en",
		"note": "publisher: SAGE Publications Ltd STM",
		"page": "237-240",
		"source": "SAGE Journals",
		"title": "Attitudes and behaviour of Greek households regarding food waste prevention",
		"URL": "https://doi.org/10.1177/0734242X14521681",
		"volume": "32",
		"author": [
			{
				"family": "Abeliotis",
				"given": "Konstadinos"
			},
			{
				"family": "Lasaridi",
				"given": "Katia"
			},
			{
				"family": "Chroni",
				"given": "Christina"
			}
		],
		"accessed": {
			"date-parts": [
				[
					"2022",
					9,
					26
				]
			]
		},
		"issued": {
			"date-parts": [
				[
					"2014",
					3,
					1
				]
			]
		}
	}
]

**Comment by YUKITOfoxx** [comment]
[
	{
		"id": "http://zotero.org/users/8429396/items/TQRW4Y4Z",
		"type": "article-journal",
		"abstract": "Background: Food consumption and wastage behavior varies across cultures, which warrants investigations in various countries and locations of different income levels. To date, information on the attitudes and behaviors of households in developing countries regarding food waste is scarce. The objective of this study is to assess the household attitudes and behaviors that determine food waste in Lebanon for a better understanding and for tailoring community based interventions. Methods: A questionnaire, composed of 3 sections and 27 questions, was developed to assess the attitudes and behaviors towards food waste in Lebanese households. A convenient sample of 1264 households from the five governorates of Lebanon was interviewed in 2016 and 2017. The variable “eat everything prepared” was used as a proxy for food waste. The effect of various socio-demographic and behavioral factors on household food waste generation across urban and rural areas in Lebanon was estimated by means of a Logistic regression, using STATA. Results: Socio-demographic variables such as employment, education, number of members in the household and income affected food waste volume. Behaviors such as eating out frequently and buying best offers were shown to increase food wastage. Also, beliefs such as feeling guilty decreased food waste generation. Rural households contributed less to food waste generation compared to urban areas. Conclusion: Households contribute significantly to a country's food waste problem through their behavior and beliefs. Our findings showed that various household characteristics and food-related behaviors, attitudes toward recycling and other beliefs affected food waste generation in urban and rural communities of a developing country. Future research is still needed to better understand determinants of food waste at the household level in developing countries.",
		"container-title": "Journal of Cleaner Production",
		"DOI": "10.1016/j.jclepro.2018.07.085",
		"journalAbbreviation": "Journal of Cleaner Production",
		"language": "en-US",
		"source": "ResearchGate",
		"title": "Attitudes and Behaviors Shaping Household Food Waste Generation: Lessons from Lebanon",
		"title-short": "Attitudes and Behaviors Shaping Household Food Waste Generation",
		"volume": "198",
		"author": [
			{
				"family": "Mattar",
				"given": "Lama"
			},
			{
				"family": "Abiad",
				"given": "M.G."
			},
			{
				"family": "Chalak",
				"given": "Ali"
			},
			{
				"family": "Diab",
				"given": "M."
			},
			{
				"family": "Hassan",
				"given": "Hussein"
			}
		],
		"issued": {
			"date-parts": [
				[
					"2018",
					7,
					1
				]
			]
		}
	}
]

**Comment by redleafnew** [comment]
同时选中这几个文献，导出为一个json文件

**Comment by YUKITOfoxx** [comment]
[
	{
		"id": "http://zotero.org/users/8429396/items/HDTUJ7AA",
		"type": "article-journal",
		"abstract": "A clear understanding of the characteristics of generated household food waste (HFW) is necessary to formulate an effective food waste management policy. The present study has focused on the quantity and composition of generated HFW as well as the driving forces, and further explored potential means of reducing HFW. The quantity of avoidable HFW generated in Shenzhen City in 2015 was estimated to be two-fold greater than that in 2001, which consequently produced 1,378 thousand metric tonnes CO2 eq. emissions during their ultimate waste disposal. This suggests that HFW prevention can yield great environment benefits by reducing carbon emissions. Based on a survey in which 418 households in Shenzhen City participated, it was apparent that both household size and income are the major drivers to HFW generation. A substantial reduction in HFW generation can be achieved through improvements in consumer behaviors, consciousness and attitudes. Priority should be given to the strategies that can increase people’s awareness of HFW induced problems, with the purposes to achieve a more sustainable development.",
		"container-title": "Waste Management",
		"DOI": "10.1016/j.wasman.2018.06.010",
		"journalAbbreviation": "Waste Management",
		"language": "en-US",
		"source": "ResearchGate",
		"title": "Characterization of household food waste and strategies for its reduction: A Shenzhen City case study",
		"title-short": "Characterization of household food waste and strategies for its reduction",
		"volume": "78",
		"author": [
			{
				"family": "Zhang",
				"given": "Hui"
			},
			{
				"family": "Duan",
				"given": "Huabo"
			},
			{
				"family": "Andrić",
				"given": "Jelena"
			},
			{
				"family": "Song",
				"given": "Mingwei"
			},
			{
				"family": "Yang",
				"given": "Bo"
			}
		],
		"issued": {
			"date-parts": [
				[
					"2018",
					6,
					23
				]
			]
		}
	},
	{
		"id": "http://zotero.org/users/8429396/items/TQRW4Y4Z",
		"type": "article-journal",
		"abstract": "Background: Food consumption and wastage behavior varies across cultures, which warrants investigations in various countries and locations of different income levels. To date, information on the attitudes and behaviors of households in developing countries regarding food waste is scarce. The objective of this study is to assess the household attitudes and behaviors that determine food waste in Lebanon for a better understanding and for tailoring community based interventions. Methods: A questionnaire, composed of 3 sections and 27 questions, was developed to assess the attitudes and behaviors towards food waste in Lebanese households. A convenient sample of 1264 households from the five governorates of Lebanon was interviewed in 2016 and 2017. The variable “eat everything prepared” was used as a proxy for food waste. The effect of various socio-demographic and behavioral factors on household food waste generation across urban and rural areas in Lebanon was estimated by means of a Logistic regression, using STATA. Results: Socio-demographic variables such as employment, education, number of members in the household and income affected food waste volume. Behaviors such as eating out frequently and buying best offers were shown to increase food wastage. Also, beliefs such as feeling guilty decreased food waste generation. Rural households contributed less to food waste generation compared to urban areas. Conclusion: Households contribute significantly to a country's food waste problem through their behavior and beliefs. Our findings showed that various household characteristics and food-related behaviors, attitudes toward recycling and other beliefs affected food waste generation in urban and rural communities of a developing country. Future research is still needed to better understand determinants of food waste at the household level in developing countries.",
		"container-title": "Journal of Cleaner Production",
		"DOI": "10.1016/j.jclepro.2018.07.085",
		"journalAbbreviation": "Journal of Cleaner Production",
		"language": "en-US",
		"source": "ResearchGate",
		"title": "Attitudes and Behaviors Shaping Household Food Waste Generation: Lessons from Lebanon",
		"title-short": "Attitudes and Behaviors Shaping Household Food Waste Generation",
		"volume": "198",
		"author": [
			{
				"family": "Mattar",
				"given": "Lama"
			},
			{
				"family": "Abiad",
				"given": "M.G."
			},
			{
				"family": "Chalak",
				"given": "Ali"
			},
			{
				"family": "Diab",
				"given": "M."
			},
			{
				"family": "Hassan",
				"given": "Hussein"
			}
		],
		"issued": {
			"date-parts": [
				[
					"2018",
					7,
					1
				]
			]
		}
	},
	{
		"id": "http://zotero.org/users/8429396/items/ZDFQC2ZU",
		"type": "article-journal",
		"abstract": "The Waste Framework Directive (WFD-2008/98/EC) has set clear waste prevention procedures, including reporting, reviewing, monitoring and evaluating. Based on the WFD, the European Commission and will offer support to Member States on how to develop waste prevention programmes through guidelines and information sharing on best practices. Monitoring and evaluating waste prevention activities are critical, as they constitute the main tools to enable policy makers, at the national and local level, to build their strategic plans and ensure that waste prevention initiatives are effective and deliver behaviour change. However, how one can measure something that is not there, remains an important and unresolved research question. The paper reviews and attempts to evaluate the methods that are being used for measuring waste prevention and the impact of relevant implemented activities at the household level, as the available data is still limited.",
		"container-title": "Waste Management",
		"DOI": "10.1016/j.wasman.2012.12.017",
		"ISSN": "0956-053X",
		"issue": "5",
		"journalAbbreviation": "Waste Management",
		"language": "en-US",
		"page": "1047-1056",
		"source": "ScienceDirect",
		"title": "Measuring waste prevention",
		"URL": "https://www.sciencedirect.com/science/article/pii/S0956053X1200582X",
		"volume": "33",
		"author": [
			{
				"family": "Zorpas",
				"given": "Antonis A."
			},
			{
				"family": "Lasaridi",
				"given": "Katia"
			}
		],
		"accessed": {
			"date-parts": [
				[
					"2022",
					9,
					26
				]
			]
		},
		"issued": {
			"date-parts": [
				[
					"2013",
					5,
					1
				]
			]
		}
	},
	{
		"id": "http://zotero.org/users/8429396/items/4ILV9NIN",
		"type": "article-journal",
		"abstract": "Food waste is a waste stream with serious economic, environmental and social implications. The emphasis of the reported research is on the food waste generated by households in Greece. A structured questionnaire was utilised in order to identify the attitudes of the respondents and investigate the prevalence of certain behavioural good practices that can prevent the generation of food waste. The research, to our knowledge the first of its kind in Greece, took place in February and March 2012. Face-to-face interviews were employed, resulting to a total of 231 consumers fully completing the questionnaire. Results indicate that, based on self-reported behaviour, people in Greece have positive attitudes towards food waste prevention and that their habits are close to the good practices suggested in the literature for reducing food waste. For instance, most respondents do plan their food shopping in a multitude of ways and are very careful in their purchases of fresh food supplies. However, about 40% misunderstand the meaning of food date labels. The positive findings are strongly influenced by the severe recession experienced in the country, which makes consumers more conscious of their spending. Results may serve as a yardstick to further promote and establish food waste prevention behaviour at the household level on an environmental and social awareness basis that may outlast the economic crisis.",
		"container-title": "Waste Management & Research",
		"DOI": "10.1177/0734242X14521681",
		"ISSN": "0734-242X",
		"issue": "3",
		"journalAbbreviation": "Waste Manag Res",
		"language": "en",
		"note": "publisher: SAGE Publications Ltd STM",
		"page": "237-240",
		"source": "SAGE Journals",
		"title": "Attitudes and behaviour of Greek households regarding food waste prevention",
		"URL": "https://doi.org/10.1177/0734242X14521681",
		"volume": "32",
		"author": [
			{
				"family": "Abeliotis",
				"given": "Konstadinos"
			},
			{
				"family": "Lasaridi",
				"given": "Katia"
			},
			{
				"family": "Chroni",
				"given": "Christina"
			}
		],
		"accessed": {
			"date-parts": [
				[
					"2022",
					9,
					26
				]
			]
		},
		"issued": {
			"date-parts": [
				[
					"2014",
					3,
					1
				]
			]
		}
	}
]



请问这样可以吗，上面是四条文献的json，前两条作者是Z开头的后两条是A开头的，是图片中序号的40-43

**Comment by redleafnew** [comment]
应该是是什么样的排序才对？

**Comment by YUKITOfoxx** [comment]
我希望42之后的文献能进入1-41的排序里面。两个排序都是完整的🤦
<img width="126" alt="截屏2022-11-08 09 53 11" src="https://user-images.githubusercontent.com/115545817/200454650-9a484128-0f21-4f62-9c75-72183f8e6725.png">
<img width="119" alt="截屏2022-11-08 09 53 36" src="https://user-images.githubusercontent.com/115545817/200454657-55448198-9587-47e9-ae33-cb13233ac89d.png">

**Comment by redleafnew** [comment]
作者升序是不正常：

> （Abeliotis et al., 2014; Mattar et al., 2018; Zhang et al., 2018; Zorpas & Lasaridi, 2013）
> （1）Mattar L., Abiad M.G., Chalak A., et al., 2018, “Attitudes and Behaviors Shaping Household Food Waste Generation: Lessons from Lebanon”, Journal of Cleaner Production, 198.
> （2）Zhang H., Duan H., Andrić J., et al., 2018, “Characterization of household food waste and strategies for its reduction: A Shenzhen City case study”, Waste Management, 78.
> （3）Zorpas A.A., Lasaridi K., 2013, “Measuring waste prevention”, Waste Management, 33(5), pp. 1047~1056.
> （4）Abeliotis K., Lasaridi K., Chroni C., 2014, “Attitudes and behaviour of Greek households regarding food waste prevention”, Waste Management & Research, 32(3), pp. 237~240.

作者降序正常：

> （1）Zorpas A.A., Lasaridi K., 2013, “Measuring waste prevention”, Waste Management, 33(5), pp. 1047~1056.
> （2）Zhang H., Duan H., Andrić J., et al., 2018, “Characterization of household food waste and strategies for its reduction: A Shenzhen City case study”, Waste Management, 78.
> （3）Mattar L., Abiad M.G., Chalak A., et al., 2018, “Attitudes and Behaviors Shaping Household Food Waste Generation: Lessons from Lebanon”, Journal of Cleaner Production, 198.
> （4）Abeliotis K., Lasaridi K., Chroni C., 2014, “Attitudes and behaviour of Greek households regarding food waste prevention”, Waste Management & Research, 32(3), pp. 237~240.

@zepinglee 与locale的设置有关？

**Comment by YUKITOfoxx** [comment]
所以把文献全部改成en-US即可解决问题是吗？非常感谢两位大佬！

**Comment by redleafnew** [comment]
@zepinglee 我也看漏了，看三个都是en-US，没想还有一个en的

**Comment by YUKITOfoxx** [comment]
收到，非常感谢！祝您生活愉快。

**Comment by YUKITOfoxx** [comment]
好的，感谢您，祝您生活愉快。
